phy: qcom-qmp: select COMMON_CLK
It is impossible to build Qualcom QMP phy driver without COMMON_CLK
enabled:
  CC      drivers/phy/phy-qcom-qmp.o
drivers/phy/phy-qcom-qmp.c: In function ‘phy_pipe_clk_register’:
drivers/phy/phy-qcom-qmp.c:932:9: error: variable ‘init’ has initializer
but incomplete type
  struct clk_init_data init = { };
         ^~~~~~~~~~~~~
drivers/phy/phy-qcom-qmp.c:932:23: error: storage size of ‘init’ isn’t
known
  struct clk_init_data init = { };
                       ^~~~
...

Selecting COMMON_CLK when PHY_QCOM_QMP is enabled fix this issue.

Fixes: 93a8c0c7b1ad ("phy: qcom-qmp: new qmp phy driver for qcom-chipsets")
Signed-off-by: Jérémy Lefaure <jeremy.lefaure@lse.epita.fr>