char: tb0219: fix build failure
The build of mips tb0219_defconfig was failing with the error:

drivers/char/tb0219.c:188:2:
	error: implicit declaration of function 'put_user'
drivers/char/tb0219.c:216:3:
	error: implicit declaration of function 'get_user'

Quoting Al Viro - "another victim of indirect include chains"

Fixes: 58a8f3b69e07 ("mips: separate extable.h, switch module.h to it")
Cc: Al Viro <viro@zeniv.linux.org.uk>
Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>