VIDEO_MEDIATEK_VCODEC should depend on HAS_DMA
If NO_DMA=y:

    warning: (VIDEO_MEDIATEK_VCODEC && VIDEO_DM365_VPFE && VIDEO_OMAP4) selects VIDEOBUF2_DMA_CONTIG which has unmet direct dependencies (MEDIA_SUPPORT && HAS_DMA)

    drivers/media/v4l2-core/videobuf2-dma-contig.c: In function ‘vb2_dc_get_userptr’:
    drivers/media/v4l2-core/videobuf2-dma-contig.c:486: error: implicit declaration of function ‘dma_get_cache_alignment’

VIDEO_MEDIATEK_VCODEC selects VIDEOBUF2_DMA_CONTIG, which bypasses its
dependency on HAS_DMA.  Make VIDEO_MEDIATEK_VCODEC depend on HAS_DMA to
fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>