perf tests: Delete mis-indented dead code that causes build failure with gcc 6
gcc 6 complains:

arch/x86/tests/intel-cqm.c: In function 'spawn':
arch/x86/tests/intel-cqm.c:21:3: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]
   sleep(5);
   ^~~~~

arch/x86/tests/intel-cqm.c:20:2: note: ...this 'while' clause, but it is not
  while(1);
  ^~~~~

Fixes: 035827e9f2bd ("perf tests: Add Intel CQM test")
Signed-off-by: Ben Hutchings <ben@decadent.org.uk>