MIPS: perf: fix build failure
The build of gpr_defconfig is failing with the error:
arch/mips/kernel/perf_event_mipsxx.c:
	In function 'mipsxx_pmu_map_raw_event':
arch/mips/kernel/perf_event_mipsxx.c:1614:2:
	error: duplicate case value

Patch - f7a31b5e7874 ("MIPS: perf: Remove incorrect odd/even counter
handling for I6400") removed the previous case and added it as a
separate case. But patch dd71e57bacb5 ("MIPS: perf: add I6500 handling")
added it back to its old location and thus giving us two duplicate case.

Fixes: dd71e57bacb5 ("MIPS: perf: add I6500 handling")
Signed-off-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>