crypto: hide unused label
A recent change left an existing label unused in some configurations,
as seen from a gcc warning:

crypto/xor.c: In function 'calibrate_xor_blocks':
crypto/xor.c:156:1: error: label 'out' defined but not used [-Werror=unused-label]

This adds an #ifdef around it to match the one around the respective "goto".

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 39457acda913 ("crypto: xor - skip speed test if the xor function is selected automatically")