irqdomain: fix compiling when IRQ_DOMAIN unset
When config option IRQ_DOMAIN is unset, compiling the file
'drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c' fails:

      CC      drivers/gpu/drm/amd/amdgpu/amdgpu_irq.o
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c: In function ‘amdgpu_irq_dispatch’:
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c:345:3: error: implicit declaration of
        function ‘irq_find_mapping’ [-Werror=implicit-function-declaration]
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c: In function ‘amdgpu_irq_add_domain’:
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c:529:2: error: implicit declaration of
        function ‘irq_domain_add_linear’ [-Werror=implicit-function-declaration]
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c: In function ‘amdgpu_irq_remove_domain’:
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c:550:3: error: implicit declaration of
        function ‘irq_domain_remove’ [-Werror=implicit-function-declaration]
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c: In function ‘amdgpu_irq_create_mapping’:
    drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c:569:2: error: implicit declaration of
        function ‘irq_create_mapping’ [-Werror=implicit-function-declaration]

Adding the functions stubs in the header file so it compiles cleanly.
Maybe the drm driver 'amdgpu' should select the config option IRQ_DOMAIN
if it cannot work without it. But I don't know if that's necessary.

Signed-off-by: Stefan Christ <contact@stefanchrist.eu>