dma: remove bad_dma_ops to fix build fail
m32r allmodconfig is failng with errors like:
ERROR: "bad_dma_ops" [sound/soc/bcm/snd-soc-cygnus.ko] undefined!

On checking the code it turns out that struct bad_dma_ops has been
declared as extern but no one has actually defined struct bad_dma_ops.
Lets remove that and return NULL from get_dma_ops() if HAS_DMA is not
defined.

Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>