watchdog: ath79_wdt: fix build failure
The build of mips ath79_defconfig was failing with the error:
drivers/watchdog/ath79_wdt.c:164:5:
	error: implicit declaration of function 'get_user'
drivers/watchdog/ath79_wdt.c:196:3:
	error: implicit declaration of function 'copy_to_user'
drivers/watchdog/ath79_wdt.c:201:3:
	error: implicit declaration of function 'put_user'

Quoting Al Viro - "another victim of indirect include chains"

Fixes: 58a8f3b69e07 ("mips: separate extable.h, switch module.h to it")
Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>