undefined reference to `early_panic'
On Sun, 5 Jun 2016 12:33:29 +0800 kbuild test robot <fengguang.wu@intel.com> wrote:

> It's probably a bug fix that unveils the link errors.
>
> tree:   https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git master
> head:   049ec1b5a76d34a6980cccdb7c0baeb4eed7a993
> commit: 888cdbc2c9a76a0e450f533b1957cdbfe7d483d5 hugetlb: fix compile error on tile
> date:   5 months ago
> config: tile-allnoconfig (attached as .config)
> compiler: tilegx-linux-gcc (GCC) 4.6.2
> reproduce:
>         wget https://git.kernel.org/cgit/linux/kernel/git/wfg/lkp-tests.git/plain/sbin/make.cross -O ~/bin/make.cross
>         chmod +x ~/bin/make.cross
>         git checkout 888cdbc2c9a76a0e450f533b1957cdbfe7d483d5
>         # save the attached .config to linux build tree
>         make.cross ARCH=tile
>
> All errors (new ones prefixed by >>):
>
>    arch/tile/built-in.o: In function `setup_arch':
> >> (.init.text+0x15d8): undefined reference to `early_panic'
>    arch/tile/built-in.o: In function `setup_arch':
>    (.init.text+0x1610): undefined reference to `early_panic'
>    arch/tile/built-in.o: In function `setup_arch':
>    (.init.text+0x1800): undefined reference to `early_panic'
>    arch/tile/built-in.o: In function `setup_arch':
>    (.init.text+0x1828): undefined reference to `early_panic'
>    arch/tile/built-in.o: In function `setup_arch':
>    (.init.text+0x1bd8): undefined reference to `early_panic'
>    arch/tile/built-in.o:(.init.text+0x1c18): more undefined references to `early_panic' follow

This?

From: Andrew Morton <akpm@linux-foundation.org>
Subject: tile: early_printk.o is always required

arch/tile/setup.o is always compiled, and it requires early_panic() and
hence early_printk(), so we must always build and link early_printk.o.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Cc: Chris Metcalf <cmetcalf@mellanox.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>