drm: arm-hdlcd: remove DMA_CMA select
The newly added DRM_HDLCD driver tries to select DMA_CMA, but that is
not necessarily possible, as not all configurations contain HAVE_DMA_CONTIGUOUS:

warning: (DRM_HDLCD) selects DMA_CMA which has unmet direct dependencies (HAVE_DMA_CONTIGUOUS && CMA)
drivers/built-in.o: In function `dma_alloc_from_contiguous':
:(.text+0x1dee00): undefined reference to `cma_alloc'
drivers/built-in.o: In function `dma_release_from_contiguous':
:(.text+0x1dee24): undefined reference to `cma_release'

This removes the 'select' statement. It is not needed because CMA is meant
to transparently change the behavior of dma_alloc_coherent to make it succeed
for larger allocations, but there is no actual build-time dependency, and
the driver can still work without CMA in many cases.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 1561e558334d ("drm: Add support for ARM's HDLCD controller.")