x86/vdso: Add ARCH_MAP_VDSO_X32 if CONFIG_X86_X32_ABI.
vdso_image_x32 is generated if CONFIG_X86_X32_ABI.

This patch fixes this build error on CentOS 6.8 with gcc 4.4.

  LD      init/built-in.o
arch/x86/built-in.o: In function `do_arch_prctl':
(.text+0x27466): undefined reference to `vdso_image_x32'
arch/x86/built-in.o: In function `do_arch_prctl':
(.text+0x27477): undefined reference to `vdso_image_x32'

Fixes: 2eefd8789698 ("x86/arch_prctl/vdso: Add ARCH_MAP_VDSO_*")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>