Bluetooth: btintel: remove extraneous semicolon
The newly added btintel_download_firmware() dummy helper definition is
incorrect, causing a build error when CONFIG_BT_INTEL is disabled:

In file included from drivers/bluetooth/hci_ldisc.c:49:0:
drivers/bluetooth/btintel.h:196:1: error: expected identifier or '(' before '{' token
drivers/bluetooth/btintel.h:193:19: error: 'btintel_download_firmware' declared 'static' but never defined [-Werror=unused-function]

Removing the semicolon makes it work again.

Fixes: 0bd4ded3287d ("Bluetooth: btintel: Create common function for firmware download")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>