Revert "clocksource/drivers/timer-atmel-st: Add the COMPILE_TEST option"
This reverts commit 7011a4947ca61cd28a8c025b39c98861687e4fb6.

When trying to build parisc:allmodconfig:

drivers/clocksource/timer-atmel-st.c: In function 'at91rm9200_timer_interrupt':
drivers/clocksource/timer-atmel-st.c:76:3: error:
	invalid use of undefined type 'struct clock_event_device'

Cc: Daniel Lezcano <daniel.lezcano@linaro.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>