mn10300, c6x: CONFIG_GENERIC_BUG must depend on CONFIG_BUG
On Tue, 1 Mar 2016 14:18:56 +0800 kbuild test robot <lkp@intel.com> wrote:

> [auto build test ERROR on v4.5-rc6]
> [also build test ERROR on next-20160229]
> [if your patch is applied to the wrong git tree, please drop us a note to help improving the system]
>
> url:    https://github.com/0day-ci/linux/commits/Andrew-Morton/mn10300-c6x-CONFIG_GENERIC_BUG-must-depend-on-CONFIG_BUG/20160301-045134
> config: mn10300-allnoconfig (attached as .config)
> reproduce:
>         wget https://git.kernel.org/cgit/linux/kernel/git/wfg/lkp-tests.git/plain/sbin/make.cross -O ~/bin/make.cross
>         chmod +x ~/bin/make.cross
>         # save the attached .config to linux build tree
>         make.cross ARCH=mn10300
>
> All errors (new ones prefixed by >>):
>
> >> arch/mn10300/kernel/fpu-nofpu.c:27:36: error: unknown type name 'elf_fpregset_t'
>     int dump_fpu(struct pt_regs *regs, elf_fpregset_t *fpreg)

hm, that error isn't well correlated with that patch!

This, I suppose.  I don't have an mn10300 cross-compiler.

From: Andrew Morton <akpm@linux-foundation.org>
Subject: arch/mn10300/kernel/fpu-nofpu.c: needs asm/elf.h

 arch/mn10300/kernel/fpu-nofpu.c:27:36: error: unknown type name 'elf_fpregset_t'
    int dump_fpu(struct pt_regs *regs, elf_fpregset_t *fpreg)

Reported-by: kbuild test robot <lkp@intel.com>
Cc: Josh Triplett <josh@joshtriplett.org>
Cc: David Howells <dhowells@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>