i2c: designware: fix platform driver probe rename
A function rename was incomplete and missed the !CONFIG_PM
case:

i2c-designware-platdrv.c:340:13: error: 'dw_i2c_plat_prepare' undeclared here (not in a function)
i2c-designware-platdrv.c:341:14: error: 'dw_i2c_plat_complete' undeclared here (not in a function)

This renames the macros accordingly.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 6ad6fde3970c ("i2c: designware: Rename platform driver probe and PM functions")