debugfs: inline dummy implementations of debugfs_use_file_start()/_finish()
In commit 921d5cbeb37c ("debugfs: prevent access to removed files'
                         private data")
the functions debugfs_use_file_start() and debugfs_use_file_finish() have
been exported from the debugfs core.

Unfortunately, the inline keyword has been missed at their noop
implementations provided for the CONFIG_DEBUG_FS=n case.

Due to this lapse, the kbuild test robot moans on a powerpc defconfig
build:

  In file included from arch/powerpc/kernel/irq.c:54:0:
    include/linux/debugfs.h:185:12: error: 'debugfs_use_file_start'
      defined but not used [-Werror=unused-function]
      static int debugfs_use_file_start(const struct dentry *dentry,
                                        int *srcu_idx)

    include/linux/debugfs.h:191:13: error: 'debugfs_use_file_finish'
      defined but not used [-Werror=unused-function]
      static void debugfs_use_file_finish(int srcu_idx)

Add the inline keyword to the CONFIG_DEBUG_FS=n noop implementations of
debugfs_use_file_start() and debugfs_use_file_finish().

Signed-off-by: Nicolai Stange <nicstange@gmail.com>