cpufreq: select IRQ_WORK in Kconfig
The cpufreq core code has started using the irq_work infrastructure, but that
can be disabled in Kconfig, causing a link failure:

drivers/cpufreq/cpufreq_governor.c: In function 'gov_queue_irq_work':
drivers/cpufreq/cpufreq_governor.c:251:3: error: implicit declaration of function 'irq_work_queue_on' [-Werror=implicit-function-declaration]

This adds an explicit 'select' to ensure it's always enabled.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 0144fa03ef46 ("cpufreq: governor: Replace timers with utilization update callbacks")