infiniband: rxe: add UDP_TUNNEL dependency
The newly added rxe driver links against the UDP tunneling code,
which causes build errors when CONFIG_UDP_TUNNEL is disabled:

ERROR: "setup_udp_tunnel_sock" [drivers/infiniband/hw/rxe/ib_rxe.ko] undefined!
ERROR: "udp_tunnel_sock_release" [drivers/infiniband/hw/rxe/ib_rxe.ko] undefined!
ERROR: "udp_sock_create4" [drivers/infiniband/hw/rxe/ib_rxe.ko] undefined!

This adds a Kconfig dependency to prevent the invalid configuration.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>