mtd: spi-nor: stm32: remove broken MODULE_ALIAS
The MODULE_ALIAS statement refers to a macro that has never been defined
in this driver, causing a build error:

drivers/mtd/spi-nor/stm32-quadspi.c:694:150: error: expected ',' or ';' before 'DRIVER_NAME'

Unless there is a specific alias we need other then the driver name,
we don't need an alias here and can simply remove the line to fix the
build.

Fixes: dc5e400611c5 ("mtd: spi-nor: add driver for STM32 quad spi flash controller")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>