nds32: Fix build error caused by incomplete configuration flag rename
GENERIC_ASHLDI3, GENERIC_ASHRDI3, and GENERIC_LSHRDI3 were renamed to
GENERIC_LIB_ASHLDI3, GENERIC_LIB_ASHRDI3, and GENERIC_LIB_LSHRDI3
without making the matching changes in arch/nds32. This results in
the following build errors.

nds32le-linux-ld: kernel/time/timekeeping.o:
	in function `timekeeping_init':
timekeeping.c:(.init.text+0x140):
	undefined reference to `__ashldi3'
nds32le-linux-ld: timekeeping.c:(.init.text+0x144):
	undefined reference to `__ashldi3'
nds32le-linux-ld: timekeeping.c:(.init.text+0x17e):
	undefined reference to `__lshrdi3'
nds32le-linux-ld: timekeeping.c:(.init.text+0x182):
	undefined reference to `__lshrdi3'
nds32le-linux-ld: drivers/clocksource/mmio.o:
	in function `clocksource_mmio_init':
mmio.c:(.init.text+0x54):
	undefined reference to `__lshrdi3'
nds32le-linux-ld: mmio.c:(.init.text+0x58):
	undefined reference to `__lshrdi3'

Fixes: e3d5980568f ("lib: Rename compiler intrinsic selects to GENERIC_LIB_*")
Cc: Matt Redfearn <matt.redfearn@mips.com>
Cc: James Hogan <jhogan@kernel.org>
Cc: Palmer Dabbelt <palmer@sifive.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>