arm: fixmap: Annotate page flags with pgprot
With STRICT_MM_TYPECHECKS, the kernel build fails like :

  CC      mm/early_ioremap.o
mm/early_ioremap.c: In function ‘early_ioremap’:
mm/early_ioremap.c:211:2: error: incompatible type for argument 3 of ‘__early_ioremap’
mm/early_ioremap.c:98:1: note: expected ‘pgprot_t’ but argument is of type ‘long long unsigned int’
mm/early_ioremap.c: In function ‘early_memremap’:
mm/early_ioremap.c:219:13: error: incompatible type for argument 3 of ‘__early_ioremap’
mm/early_ioremap.c:98:1: note: expected ‘pgprot_t’ but argument is of type ‘long long unsigned int’
mm/early_ioremap.c: In function ‘early_memremap_ro’:
mm/early_ioremap.c:225:2: error: incompatible type for argument 3 of ‘__early_ioremap’
mm/early_ioremap.c:98:1: note: expected ‘pgprot_t’ but argument is of type ‘long long unsigned int’
mm/early_ioremap.c:226:1: warning: control reaches end of non-void function [-Wreturn-type]
mm/early_ioremap.c: In function ‘early_memremap’:
mm/early_ioremap.c:220:1: warning: control reaches end of non-void function [-Wreturn-type]
mm/early_ioremap.c: In function ‘early_ioremap’:
mm/early_ioremap.c:212:1: warning: control reaches end of non-void function [-Wreturn-type]
make[1]: *** [mm/early_ioremap.o] Error 1
make: *** [mm] Error 2
make: *** Waiting for unfinished jobs....
  CC      arch/arm/mm/mmu.o
  CC      arch/arm/kernel/patch.o
arch/arm/kernel/patch.c: In function ‘patch_map’:
arch/arm/kernel/patch.c:39:2: error: incompatible type for argument 3 of ‘__set_fixmap’
./arch/arm/include/asm/fixmap.h:55:6: note: expected ‘pgprot_t’ but argument is of type ‘long long unsigned int’
make[1]: *** [arch/arm/kernel/patch.o] Error 1

Fixes Commit a5f4c561b ("ARM: 8415/1: early fixmap support for earlycon").

Annotate the page flags properly using __pgprot.

Cc: Stefan Agner <stefan@agner.ch>
Cc: Arnd Bergmann <arnd@arndb.de>
Cc: Ard Biesheuvel <ard.biesheuvel@linaro.org>
Cc: Rob Herring <robh@kernel.org>
Cc: Russell King <rmk+kernel@arm.linux.org.uk>
Cc: stable@vger.kernel.org	# v4.3+
Signed-off-by: Suzuki K Poulose <suzuki.poulose@arm.com>