nilfs: avoid warning about unused variables
The newly added nilfs_msg() infrastructure caused a warning in
nilfs_clear_dirty_page() when it is disabled:

fs/nilfs2/page.c: In function 'nilfs_clear_dirty_page':
fs/nilfs2/page.c:402:22: error: unused variable 'sb' [-Werror=unused-variable]
  struct super_block *sb = inode->i_sb;

We can avoid the warning by adding a cast to void for the first
argument of the macro.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: aede53d223f0 ("nilfs2: replace nilfs_warning() with nilfs_msg()")