i915: fix build on gcc7
With gcc7, the conditional usage of (port == PORT_A ? PORT_C : PORT_A)
triggers -Werror=int-in-bool-context which breaks the build. Instead,
use a temporary port_other variable that avoids hitting this error.

  % gcc --version
  gcc (SUSE Linux) 7.1.1 20170517 [gcc-7-branch revision 248152]
  Copyright (C) 2017 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  % make -j8 drivers/gpu/drm/i915/intel_dsi.o
  In file included from drivers/gpu/drm/i915/intel_dsi.c:34:0:
  drivers/gpu/drm/i915/intel_dsi.c: In function ‘intel_dsi_prepare’:
  drivers/gpu/drm/i915/intel_dsi.c:1487:23: error: ?: using integer constants in boolean context [-Werror=int-in-bool-context]
         PORT_A ? PORT_C : PORT_A),
  drivers/gpu/drm/i915/i915_drv.h:3909:76: note: in definition of macro ‘I915_WRITE’
   #define I915_WRITE(reg, val) dev_priv->uncore.funcs.mmio_writel(dev_priv, (reg), (val), true)
                                                                              ^~~
  drivers/gpu/drm/i915/i915_reg.h:8280:32: note: in expansion of macro ‘_MMIO’
   #define _MMIO_MIPI(port, a, c) _MMIO(_MIPI_PORT(port, a, c))
                                  ^~~~~
  drivers/gpu/drm/i915/i915_reg.h:8280:38: note: in expansion of macro ‘_MIPI_PORT’
   #define _MMIO_MIPI(port, a, c) _MMIO(_MIPI_PORT(port, a, c))
                                        ^~~~~~~~~~
  drivers/gpu/drm/i915/i915_reg.h:8624:32: note: in expansion of macro ‘_MMIO_MIPI’
   #define MIPI_INIT_COUNT(port)  _MMIO_MIPI(port, _MIPIA_INIT_COUNT, _MIPIC_INIT_COUNT)
                                  ^~~~~~~~~~
  drivers/gpu/drm/i915/intel_dsi.c:1486:15: note: in expansion of macro ‘MIPI_INIT_COUNT’
      I915_WRITE(MIPI_INIT_COUNT(port ==
                 ^~~~~~~~~~~~~~~

Signed-off-by: Aleksa Sarai <asarai@suse.de>