powerpc/4xx/ocm: fix compilation error
This patch fixes a recent compilation regression in ocm:

| ocm.c: In function ‘ocm_init_node’:
| ocm.c:182:18: error: invalid operands to binary |
|       (have ‘int’ and ‘pgprot_t’ {aka ‘struct <anonymous>’})
|       _PAGE_EXEC | PAGE_KERNEL_NCG);
|                  ^
|
| ocm.c:197:17: error: invalid operands to binary |
|       (have ‘int’ and ‘pgprot_t’ {aka ‘struct <anonymous>’})
|        _PAGE_EXEC | PAGE_KERNEL);
|                   ^

Fixes: 56f3c1413f5c ("powerpc/mm: properly set PAGE_KERNEL flags in ioremap()")
Signed-off-by: Christian Lamparter <chunkeey@gmail.com>