slub: avoid false-postive warning
The slub allocator gives us some incorrect warnings when
CONFIG_PROFILE_ANNOTATED_BRANCHES is set, as the unlikely()
macro prevents it from seeing that the return code matches
what it was before:

mm/slub.c: In function ‘kmem_cache_free_bulk’:
mm/slub.c:262:23: error: ‘df.s’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
mm/slub.c:2943:3: error: ‘df.cnt’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
mm/slub.c:2933:4470: error: ‘df.freelist’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
mm/slub.c:2943:3: error: ‘df.tail’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

I have not been able to come up with a perfect way for dealing with
this, the three options I see are:

- add a bogus initialization, which would increase the runtime overhead
- replace unlikely() with unlikely_notrace()
- remove the unlikely() annotation completely

I checked the object code for a typical x86 configuration and the
last two cases produce the same result, so I went for the last
one, which is the simplest.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>