KEYS: fix build failure with CONFIG_KEY_DH_OPERATIONS
With CONFIG_KEY_DH_OPERATIONS=y and CONFIG_CRYPTO=m we get the following
link error:

security/built-in.o: In function `__keyctl_dh_compute':
device_cgroup.c:(.text+0x925c): undefined reference to 'crypto_alloc_shash'
device_cgroup.c:(.text+0x9510): undefined reference to 'crypto_shash_update'
device_cgroup.c:(.text+0x9548): undefined reference to 'crypto_shash_update'
device_cgroup.c:(.text+0x957c): undefined reference to 'crypto_shash_final'
device_cgroup.c:(.text+0x95d0): undefined reference to 'crypto_shash_final'
device_cgroup.c:(.text+0x9710): undefined reference to 'crypto_destroy_tfm'

Fix this by selecting the crypto core in order to reach the functions above.

Fixes: f1c316a3ab9d ("KEYS: add SP800-56A KDF support for DH")
Signed-off-by: Tobias Regnery <tobias.regnery@gmail.com>