net: avoid uninitialized variable
when I compiler the newest kernel, I hit the following error with
Werror=may-uninitalized.

net/core/flow_dissector.c: In function ?._skb_flow_dissect?
include/uapi/linux/swab.h:100:46: error: ?.lan?.may be used uninitialized in this function [-Werror=maybe-uninitialized]
net/core/flow_dissector.c:248:26: note: ?.lan?.was declared here

This adds an additional check for proto to explicitly tell the compiler
that vlan pointer have the correct value before it is used.

Signed-off-by: zhong jiang <zhongjiang@huawei.com>