ACPI: Fix build failure when CONFIG_NLS is set to 'n'
Observing link failure as follows when CONFIG_ACPI is set but
both CONFIG_NLS and CONFIG_PCI are unset.

drivers/acpi/device_sysfs.o: In function `description_show':
device_sysfs.c:(.text+0x48a): undefined reference to `utf16s_to_utf8s'

This issue has been previously fxed by
'commit 8a226e00eeed ("PCI: pci-label: Fix build failure when CONFIG_NLS
is set to 'm' by allmodconfig")' selecting NLS when ACPI is present.

Now that it is possible to have ACPI without PCI, we need an alternative
select statement inside the ACPI kconfig.

Fixes: 5d32a66541c46 ("PCI/ACPI: Allow ACPI to be built without CONFIG_PCI set")
Signed-off-by: Sinan Kaya <okaya@kernel.org>