staging: pi433: fix thread_run failure check
The check for thread_run failure is incorrect, use IS_ERR instead.

Cleans up sparse error message:
"error: incompatible types for operation (<)"

Fixes: 874bcba65f9a ("staging: pi433: New driver")
Signed-off-by: Colin Ian King <colin.king@canonical.com>