debugobjects: fix debug_objects_freed accounting
The removal of the batched object freeing has caused the debug_objects_freed
to become read-only, and the reading is inside an ifdef, so gcc warns that it
is completely unused without CONFIG_DEBUG_FS:

lib/debugobjects.c:71:14: error: 'debug_objects_freed' defined but not used [-Werror=unused-variable]

Assuming we are still interested in this number, this adds back code to
count every instance we are about to free while we still hold the spinlock.

Fixes: 636e1970fd7d ("debugobjects: Use global free list in free_object()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>