mm: hugepage: make hstate_is_gigantic() inline
Ignoring the argument of both alloc_huge_page_node() and hstate_is_gigantic()
causes a harmless warning:

mm/memory-failure.c: In function 'new_page':
mm/memory-failure.c:1493:18: error: unused variable 'hstate' [-Werror=unused-variable]

Turning one into an inline function makes the compiler see that the variable is
not meant to be unused.

Fixes: d81a077951f8 ("mm/madvise: enable (soft|hard) offline of HugeTLB pages at PGD level")
Fixes: 39b80148ffd7 ("mm/follow_page_mask: add support for hugepage directory entry")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>