m68k: fix build failure
The defconfig build of m68k was failing with the error:
implicit declaration of function '__pfn_to_phys'

Other architectures have added <asm/memory.h>, but if we do so here then
we will also get redeclaration of some other functions. So it is better
to copy these macros into page_mm.h.

Fixes: 0a3c3bf11240 ("x86, mm: introduce vmem_altmap to augment vmemmap_populate()")
Cc: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>