RDMA/core: Fix a violation of the C standard
This patch avoids that sparse reports the following:

drivers/infiniband/core/uverbs_std_types_cq.c:206:1: error: directive in argument list
drivers/infiniband/core/uverbs_std_types_cq.c:209:1: error: directive in argument list

Additionally, this patch also avoids that sparse warns about defined
but not used functions with CONFIG_INFINIBAND_EXP_LEGACY_VERBS_NEW_UAPI=n.

Fixes: 185899ee8d00 ("IB/uverbs: Enable ioctl() uAPI by default for new verbs")
Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
Cc: Matan Barak <matanb@mellanox.com>
Cc: Leon Romanovsky <leonro@mellanox.com>