locktorture: style fix - spaces required around
This patch fixes the following checkpatch.pl errors:

ERROR: spaces required around that ':' (ctx:VxW)
+                torture_type, tag, cxt.debug_lock ? " [debug]": "",
                                                               ^

Signed-off-by: Wen Yang <wen.yang99@zte.com.cn>
CC: Davidlohr Bueso <dave@stgolabs.net>
CC: "Paul E. McKenney" <paulmck@linux.ibm.com>
CC: Josh Triplett <josh@joshtriplett.org>
CC: linux-kernel@vger.kernel.org