drm/p[111: add CONFIG_OF dependency
We cannot select a symbol without meeting its other dependencies:

warning: (DRM_PL111) selects DRM_DUMB_VGA_DAC which has unmet direct dependencies (HAS_IOMEM && DRM && DRM_BRIDGE && OF)
drivers/gpu/drm/bridge/dumb-vga-dac.c: In function 'dumb_vga_probe':
drivers/gpu/drm/bridge/dumb-vga-dac.c:207:13: error: 'struct drm_bridge' has no member named 'of_node'
  vga->bridge.of_node = pdev->dev.of_node;
             ^

Here it seems reasonable to depend on CONFIG_OF, as all platforms
using this driver already require that anyway.

Fixes: 49f81d80ab84 ("drm/pl111: Support handling bridge timings")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>