perf/core: Remove unused function perf_cgroup_event_cgrp_time()
The function was added by commit e5d1367f17ba ("perf: Add cgroup
support") in 2011 and hasn't been used since then. Removing it fixes the
following warning when building with clang:

    kernel/events/core.c:696:19: error: unused function
        'perf_cgroup_event_cgrp_time' [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>