platform/x86: intel_pmc_ipc: Delete unused function ipc_data_readb()
The function was added by commit 0a8b83530b6f ("intel_pmc_ipc: Add Intel
Apollo Lake PMC IPC driver") in 2015 and hasn't been used since then.
Removing it fixes the following warning when building with clang:

    drivers/platform/x86/intel_pmc_ipc.c:189:18: error: unused function
        'ipc_data_readb' [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>