usb: hide usb_of_get_companion_dev for CONFIG_USB=n
The renesas UDC implementation now calls usb_of_get_companion_dev(),
which is only defined when CONFIG_USB is enabled:

drivers/usb/gadget/udc/renesas_usb3.o: In function `renesas_usb3_probe':
renesas_usb3.c:(.text+0xa34): undefined reference to `usb_of_get_companion_dev'

To avoid the build error, we need two changes:

- usb_of_get_companion_dev must be stubbed out when CONFIG_USB is
  disabled, so it the udc driver can be built for a gadget-only
  mode kernel
- With CONFIG_USB=m, we must not attempt to have USB_RENESAS_USB3
  built-in, so we need a soft dependency on USB.

Fixes: 39facfa01c9f ("usb: gadget: udc: renesas_usb3: Add register of usb role switch")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>