phy: micrel: Fix build failure in ksz9031_config_init()
This fixes the following build failure seen in net.git#master on top of
Linux v4.4-rc8+:

drivers/net/phy/micrel.c: In function 'ksz9031_config_init':
drivers/net/phy/micrel.c:492:22: error: 'struct phy_device' has no member named 'dev'
  dev_walker = &phydev->dev;

Fixes: b4c19f71252e ("phy: micrel: Fix finding PHY properties in MAC node for KSZ9031.")
CC: Roosen Henri <Henri.Roosen@ginzinger.com>
CC: Andrew Lunn <andrew@lunn.ch>
CC: David Daney <david.daney@cavium.com>
CC: Florian Fainelli <f.fainelli@gmail.com>
CC: David S. Miller <davem@davemloft.net>
CC: "netdev@vger.kernel.org" <netdev@vger.kernel.org>
Signed-off-by: Sedat Dilek <sedat.dilek@gmail.com>