ia64/mm/tlb: Fix indentation in ia64_global_tlb_purge()
The script "checkpatch.pl" pointed the following information out.

ERROR: code indent should use tabs where possible
#40: FILE: arch/ia64/mm/tlb.c:271

Thus fix the affected source code places.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>