mm: Drop unnecessary include file
Commmit e9be930fa6b5 ("mm: fix vm-scalability regression in cgroup-aware
workingset code") adds '#include <linux/mm.h>' to
include/linux/memcontrol.h. This results in the following build error
when building hexagon images.

In file included from ./include/linux/memcontrol.h:32:0,
                 from ./include/linux/swap.h:8,
		 from ./arch/hexagon/include/asm/pgtable.h:27,
		 from mm/init-mm.c:9:
./include/linux/mm.h:322:2: error: unknown type name 'pmd_t'
./include/linux/mm.h:353:7: error: unknown type name 'pmd_t'
./include/linux/mm.h:414:30: error: unknown type name 'pmd_t'

The include file does not appear to be necessary, so just drop it.

Fixes: e9be930fa6b5 ("mm: fix vm-scalability regression in cgroup-aware workingset code")
Cc: Johannes Weiner <hannes@cmpxchg.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>