mm: Fix build on non-MMU systems
Non-MMU systems fail to build with

In file included from init/main.c:50:0:
include/linux/rmap.h:274:1: error:
	expected declaration specifiers or ‘...’ before ‘{’ token

Fixes: c3f568752340 ("mm: support madvise(MADV_FREE)")
Cc: Minchan Kim <minchan@kernel.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>