drm/amdgpu: use first uvd instance to avoid clang build error
Explicitly use the first uvd instance to avoid a build error when
using clang 6:
drivers/gpu/drm/amd/amdgpu/amdgpu_uvd.c:1148:52: error: expected ')'
                container_of(work, struct amdgpu_device, uvd.inst->idle_work.work);
                                                                 ^
drivers/gpu/drm/amd/amdgpu/amdgpu_uvd.c:1148:3: note: to match this '('
                container_of(work, struct amdgpu_device, uvd.inst->idle_work.work);
                ^
./include/linux/kernel.h:967:21: note: expanded from macro 'container_of'
        ((type *)(__mptr - offsetof(type, member))); })
                           ^
./include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
                                ^
./include/linux/compiler-gcc.h:170:20: note: expanded from macro
      '__compiler_offsetof'
        __builtin_offsetof(a, b)
                          ^
drivers/gpu/drm/amd/amdgpu/amdgpu_uvd.c:1147:24: error: initializing
      'struct amdgpu_device *' with an expression of incompatible type 'void'
        struct amdgpu_device *adev =
                              ^
2 errors generated.

Fixes: 10dd74eac4db ("drm/amdgpu/vg20:Restruct uvd.inst to support multiple instances")
Cc: James Zhu <James.Zhu@amd.com>
Signed-off-by: Stefan Agner <stefan@agner.ch>