spi: bcm-qspi: fix build error
While building m68k allmodconfig, the build was failing with the error:

drivers/spi/spi-bcm-qspi.c:1300:13:
error: 'bcm_qspi_suspend' undeclared here (not in a function)
  .suspend = bcm_qspi_suspend,

drivers/spi/spi-bcm-qspi.c:1301:13:
error: 'bcm_qspi_resume' undeclared here (not in a function)
  .resume  = bcm_qspi_resume,

bcm_qspi_suspend() and bcm_qspi_resume() are only defined when
CONFIG_PM_SLEEP is defined. Use the macro SET_SYSTEM_SLEEP_PM_OPS to
use it only when CONFIG_PM_SLEEP is defined.

Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>