phy: nsp-usb3: select PHYLIB
Building this driver without PHYLIB fails:

ERROR: "mdio_driver_unregister" [drivers/phy/phy-bcm-nsp-usb3.ko] undefined!
ERROR: "mdio_driver_register" [drivers/phy/phy-bcm-nsp-usb3.ko] undefined!
ERROR: "mdiobus_write" [drivers/phy/phy-bcm-nsp-usb3.ko] undefined!

Unfortunately selecting PHYLIB without NETDEVICES produces a warning:

warning: (NET_DSA && NETLOGIC_XLR_NET && PHY_NSP_USB3) selects PHYLIB which has unmet direct dependencies (NETDEVICES)

so I'm adding a dependency on netdevices here.

Fixes: d7bc1a7d41bf ("phy: Add USB3 PHY support for Broadcom NSP SoC")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>