mm: provide reference to READ_IMPLIES_EXEC
blackfin defconfig fails with the error:
mm/internal.h: In function 'is_stack_mapping':
arch/blackfin/include/asm/page.h:15:27: error: 'READ_IMPLIES_EXEC' undeclared

Commit 07dff8ae2bc5 has added is_stack_mapping in mm/internal.h but it
also needs personality.h.

Fixes: 07dff8ae2bc5 ("mm: warn about VmData over RLIMIT_DATA")
Cc: Konstantin Khlebnikov <koct9i@gmail.com>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>