cgroup: remove an unused variable
The newly introduced cgroup_show_path has an extraneous variable
that gcc warns about:

kernel/cgroup.c: In function 'cgroup_show_path':
kernel/cgroup.c:1634:15: error: unused variable 'ret' [-Werror=unused-variable]
  int len = 0, ret = 0;

This must have been left over from a previous version that was
changed before it got committed. I checked the function and
found that two other variables in the same function have an
extraneous initialization, presumably another artifact from
the same rework.

This patch removes the useless warning and the extra initializations.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>