mm-rmap-handle-anon_vma_prepare-common-case-inline-checkpatch-fixes
WARNING: function definition argument 'struct vm_area_struct *' should also have an identifier name
#45: FILE: include/linux/rmap.h:140:
+int  __anon_vma_prepare(struct vm_area_struct *);

ERROR: "foo * bar" should be "foo *bar"
#50: FILE: include/linux/rmap.h:145:
+static inline int anon_vma_prepare(struct vm_area_struct * vma)

total: 1 errors, 1 warnings, 118 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-rmap-handle-anon_vma_prepare-common-case-inline.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: "Kirill A. Shutemov" <kirill.shutemov@linux.intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>