x86/uapi: fix asm/signal.h userspace compilation error
Replace size_t to fix the following asm/signal.h userspace compilation
error:

/usr/include/asm/signal.h:126:2: error: unknown type name 'size_t'
  size_t ss_size;

size_t is replaced with __kernel_size_t in all cases except x32 where
unsigned int has to be used instead.

Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>