perf probe: Fix build failure for get_target_map()
Commit 801bc8193463 ("perf probe: Allow placing uprobes in
alternate namespaces.") is causing a build failure on powerpc:

  error: incompatible type for argument 2 of 'get_target_map'
  map = get_target_map(pev->target, pev->uprobes);
                                    ^~~

Fix it by changing parameters of get_target_map().

Fixes: 801bc8193463 ("perf probe: Allow placing uprobes in alternate namespaces.")
Signed-off-by: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>