memstick: r592: avoid gcc-6 warning
The r592 driver relies on behavior of the DMA mapping API that is
normally observed but not guaranteed by the API. Instead it uses
a runtime check to fail transfers if the API ever behaves
differently.

When CONFIG_NEED_SG_DMA_LENGTH is not set, one of the checks turns
into a comparison of a variable with itself, which gcc-6.0 now
warns about:

drivers/memstick/host/r592.c: In function 'r592_transfer_fifo_dma':
drivers/memstick/host/r592.c:302:31: error: self-comparison always evaluates to false [-Werror=tautological-compare]
    (sg_dma_len(&dev->req->sg) < dev->req->sg.length)) {
                               ^

The check itself is not a problem, so this patch just rephrases
the condition in a way that gcc does not consider an indication
of a mistake. We already know that dev->req->sg.length was initially
R592_LFIFO_SIZE, so we can compare it to that constant again.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>