amdgpu/dc: Add missing cast in dce_clock_set_min_clocks_state()
dce_clock_set_min_clocks_state() assigns (intentionally) a value of type
'enum dm_pp_clocks_state' to a variable of type 'enum dm_pp_power_level'
without an explicit cast. This causes clang to raise the following
warning:

drivers/gpu/drm/amd/amdgpu/../display/dc/dce/dce_clocks.c:308:4: error:
  implicit conversion from enumeration type 'enum dm_pp_clocks_state'
  to different enumeration type 'enum dm_pp_power_level' [-Werror,-Wenum-conversion]
    clocks_state };

Make the cast explicit.

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>