tools: perf: fix build error in uapi/linux/mman.h
All the other occurrence refer "uapi/asm-generic/*.h" directly instead
of "uapi/asm/*.h" in tools/include except mman.h. Without this patch,
the following build failure is seen.

 In file included from util/event.c:2:0:
 tools/include/uapi/linux/mman.h:4:27: fatal error: uapi/asm/mman.h: No such file or directory
 compilation terminated.

Fixes: f3539c12d819 ("tools include: Add uapi mman.h for each architecture")
Cc: Wang Nan <wangnan0@huawei.com>
Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Ingo Molnar <mingo@redhat.com>
Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>