Input: colibri-vf50-ts: fix implicit declaration
The build of m32r allmodconfig fails with the error:
drivers/input/touchscreen/colibri-vf50-ts.c:302:10: error: implicit
	declaration of function 'of_property_read_u32'

of_property_read_u32() is defined in linux/of.h which was not included.

Fixes: 1261d013daea ("Input: Allow compile test of Goodix and Colibri VF50 if !GPIOLIB")
Cc: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>