h8300: binfmt_flat: Fix build error
arch/h8300/include/asm/flat.h: In function ‘flat_get_addr_from_rp’:
arch/h8300/include/asm/flat.h:28:3: error: expected ‘)’ before ‘val’

Fixes: 468138d785106 ("binfmt_flat: flat_{get,put}_addr_from_rp() ...")
Cc: Al Viro <viro@zeniv.linux.org.uk>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>