cfq-iosched: Fix warning about unused dummy functions
Only define dummies for cfqg_stats_set_start_group_wait_time()
and cfqg_stats_end_empty_time() when CONFIG_CFQ_GROUP_IOSCHED=y. This
fixes the following warnings when building with clang:

    block/cfq-iosched.c:589:20: error: unused function
        'cfqg_stats_set_start_group_wait_time' [-Werror,-Wunused-function]

    block/cfq-iosched.c:590:20: error: unused function
        'cfqg_stats_end_empty_time' [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>