uapi: fix linux/usb/audio.h userspace compilation error
Replace NULL with 0 in uac_mixer_unit_bmControls() to fix the following
linux/usb/audio.h userspace compilation error:

/usr/include/linux/usb/audio.h: In function 'uac_mixer_unit_bmControls':
/usr/include/linux/usb/audio.h:304:10: error: 'NULL' undeclared (first use in this function)
   return NULL;

Fixes: 6cfd839ae78e ("ALSA: usb-audio: UAC3. Add support for mixer unit.")
Cc: <stable@vger.kernel.org> # v4.18
Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>