iio: adc: Fix at91-sama5d2_adc dependencies
Not all archs have io memory.

Fixes the following build error:
ERROR: "devm_ioremap_resource" [drivers/iio/adc/at91-sama5d2_adc.ko] undefined!

Cc: Jonathan Cameron <jic23@kernel.org>
Cc: Hartmut Knaack <knaack.h@gmx.de>
Cc: Lars-Peter Clausen <lars@metafoo.de>
Cc: Peter Meerwald <pmeerw@pmeerw.net>
Cc: Ludovic Desroches <ludovic.desroches@atmel.com>
Fixes: b9cd7a25 ("MAINTAINERS: add entry for Atmel SAMA5D2 ADC driver")
Signed-off-by: Richard Weinberger <richard@nod.at>