of: Add stub for of_get_next_parent()
Fixes a compiler error:

drivers/phy/phy-core.c: In function ‘__of_phy_provider_register’:
drivers/phy/phy-core.c:848:13: error: implicit declaration of function
‘of_get_next_parent’ [-Werror=implicit-function-declaration]
    parent = of_get_next_parent(parent);
                 ^

Fixes: 2f7600bc981c ("phy: core: Allow children node to be overridden")
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>