arm: Select GPIO_GENERIC_PLATFORM for CRAGG_6410
Since commit 0f4630f3720e ("gpio: generic: factor into gpio_chip struct"),
all users of struct bgpio_pdata depend on GPIO_GENERIC.

This results in the following build error.

arch/arm/mach-s3c64xx/mach-crag6410.c:270:3: warning:
	excess elements in struct initializer
arch/arm/mach-s3c64xx/mach-crag6410.c:270:3: warning:
	(near initialization for '(anonymous)')
arch/arm/mach-s3c64xx/mach-crag6410.c:271:2: error:
	invalid use of undefined type 'struct bgpio_pdata'

Fixes: 0f4630f3720e ("gpio: generic: factor into gpio_chip struct")
Cc: Linus Walleij <linus.walleij@linaro.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>