pstore: fix warning about conditional locking
gcc cannot prove that "prz->flags" remains constant over the
function, so it warns that we might restore flags that have
never been saved:

fs/pstore/ram_core.c: In function ‘buffer_size_add’:
include/linux/spinlock.h:246:3: error: ‘flags’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

This reworks the code to avoid the spinlock entirely, by actually
using the atomic_t for atomic updates. The resulting code is
more efficient and easier to understand, and it avoids the
local variable that the compiler did not track correctly.

Fixes: 95937ddce59a ("pstore: Allow prz to control need for locking")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>