Firmware: broadcom sprom: clarifiy SSB dependency
The broadcom firmware drvier calls into the ssb SPROM code if that
is enabled, but it fails if the SSB code is in a loadable module
because the bcm47xx firmware is always built-in:

drivers/firmware/built-in.o: In function `bcm47xx_sprom_register_fallbacks':
bcm47xx_sprom.c:(.text+0x11c4): undefined reference to `ssb_arch_register_fallback_sprom'

This adds a Kconfig dependency to ensure that we cannot turn on the
generic sprom support if the ssb sprom is in a module.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>