Fix "ERROR: code indent should use tabs where possible"
ERROR: code indent should use tabs where possible
+^I^I         "Need to wait for TPM to finish\n");$

Signed-off-by: SZ Lin <sz.lin@moxa.com>