scsi: libfc: drop an incorrect assertion
gcc points out one case in which the added lockdep_assert_held()
is wrong:

In file included from include/linux/spinlock_types.h:18,
                 from include/linux/spinlock.h:82,
                 from drivers/scsi/libfc/fc_rport.c:61:
drivers/scsi/libfc/fc_rport.c: In function 'fc_rport_recv_plogi_req':
include/linux/lockdep.h:347:45: error: 'rdata' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 #define lockdep_is_held(lock)  lock_is_held(&(lock)->dep_map)
                                             ^
drivers/scsi/libfc/fc_rport.c:1832:24: note: 'rdata' was declared here
  struct fc_rport_priv *rdata;

The pointer to the lock is not initialized here, so besides the
compile-time warning, this will likely lead to an immediate
crash when dereferencing that pointer.

Fixes: ee35624e1e4e ("scsi: libfc: Add lockdep annotations")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>