net/macb: add proper header file
mips allmodconfig build fails with the error:

drivers/net/ethernet/cadence/macb.c: In function 'macb_probe':
drivers/net/ethernet/cadence/macb.c:2908:2: error: implicit declaration of function 'devm_gpiod_get_optional' [-Werror=implicit-function-declaration]
  bp->reset_gpio = devm_gpiod_get_optional(&bp->pdev->dev, "phy-reset",
  ^
drivers/net/ethernet/cadence/macb.c:2909:8: error: 'GPIOD_OUT_HIGH' undeclared (first use in this function)
        GPIOD_OUT_HIGH);
        ^
drivers/net/ethernet/cadence/macb.c:2909:8: note: each undeclared identifier is reported only once for each function it appears in
drivers/net/ethernet/cadence/macb.c: In function 'macb_remove':
drivers/net/ethernet/cadence/macb.c:2979:3: error: implicit declaration of function 'gpiod_set_value' [-Werror=implicit-function-declaration]
   gpiod_set_value(bp->reset_gpio, 0);
   ^

Add the proper header file to resolve it.

Fixes: 5833e0526820 ("net/macb: add support for resetting PHY using GPIO")
Cc: Gregory CLEMENT <gregory.clement@free-electrons.com>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>