reiserfs: avoid uninitialized variable use
I got this warning on an ARM64 allmodconfig build with gcc-5.3:

fs/reiserfs/ibalance.c: In function 'balance_internal':
fs/reiserfs/ibalance.c:1158:3: error: 'new_insert_key' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   memcpy(new_insert_key_addr, &new_insert_key, KEY_SIZE);

The warning is correct, in fact both new_insert_key and new_insert_ptr
are only updated inside of an if() block, but used at the end of
the function.

Looking at how the balance_internal() function gets called, it
is clear that this is harmless because the caller never uses the
updated arrays, they are initialized from balance_leaf_new_nodes()
and then passed into balance_internal().

This has not changed at all since the start of the git history,
but apparently the warning has only recently appeared.

This modifies the function to only update the two argument variables
when the new_insert_key and new_insert_ptr have been updated, to
get rid of the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>