serial: 8250_dw: 8250_dw need to depend on COMMON_CLK
This patch fix the following build error on M68K:
drivers/tty/serial/8250/8250_dw.o: In function `dw8250_set_termios':
8250_dw.c:(.text+0x50c): undefined reference to `clk_round_rate'
8250_dw.c:(.text+0x594): undefined reference to `clk_set_rate'

So 8250_dw need to depend on COMMON_CLK.

Signed-off-by: Corentin Labbe <clabbe@baylibre.com>