ARC: [arcompact] fix handling of unaligned access in delay slot
Commit 9aed02feae5 ("ARC: [arcompact] handle unaligned access delay slot
corner case") was meant to fix one corner-case of unaligned access
fixup. But for some reason real implementation has an important spello
which prevents kernel to be built with enabled
CONFIG_ARC_EMUL_UNALIGNED:
--------------------------------->8--------------------------------
arch/arc/kernel/unaligned.c: In function 'misaligned_fixup':
arch/arc/kernel/unaligned.c:246:25: error: expected ';' before '~ token
   regs->ret = regs->bta ~1U;
                         ^
--------------------------------->8--------------------------------

What needs to be done - LSB bit of regs->bta has to be cleared and now
we do exactly this with "& ~1U".

While at it fix another spello in comments.

Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
Reported-by: John Crispin <john@phrozen.org>
Cc: Felix Fietkau <nbd@nbd.name>
Cc: Vineet Gupta <vgupta@synopsys.com>
Cc: Igor Guryanov <guryanov@synopsys.com>