pinctrl: sprd: add missing Kconfig dependency
The chip-specific driver fails to build when the common
part is not enabled first:

drivers/pinctrl/sprd/pinctrl-sprd-sc9860.o:(.data+0x8): undefined reference to `sprd_pinctrl_remove'
drivers/pinctrl/sprd/pinctrl-sprd-sc9860.o:(.data+0x10): undefined reference to `sprd_pinctrl_shutdown'

This adds a Kconfig dependency to ensure this is always
the case.

Fixes: 41d32cfce1ae ("pinctrl: sprd: Add Spreadtrum pin control driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>