origin
GIT ef0e1ea8856bed6ff8394d3dfe77f2cab487ecea

commit c57653dc94d0db7bf63067433ceaa97bdcd0a312
Author: Vineet Gupta <vgupta@synopsys.com>
Date:   Fri Aug 19 13:59:02 2016 -0700

    ARC: export __udivdi3 for modules
    
    Some module using div_u64() was failing to link because the libgcc 64-bit
    divide assist routine was not being exported for modules
    
    Reported-by: avinashp@quantenna.com
    Cc: stable@vger.kernel.org
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

commit 1c3c909303924d30145601f47b6c058fdd2cbc2e
Author: Vineet Gupta <vgupta@synopsys.com>
Date:   Tue Aug 16 18:27:07 2016 -0700

    ARC: mm: fix build breakage with STRICT_MM_TYPECHECKS
    
    |  CC      mm/memory.o
    | In file included from ../mm/memory.c:53:0:
    | ../include/linux/pfn_t.h: In function ‘pfn_t_pte’:
    | ../include/linux/pfn_t.h:78:2: error: conversion to non-scalar type requested
    |  return pfn_pte(pfn_t_to_pfn(pfn), pgprot);
    
    With STRICT_MM_TYPECHECKS pte_t is a struct and the offending code
    forces a cast which ends up shifting a struct and hence the gcc warning.
    
    Note that in recent past some of the arches (aarch64, s390) made
    STRICT_MM_TYPECHECKS default, but we don't for ARC as this leads to slightly
    worse generated code, given ARC ABI definition of returning structs
    (which pte_t would become)
    
    Quoting from ARC ABI...
    
      "Results of type struct are returned in a caller-supplied temporary
      variable whose address is passed in r0.
      For such functions, the arguments are shifted so that they are
      passed in r1 and up."
    
    So
     - struct to be returned would be allocated on stack requiring extra
       code at call sites
     - callee updates stack memory to facilitate the return (vs. simple
       MOV into return reg r0)
    
    Hence STRICT_MM_TYPECHECKS is not enabled by default for ARC
    
    Cc: <stable@vger.kernel.org>   #4.4+
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

commit d77976c414ed7f521b9c79b2a9dde0147a3cf754
Author: Vineet Gupta <vgupta@synopsys.com>
Date:   Wed Aug 17 17:34:46 2016 -0700

    ARC: export kmap
    
    |  MODPOST 7 modules
    | ERROR: "kmap" [fs/ext2/ext2.ko] undefined!
    | ../scripts/Makefile.modpost:91: recipe for target '__modpost' failed
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

commit 840c054fd0efb048df6fceb0c46385ec5b66dfe6
Author: Vineet Gupta <vgupta@synopsys.com>
Date:   Wed Aug 10 14:10:57 2016 -0700

    ARC: Support syscall ABI v4
    
    The syscall ABI includes the gcc functional calling ABI since a syscall
    implies userland caller and kernel callee.
    
    The current gcc ABI (v3) for ARCv2 ISA required 64-bit data be passed in
    even-odd register pairs, (potentially punching reg holes when passing such
    values as args). This was partly driven by the fact that the double-word
    LDD/STD instructions in ARCv2 expect the register alignment and thus gcc
    forcing this avoids extra MOV at the cost of a few unused register (which we
    have plenty anyways).
    
    This however was rejected as part of upstreaming gcc port to HS. So the new
    ABI v4 doesn't enforce the even-odd reg restriction.
    
    Do note that for ARCompact ISA builds v3 and v4 are practically the same in
    terms of gcc code generation.
    
    In terms of change management, we infer the new ABI if gcc 6.x onwards
    is used for building the kernel.
    
    This also needs a stable backport to enable older kernels to work with
    new tools/user-space
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

commit 86147e3cfa5e118b61e78f4f0bf29e920dcbd477
Author: Liav Rehana <liavr@mellanox.com>
Date:   Tue Aug 16 10:55:35 2016 +0300

    ARC: use correct offset in pt_regs for saving/restoring user mode r25
    
    User mode callee regs are explicitly collected before signal delivery or
    breakpoint trap. r25 is special for kernel as it serves as task pointer,
    so user mode value is clobbered very early. It is saved in pt_regs where
    generally only scratch (aka caller saved) regs are saved.
    
    The code to access the corresponding pt_regs location had a subtle bug as
    it was using load/store with scaling of offset, whereas the offset was already
    byte wise correct. So fix this by replacing LD.AS with a standard LD
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Liav Rehana <liavr@mellanox.com>
    Reviewed-by: Alexey Brodkin <abrodkin@synopsys.com>
    [vgupta: rewrote title and commit log]
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

commit 048c28c91e56781082bc17d181e460b81e7e8bcb
Author: Linus Walleij <linus.walleij@linaro.org>
Date:   Tue Aug 16 12:07:31 2016 +0200

    gpio: make any OF dependent driver depend on OF_GPIO
    
    The drivers that depend on OF but not OF_GPIO are wreaking havoc
    with the autobuilders for archs that have all requirements for
    OF but not for OF_GPIO, particularly the UM (Usermode) arch does
    not have iomem (NO_IOMEM) which result in configuring GPIOLIB but
    without OF_GPIO which is wrong if the driver is using the .of_node
    of the gpiochip, which only appears with OF_GPIO.
    
    After a brief look at the drivers just depending on OF it seems
    most if not all of them actually require stuff from gpiolib-of so
    the dependency is wrong in the first place.
    
    This simply patches the Kconfig so that all GPIO drivers using OF
    depend on OF_GPIO rather than just OF.
    
    Cc: Rabin Vincent <rabin@rab.in>
    Cc: Pramod Gurav <pramod.gurav@smartplayin.com>
    Cc: Andreas Larsson <andreas@gaisler.com>
    Cc: Gregory CLEMENT <gregory.clement@free-electrons.com>
    Cc: Thierry Reding <treding@nvidia.com>
    Cc: Laxman Dewangan <ldewangan@nvidia.com>
    Cc: Alexandre Courbot <acourbot@nvidia.com>
    Cc: Geert Uytterhoeven <geert+renesas@glider.be>
    Cc: Phil Reid <preid@electromag.com.au>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 2527ecc9195e9c66252af24c4689e8a67cd4ccb9
Author: Linus Walleij <linus.walleij@linaro.org>
Date:   Tue Aug 16 09:58:25 2016 +0200

    gpio: Fix OF build problem on UM
    
    The UserMode (UM) Linux build was failing in gpiolib-of as it requires
    ioremap()/iounmap() to exist, which is absent from UM. The non-existence
    of IO memory is negatively defined as CONFIG_NO_IOMEM which means we
    need to depend on HAS_IOMEM.
    
    Cc: stable@vger.kernel.org
    Cc: Geert Uytterhoeven <geert@linux-m68k.org>
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 45c3b08a117e2232fc8d7b9e849ead36386f4f96
Author: Vineet Gupta <vgupta@synopsys.com>
Date:   Mon Jun 13 16:38:27 2016 +0200

    ARC: Elide redundant setup of DMA callbacks
    
    For resources shared by all cores such as SLC and IOC, only the master
    core needs to do any setups / enabling / disabling etc.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

commit 18b43e89d295cc65151c505c643c98fb2c320e59
Author: Daniel Mentz <danielmentz@google.com>
Date:   Thu Aug 4 17:56:53 2016 -0700

    ARC: Call trace_hardirqs_on() before enabling irqs
    
    trace_hardirqs_on_caller() in lockdep.c expects to be called before, not
    after interrupts are actually enabled.
    
    The following comment in kernel/locking/lockdep.c substantiates this
    claim:
    
    "
    /*
     * We're enabling irqs and according to our state above irqs weren't
     * already enabled, yet we find the hardware thinks they are in fact
     * enabled.. someone messed up their IRQ state tracing.
     */
    "
    
    An example can be found in include/linux/irqflags.h:
    
    	do { trace_hardirqs_on(); raw_local_irq_enable(); } while (0)
    
    Without this change, we hit the following DEBUG_LOCKS_WARN_ON.
    
    [    7.760000] ------------[ cut here ]------------
    [    7.760000] WARNING: CPU: 0 PID: 1 at kernel/locking/lockdep.c:2711 resume_user_mode_begin+0x48/0xf0
    [    7.770000] DEBUG_LOCKS_WARN_ON(!irqs_disabled())
    [    7.780000] Modules linked in:
    [    7.780000] CPU: 0 PID: 1 Comm: init Not tainted 4.7.0-00003-gc668bb9-dirty #366
    [    7.790000]
    [    7.790000] Stack Trace:
    [    7.790000]   arc_unwind_core.constprop.1+0xa4/0x118
    [    7.800000]   warn_slowpath_fmt+0x72/0x158
    [    7.800000]   resume_user_mode_begin+0x48/0xf0
    [    7.810000] ---[ end trace 6f6a7a8fae20d2f0 ]---
    
    Signed-off-by: Daniel Mentz <danielmentz@google.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

commit 6f4deb18a505523eb7925d646574a95f9e982ff7
Author: Christophe Leroy <christophe.leroy@c-s.fr>
Date:   Mon Aug 8 15:58:56 2016 +0200

    gpio: max730x: set gpiochip data pointer before using it
    
    gpiochip_add_data() has to be called before calling
    max7301_direction_input()
    
    [    4.389883] Unable to handle kernel paging request for data at address 0x00000018
    [    4.397282] Faulting instruction address: 0xc01a8cbc
    [    4.402023] Oops: Kernel access of bad area, sig: 11 [#1]
    [    4.407331] PREEMPT CMPC885
    [    4.410131] CPU: 0 PID: 6 Comm: kworker/u2:0 Not tainted 4.5.0-gacdfdee #39
    [    4.418592] Workqueue: deferwq deferred_probe_work_func
    [    4.423711] task: c60798b0 ti: c608a000 task.ti: c608a000
    [    4.429038] NIP: c01a8cbc LR: c01a8e24 CTR: c01ff028
    [    4.433953] REGS: c608bad0 TRAP: 0300   Not tainted  (4.5.0-s3k-dev-gacdfdee-svn-dirty)
    [    4.441847] MSR: 00009032 <EE,ME,IR,DR,RI>  CR: 33039553  XER: a000f940
    [    4.448395] DAR: 00000018 DSISR: c0000000
    GPR00: c01a8e24 c608bb80 c60798b0 c60d6f6c 00000004 00000002 07de2900 00700000
    GPR08: 00000000 00000000 c608a000 00001032 35039553 00000000 c002f37c c6010b64
    GPR16: c6010a48 c6010a14 c6010a00 00000000 c0450000 c0453568 c0453438 c050db14
    GPR24: c62662bc 00000009 ffffffaa c60d6f5d 00000001 00000000 00000000 00000000
    [    4.480371] NIP [c01a8cbc] max7301_direction_input+0x20/0x9c
    [    4.485951] LR [c01a8e24] __max730x_probe+0xec/0x138
    [    4.490812] Call Trace:
    [    4.493268] [c608bba0] [c01a8e24] __max730x_probe+0xec/0x138
    [    4.498878] [c608bbc0] [c01cc368] driver_probe_device+0x190/0x38c
    [    4.504895] [c608bbf0] [c01ca918] bus_for_each_drv+0x58/0xb4
    [    4.510489] [c608bc20] [c01cc04c] __device_attach+0x8c/0x110
    [    4.516082] [c608bc50] [c01cab80] bus_probe_device+0x34/0xb8
    [    4.521673] [c608bc70] [c01c96c8] device_add+0x3c0/0x598
    [    4.526925] [c608bcb0] [c0200f90] spi_add_device+0x114/0x160
    [    4.532512] [c608bcd0] [c02018d0] spi_register_master+0x6e0/0x7c8
    [    4.538537] [c608bd20] [c02019fc] devm_spi_register_master+0x44/0x8c
    [    4.544824] [c608bd40] [c0203854] of_fsl_spi_probe+0x458/0x57c
    [    4.550587] [c608bda0] [c01cd828] platform_drv_probe+0x30/0x74
    [    4.556366] [c608bdb0] [c01cc368] driver_probe_device+0x190/0x38c
    [    4.562383] [c608bde0] [c01ca918] bus_for_each_drv+0x58/0xb4
    [    4.567977] [c608be10] [c01cc04c] __device_attach+0x8c/0x110
    [    4.573572] [c608be40] [c01cab80] bus_probe_device+0x34/0xb8
    [    4.579170] [c608be60] [c01cb9b4] deferred_probe_work_func+0xa4/0xc4
    [    4.585438] [c608be80] [c0029c04] process_one_work+0x22c/0x414
    [    4.591201] [c608bea0] [c002a100] worker_thread+0x314/0x5c0
    [    4.596722] [c608bef0] [c002f444] kthread+0xc8/0xcc
    [    4.601538] [c608bf40] [c000af84] ret_from_kernel_thread+0x5c/0x64
    [    4.607596] Instruction dump:
    [    4.610530] 7c0803a6 bba10014 38210020 4e800020 7c0802a6 9421ffe0 38840004 bf810010
    [    4.618188] 90010024 549cf0be 83c30010 549d0f7c <813e0018> 7fc3f378 7d3f2430 57ff07fe
    [    4.626041] ---[ end trace 303adb021dd4caf2 ]---
    
    Cc: stable@vger.kernel.org
    fixes: 5e45e01916197 ("gpio: max730x: use gpiochip data pointer")
    Signed-off-by: Christophe Leroy <christophe.leroy@c-s.fr>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 925baf394bb0e65d85330afe467393f66f910353
Author: Baruch Siach <baruch@tkos.co.il>
Date:   Wed Jul 27 08:41:49 2016 +0300

    tools/gpio: fix gpio-event-mon header comment
    
    Fixes: 97f69747d8b1 ('tools/gpio: add the gpio-event-mon tool')
    Signed-off-by: Baruch Siach <baruch@tkos.co.il>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>