ALSA: pcm: Export soc_dpcm_runtime_update
Some codecs may need to use this from loadable modules. Without
this patch compilation for this kind of codec will fail with the
following error:

ERROR: "soc_dpcm_runtime_update" [sound/soc/codecs/snd-soc-cpcap.ko]
undefined!

Signed-off-by: Tony Lindgren <tony@atomide.com>
Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.co.uk>