xfs: hide unused variable
The newly added xfs_finish_page_writeback() function causes
a harmless gcc warning when debugging is disabled:

fs/xfs/xfs_aops.c: In function 'xfs_finish_page_writeback':
fs/xfs/xfs_aops.c:97:16: error: unused variable 'blockmask' [-Werror=unused-variable]
  unsigned int  blockmask = (1 << inode->i_blkbits) - 1;
                ^~~~~~~~~

This adds an #ifdef around the variable declaration to hide
it whenever the ASSERT macro is defined as a stub, following
the same style as used elsewhere in xfs.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 37992c18bba3 ("xfs: don't release bios on completion immediately")