irqchip/gicv3-its: use IORT only if IOMMU support is enabled
When the IOMMU subsystem is disabled, we cannot build ARM64 kernels with ACPI:

drivers/acpi/arm64/iort.c: In function 'iort_iommu_xlate':
drivers/acpi/arm64/iort.c:647:22: error: 'struct iommu_fwspec' has no member named 'ops'

This adds a Kconfig dependency to only enable ACPI_IORT when it acutally
builds, along with addititonal dummy helper functions to make its
users build without IOMMU/IORT.

Fixes: 3f010cf19732 ("irqchip/gicv3-its: Probe ITS in the ACPI way")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>