ALSA: ad1889: Use common error handling code in snd_ad1889_create()
* Adjust jump targets so that a bit of exception handling can be better
  reused at the end of this function.

  This issue was detected by using the Coccinelle software.

* The script "checkpatch.pl" pointed information out like the following.

  ERROR: do not use assignment in if condition

  Thus fix five affected source code places.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>