pci: export devm_request_pci_bus_resources to modules
Host drivers can be loadable modules, so we might run into this
build error with the new interface:

ERROR: devm_request_pci_bus_resources [drivers/pci/host/pcie-iproc.ko] undefined!

This adds an EXPORT_SYMBOL_GPL() line.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>