clk: renesas: build clk-rcar-gen2.o for R8A7792
The newly added support for R8A7792 causes build failures
because we try to call rcar_gen2_clocks_init but that is not
built into the kernel:

arch/arm/mach-shmobile/built-in.o: In function `rcar_gen2_timer_init':
:(.init.text+0x3b0): undefined reference to `rcar_gen2_clocks_init'

This changes the clk Makefile to match the other platforms, though
I guess it would be better to find another way to do this, e.g.
by not requiring the external function call by relying on
CLK_OF_DECLARE(), or by making the ARCH_RCAR_GEN2 also control
the compilation of the clk driver.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 3ebee0adbfe7 ("ARM: shmobile: r8a7792: basic SoC support")