Fix misleading indentation issues in perf
perf doesn't build with gcc-6 because of several misleading-indentation
warnings, e.g.:

arch/x86/tests/intel-cqm.c: In function ‘spawn’:
arch/x86/tests/intel-cqm.c:21:3: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]
   sleep(5);
   ^~~~~

arch/x86/tests/intel-cqm.c:20:2: note: ...this ‘while’ clause, but it is not
  while(1);
  ^~~~~

Signed-off-by: Markus Trippelsdorf <markus@trippelsdorf.de>