hexagon: Fix compile error
Fix:

arch/hexagon/kernel/dma.c: At top level:
arch/hexagon/kernel/dma.c:209:40: error: expected '}' before ';' token

Cc: Christoph Hellwig <hch@lst.de>
Fixes: 8715a7227c30b ("hexagon: switch to use ->mapping_error for ...")
Signed-off-by: Guenter Roeck <linux@roeck-us.net>