libbpf: Show supported ELF section names on when failed to guess a prog/attach type
We need to let users check their wrong ELF section name
with proper ELF section names when failed to get a prog/attach type from it.
Because users can't realize libbpf guess prog/attach types from
given ELF section names.
For example, when a 'cgroup' section name of a BPF program is used,

Before:

    $ bpftool prog load bpf-prog.o /sys/fs/bpf/prog1
    Error: failed to guess program type based on ELF section name cgroup

After:

    libbpf: failed to guess program type based on ELF section name 'cgroup'
    libbpf: supported section(type) names are: socket kprobe/ kretprobe/ classifier action tracepoint/ raw_tracepoint/ xdp perf_event lwt_in lwt_out lwt_xmit lwt_seg6local cgroup_skb/ingress cgroup_skb/egress cgroup/skb cgroup/sock cgroup/post_bind4 cgroup/post_bind6 cgroup/dev sockops sk_skb/stream_parser sk_skb/stream_verdict sk_skb sk_msg lirc_mode2 flow_dissector cgroup/bind4 cgroup/bind6 cgroup/connect4 cgroup/connect6 cgroup/sendmsg4 cgroup/sendmsg6

In addtion, add pr_out printing without the "libbpf: " prefix.

Cc: Jakub Kicinski <jakub.kicinski@netronome.com>
Cc: Quentin Monnet <quentin.monnet@netronome.com>
Cc: Andrey Ignatov <rdna@fb.com>
Signed-off-by: Taeung Song <treeze.taeung@gmail.com>