cpufreq: intel_pstate: fix intel_pstate_exit_perf_limits prototype
The addition of the generic governor support marked the
intel_pstate_exit_perf_limits as inline, which fixed a warning,
but it introduced another warning:

drivers/cpufreq/intel_pstate.c: In function ‘intel_pstate_exit_perf_limits’:
drivers/cpufreq/intel_pstate.c:483:1: error: no return statement in function returning non-void [-Werror=return-type]

This changes it back to a 'void' return type, and changes the
corresponding intel_pstate_init_acpi_perf_limits() function to
be inline as well for consistency.

Fixes: 001c76f05b01 ("cpufreq: intel_pstate: Generic governors support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>