ALSA: x86: hdmi: fix build with CONFIG_PM=n
The runtime_status field is defined conditionally and must not be accessed outside
of #ifdef CONFIG_PM:

sound/x86/intel_hdmi_audio_if.c: In function 'hdmi_audio_suspend':
sound/x86/intel_hdmi_audio_if.c:112:30: error: 'struct dev_pm_info' has no member named 'runtime_status'
  if (intelhaddata->dev->power.runtime_status != RPM_SUSPENDED) {

pm_runtime_status_suspended() does what we need here.

Fixes: 5dab11d89777 ("ALSA: x86: hdmi: Add audio support for BYT and CHT")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>