drm/etnaviv: add THERMAL dependency
The etnaviv driver causes a link failure if it is built-in but THERMAL
is built as a module:

drivers/gpu/drm/etnaviv/etnaviv_gpu.o: In function `etnaviv_gpu_bind':
etnaviv_gpu.c:(.text+0x4c4): undefined reference to `thermal_of_cooling_device_register'
etnaviv_gpu.c:(.text+0x600): undefined reference to `thermal_cooling_device_unregister'
drivers/gpu/drm/etnaviv/etnaviv_gpu.o: In function `etnaviv_gpu_unbind':
etnaviv_gpu.c:(.text+0x2aac): undefined reference to `thermal_cooling_device_unregister'

Add a Kconfig dependency on THERMAL to avoid this, but allow building
with THERMAL disabled altogether. In that case, IS_ENABLED checks in the
code will disable the cooling device registration.

Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>