elf_fdpic: fix unused variable warning
The elf_fdpic code shows a harmless warning when built with MMU
enabled, I ran into this now that the configuration is possible
on ARM randconfig builds:

fs/binfmt_elf_fdpic.c: In function 'elf_fdpic_dump_segments':
fs/binfmt_elf_fdpic.c:1501:17: error: unused variable 'addr' [-Werror=unused-variable]

This adds another #ifdef around the variable declaration to shut
up the warning.

Fixes: 382e67aec6a7 ("ARM: enable elf_fdpic on systems with an MMU")
Fixes: e6c1baa9b562 ("convert the rest of binfmt_elf_fdpic to dump_emit()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>