dm block manager: use do/while(0) for empty macros
make W=1 reports a new warning for the dm-block-manager:

drivers/md/persistent-data/dm-block-manager.c: In function ‘dm_bm_unlock’:
drivers/md/persistent-data/dm-block-manager.c:598:3: error: suggest braces around empty body in an ‘else’ statement [-Werror=empty-body]

This is completely harmless, but generally speaking it's a good idea to
address this warning as it can often detect nasty bugs, and replacing
empty macros with "do { } while (0)" is generally considered good style
to make code more robust anyway.

Fixes: f94bdb2e26b6 ("dm block manager: make block locking optional")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>