cpufreq: intel_pstate: fix intel_pstate_use_acpi_profile helper
The newly added function uses two different prototypes depending
on configuration, and one of them does not match the caller:

drivers/cpufreq/intel_pstate.c: In function ‘copy_cpu_funcs’:
drivers/cpufreq/intel_pstate.c:1798:2: error: too few arguments to function ‘intel_pstate_use_acpi_profile’

This changes it to look like the other one.

Fixes: 3bea6a285476 ("cpufreq: intel_pstate: Use cpu load based algorithm for mobile class devices")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>