of: remove extraneous 'const' in typedef
One change that was meant to address a sparse warning turned out
to cause hundreds of new gcc-7 warnings:

include/linux/of_irq.h:11:13: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]

After reverting the change, the gcc warnings are gone again, and I
can't reproduce the sparse warnings either.

Fixes: 17a70355ea57 ("of: fix sparse warnings in fdt, irq, reserved mem, and resolver code")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>