pci: Add dummy for pci_acs_enabled() if CONFIG_PCI=n to fix iommmu build
If CONFIG_PCI=n, and gcc (e.g. 4.1.2) decides not to inline
get_pci_function_alias_group(), the build fails with:

    drivers/iommu/iommu.o: In function `get_pci_function_alias_group':
    iommu.c:(.text+0xfdc): undefined reference to `pci_acs_enabled'

Due to the various dummies for PCI calls in the CONFIG_PCI=n case,
pci_acs_enabled() isn't actually ever called, but not all versions of
gcc are smart enough to realize that.

While explicitly marking get_pci_function_alias_group() inline would fix
the build, this would inflate the code for the CONFIG_PCI=y case, as
get_pci_function_alias_group() is a not-so-small function called from
two places.

Hence fix the issue by introducing a dummy for pci_acs_enabled()
instead.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>