ASoC: AMD: add missing include
The newly added AMD acp driver is missing an include for linux/io.h
and fails to build on ARM:

sound/soc/amd/acp-pcm-dma.c: In function 'acp_reg_read':
sound/soc/amd/acp-pcm-dma.c:83:9: error: implicit declaration of function 'readl' [-Werror=implicit-function-declaration]

This adds the missing line.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>