ASoC: qdsp6: Add depends on OF
of_platform_device_destroy is only defined when building
with CONFIG_OF=y. Add a depends on OF.

sound/soc/qcom/qdsp6/q6afe.o: In function `q6afe_remove':
q6afe.c:(.text+0x363): undefined reference to `of_platform_device_destroy'
sound/soc/qcom/qdsp6/q6adm.o: In function `q6adm_remove':
q6adm.c:(.text+0x216): undefined reference to `of_platform_device_destroy'
sound/soc/qcom/qdsp6/q6asm.o: In function `q6asm_remove':
q6asm.c:(.text+0x723): undefined reference to `of_platform_device_destroy'

Signed-off-by: Niklas Cassel <niklas.cassel@linaro.org>