PCI: Change pci_host_common_probe visibility
pci_host_common_probe is defined when CONFIG_PCI_HOST_COMMON=y
therefore the function declaration should match that.

drivers/pci/host/pcie-tango.c:300:9: error:
	implicit declaration of function 'pci_host_common_probe'

Signed-off-by: Marc Gonzalez <marc_gonzalez@sigmadesigns.com>