netfilter: fix build failure with CONNTRACK=n NF_DEFRAG=y
conntrack depends on defrag support, but not vice versa, so we cannot
place defrag_ipv4/6 into netns->ct:

net/ipv4/netfilter/nf_defrag_ipv4.c:110:9: error: 'struct net' has no member named 'ct'

Move it into net->nf.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Florian Westphal <fw@strlen.de>