serial: SERIAL_ATMEL should depend on HAS_DMA
If NO_DMA=y:

    drivers/built-in.o: In function `atmel_release_rx_dma':
    atmel_serial.c:(.text+0x2502e): undefined reference to `dma_unmap_sg'
    drivers/built-in.o: In function `atmel_release_tx_dma':
    atmel_serial.c:(.text+0x25080): undefined reference to `dma_unmap_sg'
    drivers/built-in.o: In function `atmel_tx_dma':
    atmel_serial.c:(.text+0x2517a): undefined reference to `dma_sync_sg_for_cpu'
    drivers/built-in.o: In function `atmel_release_tx_pdc':
    atmel_serial.c:(.text+0x252e6): undefined reference to `dma_unmap_single'
    drivers/built-in.o: In function `atmel_prepare_tx_pdc':
    atmel_serial.c:(.text+0x2531a): undefined reference to `dma_map_single'
    drivers/built-in.o: In function `atmel_release_rx_pdc':
    atmel_serial.c:(.text+0x25362): undefined reference to `dma_unmap_single'
    drivers/built-in.o: In function `atmel_tx_pdc':
    atmel_serial.c:(.text+0x25722): undefined reference to `dma_sync_single_for_cpu'
    drivers/built-in.o: In function `atmel_rx_from_pdc':
    atmel_serial.c:(.text+0x2601a): undefined reference to `dma_sync_single_for_cpu'
    drivers/built-in.o: In function `atmel_rx_from_dma':
    atmel_serial.c:(.text+0x261b2): undefined reference to `dma_sync_sg_for_cpu'
    atmel_serial.c:(.text+0x26264): undefined reference to `dma_sync_sg_for_cpu'
    drivers/built-in.o: In function `atmel_prepare_rx_pdc':
    atmel_serial.c:(.text+0x262de): undefined reference to `dma_unmap_single'
    atmel_serial.c:(.text+0x26308): undefined reference to `dma_map_single'

Add a dependency on HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>