mtd: maps: add missing iounmap() in error path
This patch was triggered by the following Coccinelle error:

./drivers/mtd/maps/sc520cdp.c:246:3-9: \
	ERROR: missing iounmap; ioremap on line 242 \
	and execution via conditional on line 244

Signed-off-by: Luis Henriques <henrix@camandro.org>