sir_ir: annotate hardware config module parameters
On Wed, Jun 07, 2017 at 09:38:57AM -0300, Mauro Carvalho Chehab wrote:
> Em Tue,  6 Jun 2017 16:18:19 +0100
> Sean Young <sean@mess.org> escreveu:
>
> > This module was merged after commit 5a8fc6a3cebb ("Annotate hardware
> > config module parameters in drivers/media/"), so add add the missing
> > hardware annotations.
>
> This patch seems wrong:
>
> drivers/media/rc/sir_ir.c:403:1: error: macro "module_param_hw" requires 4 arguments, but only 3 given
> drivers/media/rc/sir_ir.c:406:1: error: macro "module_param_hw" requires 4 arguments, but only 3 given
> drivers/media/tuners/r820t.c:2341 r820t_attach() error: potential null dereference 'priv'.  (kzalloc returns null)
> drivers/media/rc/sir_ir.c:403:30: error: macro "module_param_hw" requires 4 arguments, but only 3 given
>  module_param_hw(io, int, 0444);
>                               ^
> drivers/media/rc/sir_ir.c:403:1: warning: data definition has no type or storage class
>  module_param_hw(io, int, 0444);
>  ^~~~~~~~~~~~~~~
> drivers/media/rc/sir_ir.c:403:1: error: type defaults to 'int' in declaration of 'module_param_hw' [-Werror=implicit-int]
> drivers/media/rc/sir_ir.c:406:31: error: macro "module_param_hw" requires 4 arguments, but only 3 given
>  module_param_hw(irq, int, 0444);
>                                ^
> drivers/media/rc/sir_ir.c:406:1: warning: data definition has no type or storage class
>  module_param_hw(irq, int, 0444);
>  ^~~~~~~~~~~~~~~
> drivers/media/rc/sir_ir.c:406:1: error: type defaults to 'int' in declaration of 'module_param_hw' [-Werror=implicit-int]
>
> Please check.

Oh dear, that's embarrassing. :(

Sean

From: Sean Young <sean@mess.org>
Subject: [PATCH] [media] sir_ir: annotate hardware config module parameters

This module was merged after commit 5a8fc6a3cebb ("Annotate hardware
config module parameters in drivers/media/"), so add add the missing
hardware annotations.

Signed-off-by: Sean Young <sean@mess.org>