s390/virtio: fix compilation of kvm_virtio.c in linux-next
Michael,
commit db932ced55cf ("virtio: add context flag to find vqs") of
linux-next causes this build failure:

drivers/s390/virtio/kvm_virtio.c: In function ‘kvm_find_vq’:
drivers/s390/virtio/kvm_virtio.c:215:18: error: passing argument 8 of
‘vring_new_virtqueue’ from incompatible pointer type
[-Werror=incompatible-pointer-types]
      kvm_notify, callback, name);
                  ^~~~~~~~
In file included from drivers/s390/virtio/kvm_virtio.c:22:0:
./include/linux/virtio_ring.h:93:19: note: expected ‘bool (*)(struct
virtqueue *) {aka _Bool (*)(struct virtqueue *)}’ but argument is of
type ‘void (*)(struct virtqueue *)’
 struct virtqueue *vring_new_virtqueue(unsigned int index,
                   ^~~~~~~~~~~~~~~~~~~
drivers/s390/virtio/kvm_virtio.c:215:28: error: passing argument 9 of
‘vring_new_virtqueue’ from incompatible pointer type
[-Werror=incompatible-pointer-types]
      kvm_notify, callback, name);
                            ^~~~
In file included from drivers/s390/virtio/kvm_virtio.c:22:0:
./include/linux/virtio_ring.h:93:19: note: expected ‘void (*)(struct
virtqueue *)’ but argument is of type ‘const char *’
 struct virtqueue *vring_new_virtqueue(unsigned int index,
                   ^~~~~~~~~~~~~~~~~~~
drivers/s390/virtio/kvm_virtio.c:213:7: error: too few arguments to
function ‘vring_new_virtqueue’
  vq = vring_new_virtqueue(index, config->num,
KVM_S390_VIRTIO_RING_ALIGN,
       ^~~~~~~~~~~~~~~~~~~
In file included from drivers/s390/virtio/kvm_virtio.c:22:0:
./include/linux/virtio_ring.h:93:19: note: declared here
 struct virtqueue *vring_new_virtqueue(unsigned int index,
                   ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

Looks like the new ctx was not added here.

Signed-off-by: Christian Borntraeger <borntraeger@de.ibm.com>