printk: remove unused suppress_message_printing()
Moving the call to suppress_message_printing() into the '#ifdef CONFIG_PRINTK'
section means that the alternative definition is now unused when PRINTK is
disabled:

kernel/printk/printk.c:2033:13: error: 'suppress_message_printing' defined but not used [-Werror=unused-function]

This removes the stub function.

Fixes: 375899cddcbb ("printk: make sure to print log on console.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>