net: mlx5: remove pointless memcpy
gcc-8 notices that the memcpy in mlx5_core_query_xsrq() makes no
sense because the source and destination variables are identical:

drivers/net/ethernet/mellanox/mlx5/core/transobj.c: In function 'mlx5_core_query_xsrq':
drivers/net/ethernet/mellanox/mlx5/core/transobj.c:347:3: error: 'memcpy' source argument is the same as destination [-Werror=restrict]

Either one of the pointers should be something else, or the code is
completely bogus. Removing the memcpy() won't change the behavior
but gets rid of the warning.

Fixes: 01949d0109ee ("net/mlx5_core: Enable XRCs and SRQs when using ISSI > 0")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>