mm/slub: Mark slab_free_hook() as __maybe_unused
The function is only used when certain configuration option are enabled.
Adding the attribute fixes the following warning when building with
clang:

mm/slub.c:1258:20: error: unused function 'slab_free_hook'
    [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>