ALSA: als4000: Use common error handling code in snd_card_als4000_probe()
* Adjust jump targets so that a bit of exception handling can be better
  reused at the end of this function.

  This issue was detected by using the Coccinelle software.

* The script "checkpatch.pl" pointed information out like the following.

  ERROR: do not use assignment in if condition

  Thus fix eight affected source code places.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>