firmware: efi: arm-runtime: fix build error void value not ignored
Commit e2a2e56e4082 ("arm64: dump: no need to check return value of debugfs_create functions")
changed the return value from 'int' to 'void'.

../drivers/firmware/efi/arm-runtime.c: In function ‘ptdump_init’:
../drivers/firmware/efi/arm-runtime.c:52:9: error: void value not ignored as it ought to be
  return ptdump_debugfs_register(&efi_ptdump_info, "efi_page_tables");
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/firmware/efi/arm-runtime.c:53:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^

Rework so that function 'ptdump_init' doesn't 'return
ptdump_debug_fs_register(...' since the function can work or not, but
the code logic should never do something different based on this.

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>