soc: imx: Select PM_GENERIC_DOMAINS only if PM is enabled
Selecting PM_GENERIC_DOMAINS without PM results in the following build
errors, seen when building sparc32:allmodconfig.

drivers/base/power/domain.c: In function 'genpd_queue_power_off_work':
drivers/base/power/domain.c:279:13: error: 'pm_wq' undeclared
drivers/base/power/domain.c: In function 'genpd_dev_pm_qos_notifier':
drivers/base/power/domain.c:462:25: error:
	'struct dev_pm_info' has no member named 'ignore_children'
drivers/base/power/domain.c: In function 'rtpm_status_str':
drivers/base/power/domain.c:2207:16: error:
	'struct dev_pm_info' has no member named 'runtime_error'
drivers/base/power/domain.c:2209:21: error:
	'struct dev_pm_info' has no member named 'disable_depth'
drivers/base/power/domain.c:2211:21: error:
	'struct dev_pm_info' has no member named 'runtime_status'
drivers/base/power/domain.c:2212:31: error:
	'struct dev_pm_info' has no member named 'runtime_status'

Fixes: 03aa12629fc4 ("soc: imx: Add GPCv2 power gating driver")
Cc: Andrey Smirnov <andrew.smirnov@gmail.com>
Cc: Shawn Guo <shawnguo@kernel.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>