kbuild: export SUBARCH
Fixes the following build error on x86:

  gcc -Wp,-MD,arch/x86/entry/vdso/.vdso2c.d -O2 -I/Users/nbd/lede/staging_dir/host/include -I/Users/nbd/lede/staging_dir/host/usr/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/Users/nbd/lede/staging_dir/host/include -I./tools/include -I./include/uapi -I./arch//include/uapi  -o arch/x86/entry/vdso/vdso2c arch/x86/entry/vdso/vdso2c.c -L/Users/nbd/lede/staging_dir/host/lib
  In file included from arch/x86/entry/vdso/vdso2c.c:66:
  In file included from ./include/uapi/linux/elf.h:4:
  ./tools/include/linux/types.h:9:10: fatal error: 'asm/types.h' file not found
  #include <asm/types.h>

Fixes: d51306f1a3bc ("x86: Make the vdso2c compiler use the host architecture headers")
Signed-off-by: Felix Fietkau <nbd@nbd.name>