net: atm: Fix build error when !CONFIG_PROC_FS
When CONFIG_ATM_CLIP is set and CONFIG_PROC_FS is not set, the building
was failing whith the error:

net/atm/clip.c: In function ‘atm_clip_exit’:
net/atm/clip.c:933:27: error: ‘atm_proc_root’ undeclared (first use in
this function)
remove_proc_entry("arp", atm_proc_root);
                           ^

Fix it by putting the proc cleanup code inside a #ifdef CONFIG_PROC_FS
block.

Signed-off-by: Augusto Mecking Caringi <augustocaringi@gmail.com>