fs: crypto: add CONFIG_BLOCK dependency
The newly added generic crypto abstraction for file systems operates
on 'struct bio' objects, which do not exist when CONFIG_BLOCK is
disabled:

fs/crypto/crypto.c: In function 'fscrypt_zeroout_range':
fs/crypto/crypto.c:308:9: error: implicit declaration of function 'bio_alloc' [-Werror=implicit-function-declaration]

This adds a Kconfig dependency that prevents FS_ENCRYPTION from being
enabled without BLOCK.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 846c506fadf7 ("fs crypto: add Makefile and Kconfig")