xfs: fix build without xfsstats
A recent rework of the xfsstats interface introduced a compile error
for the procfs-disabled case:

fs/built-in.o: In function `xfs_free_ag_extent':
fs/xfs/libxfs/xfs_alloc.c:1725: undefined reference to `xfsstats'
fs/built-in.o: In function `xfs_alloc_ag_vextent':
fs/xfs/libxfs/xfs_alloc.c:645: undefined reference to `xfsstats'
fs/built-in.o: In function `xfs_attr_set':
fs/xfs/libxfs/xfs_attr.c:353: undefined reference to `xfsstats'
fs/built-in.o: In function `xfs_attr_remove':
fs/xfs/libxfs/xfs_attr.c:483: undefined reference to `xfsstats'
fs/built-in.o: In function `xfs_attr_get':
fs/xfs/libxfs/xfs_attr.c:131: undefined reference to `xfsstats'
fs/built-in.o:fs/xfs/libxfs/xfs_bmap.c:1461: more undefined references to `xfsstats' follow

This adds conditional compilation to each reference of the xfsstats
global variable to get it to link again.

An alternative approach would be to always build the statistics
implementation even when CONFIG_PROC_FS is disabled.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 80529c45ab66 ("xfs: pass xfsstats structures to handlers and macros")
Fixes: ff6d6af2351c ("xfs: per-filesystem stats counter implementation")