clocksource: j-core: type fix init function return code
The CLOCKSOURCE_OF_DECLARE now takes a function that returns an 'int', but a this
new clocksource driver has just appeared in linux-next and causes a warning because
it has the old 'void' return value:

In file included from ../include/linux/clocksource.h:18:0,
                 from ../include/linux/clockchips.h:13,
                 from ../drivers/clocksource/jcore-pit.c:14:
include/linux/of.h:1006:20: error: comparison of distinct pointer types lacks a cast [-Werror]
        .data = (fn == (fn_type)NULL) ? fn : fn  }
                    ^

This adapts the jcore_pit_init() function to the correct return type.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: e0aa0655c60b ("clocksource: add J-Core timer/clocksource driver")