pwm: imx27: fix build issue
When PWM_IMX27 was configured as a module we got the following
build error:

In file included from ../drivers/pwm/pwm-imx27.c:15:
../drivers/pwm/pwm-imx27.c:292:25: error: ‘imx_pwm_dt_ids’
undeclared here (not in a function); did you mean ‘pwm_imx27_dt_ids’?
 MODULE_DEVICE_TABLE(of, imx_pwm_dt_ids);
                         ^~~~~~~~~~~~~~
../include/linux/module.h:213:15: note: in definition of macro ‘MODULE_DEVICE_TABLE’
 extern typeof(name) __mod_##type##__##name##_device_table  \
               ^~~~
../include/linux/module.h:213:21: error: ‘__mod_of__imx_pwm_dt_ids_device_table’
aliased to undefined symbol ‘imx_pwm_dt_ids’
 extern typeof(name) __mod_##type##__##name##_device_table  \
                     ^~~~~~
../drivers/pwm/pwm-imx27.c:292:1: note: in expansion of macro ‘MODULE_DEVICE_TABLE’
 MODULE_DEVICE_TABLE(of, imx_pwm_dt_ids);
 ^~~~~~~~~~~~~~~~~~~

Rework to use the new variable name pwm_imx27_dt_ids.

Fixes: 5a309d380019 ("pwm: imx: Split into two drivers")
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>