False positive in scripts/checkpatch.pl
scripts/checkpatch.pl reports

ERROR: Please use git commit description style
'commit <12+ chars of sha1> ("<title line>")'-
ie: 'commit 0123456789ab ("commit description")'

for this patch.

On 64bit systems an undetected overflow may occur in
do_proc_dointvec_minmax_conv_param as can be demonstrated
with the following example:

	# echo 9223372036854776806 > /proc/sys/kernel/threads-max
	# cat /proc/sys/kernel/threads-max
	998

Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>