pwm: fix undefined behavior in stm32_pwm_apply
The stm32_pwm_apply randomly sets the polarity or doesn't,
as pointed out by this gcc warning:

drivers/pwm/pwm-stm32.c: In function 'stm32_pwm_apply':
drivers/pwm/pwm-stm32.c:204:33: error: 'curstate.polarity' may be used uninitialized in this function [-Werror=maybe-uninitialized]

I assume it was meant to compare the new state to the current
state rather than an uninitialized stack variable, so let's
do that instead.

Fixes: bafffb6e7bd1 ("pwm: Add driver for STM32 plaftorm")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>