v4l2/dvb: allow v4l2_mc functions to be used by dvb
In a configuration that supports all DVB drivers but that disables
V4L2 or builds it as a loadable module, we get link errors because
of the recent change to use __v4l2_mc_usb_media_device_init:

drivers/media/built-in.o: In function `dvb_usb_adapter_dvb_init':
:(.text+0xe7966): undefined reference to `__v4l2_mc_usb_media_device_init'
drivers/media/built-in.o: In function `dvb_usbv2_init':
:(.text+0xff1cc): undefined reference to `__v4l2_mc_usb_media_device_init'
drivers/media/built-in.o: In function `smsusb_init_device':
:(.text+0x113be4): undefined reference to `__v4l2_mc_usb_media_device_init'
drivers/media/built-in.o: In function `au0828_usb_probe':
:(.text+0x114d08): undefined reference to `__v4l2_mc_usb_media_device_init'

This patch is one way out, by simply building the v4l2-mc.c file
whenever at least one of VIDEO_V4L2 or DVB_CORE are enabled, including
the case that one of them is a module and the other is built-in, which
leads the MC code to become built-in as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>