tools/perf/inject: fix dwarf support detection
I ran into problems trying to use the JIT support and display
source-level information. Basically, there was no dwarf debug
info generated in the jitted-XX.so files, yet I had libdw-dev
installed.

Turns out that the feature test build for test-dwarf.bin was broken
for me. It would die for the wrong reason:

/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libdw.so: undefined reference to `elf_compress@ELFUTILS_1.7'

In other words, the libdw has a dependency on libelf which the Makefile
was not accounting for. Thus perf was not compiled with HAVE_DWARF_SUPPORT
and the code in genelf.c was not compiled in.

This patch fixes the issue by adding -lelf to the build rule for test-dwarf.c.

I wasted quite some time trying to debug this, so I have added a warning
in builtin-inject.c so that the user is warned that in case dwarf support
is disabled, no source line information will be generated in the output
.so files from the jitted code.

In v2, we removed the extraneaous echo in the make target.
In v3, we removed the superfluous -lelf from the static build DWARFLIBS.

Signed-off-by: Stephane Eranian <eranian@google.com>