gpio: ingenic: add CONFIG_OF dependency
The driver cannot access the of_node field when CONFIG_OF is disabled:

drivers/gpio/gpio-ingenic.c: In function 'ingenic_gpio_probe':
drivers/gpio/gpio-ingenic.c:324:10: error: 'struct gpio_chip' has no member named 'of_node'

Fixes: b0653ce39a0d ("gpio: Add gpio-ingenic driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>