bitfield: Use __ffs64(x) to fix missing __ffsdi2()
On most architectures[*], gcc turns __builtin_ffsll() into a call to
__ffsdi2(), which is not provided by any architecture, leading to
failures like:

    rcar-gen3-cpg.c:(.text+0x289): undefined reference to `__ffsdi2'

To fix this, use __ffs64() instead, which is available on all
architectures.

[*] Known exceptions are some 64-bit architectures like amd64, arm64,
    ia64, powerpc64, and tilegx.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Fixes: 3e9b3112ec74f192 ("add basic register-field manipulation macros")
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>