powerpc: Mark variable `cpumsr` as unused
Add gcc attribute unused for `cpumsr` variable.

Fix warnings treated as errors with W=1:

  arch/powerpc/kernel/process.c:231:16: error: variable ‘cpumsr’ set but not used [-Werror=unused-but-set-variable]
  arch/powerpc/kernel/process.c:296:16: error: variable ‘cpumsr’ set but not used [-Werror=unused-but-set-variable]

Signed-off-by: Mathieu Malaterre <malat@debian.org>