PCI: mediatek: change to use pci_scan_root_bus_bridge()
This is a critical patch fixes Build bot failed:
> 	arm-allmodconfig
> ../drivers/pci/host/pcie-mediatek.c:485:8: error: implicit declaration of
function 'pci_register_host_bridge' [-Werror=implicit-function-declaration]

It uses the new registration methods pci_scan_root_bus_bridge().

Signed-off-by: Ryder Lee <ryder.lee@mediatek.com>