drm/amdgpu: enable powerplay unconditionally
Using the newly exported amd_set_clockgating_by_smu function in the main amdgpu driver
means that we can no longer build the driver without also enabling the powerplay
component, otherwise we get this link error:

ERROR: "amd_set_clockgating_by_smu" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!

The easiest way to avoid this error is to always enable the Kconfig symbol when
the amdgpu driver is enabled.

Fixes: a8ca34136453 ("drm/amdgpu: set gfx clock gating for tonga/polaris.")
Fixes: 1bb08f91b0f6 ("drm/amdgpu: set system clock gating for tonga/polaris.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>