bus: tegra-gmi: fix build error
The newly added driver fails to build right away:

drivers/bus/tegra-gmi.c: In function 'tegra_gmi_parse_dt':
drivers/bus/tegra-gmi.c:97:11: error: 'dev' undeclared (first use in this function)

I guess a last-minute change removed a local variable, this
adds the obvious definiton.

Fixes: 4f95e6a5c9e4 ("bus: Add support for Tegra Generic Memory Interface")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>