blackfin: define dummy pgprot_writecombine for !MMU
blackfin allmodconfig build fails with the error:

../sound/core/pcm_native.c: In function 'snd_pcm_lib_default_mmap':
../sound/core/pcm_native.c:3386:24: error: implicit declaration of function 'pgprot_writecombine' [-Werror=implicit-function-declaration]
   area->vm_page_prot = pgprot_writecombine(area->vm_page_prot);
                        ^
../sound/core/pcm_native.c:3386:22: error: incompatible types when assigning to type 'pgprot_t {aka struct <anonymous>}' from type 'int'
   area->vm_page_prot = pgprot_writecombine(area->vm_page_prot);
                      ^

When !MMU, asm-generic will not define default pgprot_writecombine, so
blackfin needs to define it by itself.

Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>