irqchip or mfd/tps65217: fix link error
Building tps65217 as a loadable module (as done in allmodconfig)
now fails after we started calling irq_set_parent():

  ERROR: "irq_set_parent" [drivers/mfd/tps65217.ko] undefined!

The two obvious workarounds are either to force the driver
to be built-in, or to make that symbol exported to modules.

As it's not clear to me if either of them would be acceptable,
I'm sending both of them here, please comment on which one
you want to have, or whether the driver should handle this
differently and not call irq_set_parent() at all.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 262d5cc6ceb2 ("mfd: tps65217: Add support for IRQs")