perf tools: Fix compiler error due to header file changes
The commit 41840d211c51 ("perf config: Move config declarations from
util/cache.h to util/config.h") moved perf_config*(), causes the
following errors when we build with LIBBABELTRACE=1:

  util/data-convert-bt.c: In function ‘convert__config’:
  util/data-convert-bt.c:1269:3: error: implicit declaration of function ‘perf_config_u64’ [-Werror=implicit-function-declaration]
     c->queue_size = perf_config_u64(var, value);
     ^
  util/data-convert-bt.c:1269:3: error: nested extern declaration of ‘perf_config_u64’ [-Werror=nested-externs]
  util/data-convert-bt.c: In function ‘bt_convert__perf2ctf’:
  util/data-convert-bt.c:1302:2: error: implicit declaration of function ‘perf_config’ [-Werror=implicit-function-declaration]
    perf_config(convert__config, &c);
    ^

Include the right header file to fix this.

Signed-off-by: He Kuang <hekuang@huawei.com>