linux-next: build failure after merge of the slave-dma tree
Hi Vinod,

After merging the slave-dma tree, today's linux-next build (x86_64
allmodconfig) failed like this:

drivers/dma/idma64.h:19:47: fatal error: asm-generic/io-64-nonatomic-lo-hi.h: No such file or directory
 #include <asm-generic/io-64-nonatomic-lo-hi.h>
                                               ^

Caused by commit

  97c37accd38f ("dmaengine: idma64: use lo_hi_readq() / lo_hi_writeq()")

interacting with commit

  f626fe17485b ("move io-64-nonatomic*.h out of asm-generic")

from the asm-generic tree.

I have applied the folling merge fix patch and can carry it as necessary.

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Thu, 15 Oct 2015 11:47:07 +1100
Subject: [PATCH] dmaengine: idma64: merge fix for "move io-64-nonatomic*.h out of asm-generic"

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>