next: media: cx231xx: add #ifdef to fix compile error
Compiling linux-next gave this warning:

drivers/media/usb/cx231xx/cx231xx-cards.c: In function
‘cx231xx_usb_probe’:
drivers/media/usb/cx231xx/cx231xx-cards.c:1754:36: error: ‘struct
cx231xx’ has no member named ‘media_dev’
  retval = media_device_register(dev->media_dev);

Looking at the refactoring in past two commits, following seems like a
decent fix, i.e. to surround dev->media_dev by #ifdef
CONFIG_MEDIA_CONTROLLER.

Signed-off-by: Okash Khawaja <okash.khawaja@gmail.com>