linux-next: build failure after merge of the input tree
Hio,

On 16-10-15 04:19, Stephen Rothwell wrote:
> Hi Dmitry,
>
> After merging the input tree, today's linux-next build (x86_64
> allmodconfig) failed like this:
>
> In file included from samples/hidraw/hid-example.c:14:0:
> ./usr/include/linux/input.h:17:31: fatal error: input-event-codes.h: No such file or directory
>
> Caused by commit
>
>    d794709c3916 ("Input: Add input-event-codes header file")
>
> I have used the input tree from next-20151015 for today.

Sorry, my bad, I assumed anything under include/uapi would
automatically get installed as a usr header, but it turns out
any files added need to also be added to the Kbuild file, the
attached patch should fix this.

Dmitry, feel free to squash this into the original patch.

Regards,

Hans

From 0dd5544b6ca0cddfe25976b46ef9ba5c4adbc791 Mon Sep 17 00:00:00 2001
From: Hans de Goede <hdegoede@redhat.com>
Date: Fri, 16 Oct 2015 09:33:45 +0200
Subject: [PATCH] input: Add input-event-codes.h to usr headers to install

Add input-event-codes.h to the list of uapi headers to install, this fixes
build-failures of any userspace tools including linux/input.h .

Signed-off-by: Hans de Goede <hdegoede@redhat.com>