phy: Fix build error of missing devm_ioremap_resource on UM
The devres.o gets linked if HAS_IOMEM is present so on ARCH=um
allyesconfig (COMPILE_TEST) failed with:

drivers/built-in.o: In function `omap_control_phy_probe':
phy-omap-control.c:(.text+0x16db): undefined reference to `devm_ioremap_resource'
drivers/built-in.o: In function `cygnus_pcie_phy_probe':
phy-bcm-cygnus-pcie.c:(.text+0x1bfa): undefined reference to `devm_ioremap_resource'

Signed-off-by: Krzysztof Kozlowski <k.kozlowski@samsung.com>