fs, proc: remove unused variable
The last cleanup can go a little further, as shown by this warning:

fs/proc/task_mmu.c: In function 'show_map_vma':
fs/proc/task_mmu.c:285:28: error: unused variable 'priv' [-Werror=unused-variable]

Fixes: 14ccc3193225 ("fs, proc: remove priv argument from is_stack")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>