ocfs2: remove unused label
A recent cleanup modified the ocfs2_file_write_iter function, which
no longer uses its 'relock' label, as gcc warns:

fs/ocfs2/file.c: In function 'ocfs2_file_write_iter':
fs/ocfs2/file.c:2198:1: error: label 'relock' defined but not used [-Werror=unused-label]

This removes the label as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 1a46f12e5071 ("ocfs2: code clean up for direct io")