sched/numa: fix build without CONFIG_NUMA_BALANCING
I ran into a build error:

kernel/sched/fair.c:2655:44: error: 'struct sched_domain' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]

Adding a forward declaration for the struct name is sufficient
to avoid it.

Fixes: 3fed382b46ba ("sched/numa: Implement NUMA node level wake_affine()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>