m32r: fix build warning about putc
We were getting build warning:
arch/m32r/boot/compressed/m32r_sio.c:11:13:
        warning: conflicting types for built-in function 'putc'

Here putc is used as a static function so lets just rename it to avoid
the conflict with the builtin putc.

Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>