mfd: asic3: remove extraneous ')'
A cleanup patch introduced an extra closing ')' that leads to a
build error:

drivers/mfd/asic3.c: In function 'asic3_gpio_get':
drivers/mfd/asic3.c:505:12: error: expected ';' before ')' token

This removes the extra character to get it to build again.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: fd5b4d01a638 ("mfd: asic3: Be sure to clamp return value")