PCI: host-generic: select IRQ_DOMAIN
The generic PCI host controller calls of_irq_parse_and_map_pci
in its IRQ fixup, but that function is only available when
CONFIG_IRQ_DOMAIN is set:

drivers/pci/built-in.o: In function `pci_host_common_probe':
drivers/pci/host/pci-host-common.c:181: undefined reference to `of_irq_parse_and_map_pci'

There is no downside in enabling the domains here, so let's
use a Kconfig select statement to ensure it's always available
to this driver.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>