ASoC: cs53l30: include gpio/consumer.h
cs53l30 breaks kernel compilation when CONFIG_GPIOLIB is disabled.

sound/soc/codecs/cs53l30.c:931:2: error: implicit declaration of
function devm_gpiod_get_optional [-Werror=implicit-function-declaration]
  cs53l30->reset_gpio = devm_gpiod_get_optional(dev, "reset",
  ^
sound/soc/codecs/cs53l30.c:932:13: error: GPIOD_OUT_LOW undeclared
(first use in this function)

Including gpio/consumer.h declares minimal functions in that case.

Signed-off-by: Fabian Frederick <fabf@skynet.be>