score: Add missing include files
Kernel builds fail with

arch/score/kernel/traps.c: In function 'do_ri':
arch/score/kernel/traps.c:248:4: error:
	implicit declaration of function 'user_disable_single_step'
arch/score/mm/extable.c: In function 'fixup_exception':
arch/score/mm/extable.c:32:38: error:
	dereferencing pointer to incomplete type
arch/score/mm/extable.c:34:24: error:
	dereferencing pointer to incomplete type

Fixes: 0f296af85be8 ("score: migrate exception table users off ...")
Cc: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>