drm: exynos: mark pm functions __maybe_unused
The exynos drm driver implements power management functions that
are hidden inside of #ifdef, but when they are all disabled,
we get a warning about another unused function that is not
called from elsewhere:

drivers/gpu/drm/exynos/exynos_drm_gsc.c:1219:12: error: 'gsc_clk_ctrl' defined but not used [-Werror=unused-function]

This removes the #ifdef and instead uses a __maybe_unused annotation
that avoids the problem because now gcc can see how the function is
(not) used and silently drop it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>