uvcvideo: Hardcoded CTRL_QUERY GET_LEN for a lying device
Hello,

I sent this patch on the linux-uvc ML but it seems effectively dead nowadays.
This thread comes after two others[1][2] about a similar issue.

I own a USB video microscope[3] from Dino-Lite. Even if the constructor does
not advertise it as being supported on Linux, it is mostly a "good citizen"
camera: it registers as a standard USB video device and as such, it is properly
recognized by uvcvideo.

This device is equipped with an integrated illuminator/lamp -- a set of LEDs.
After some research (using a USB sniffer) I managed to identify the
non-standard XU control used to switch this lamp on and off: one shall send
either 80 01 f0 (off) or 80 01 f1 (on) to XU control unit 4 selector 3.

So at first I tried to send a raw ctrl_set using:

    $ uvcdynctrl -S 4:3 8001f0
    [...]
    query control size of : 1
    [...]
    ERROR: Unable to set the control value: Invalid argument. (Code: 3)

Indeed, the device reports this XU as being only 1 in length, but the payload
has to be 3 bytes. So I assume there is a bug (or deliberate inaccuracy) in the
GET_LEN reply from the device firmware. To overcome this issue, I compiled
a patched version of uvcvideo in which uvc_query_ctrl[4] returns an hardcoded
size of 3 for this specific device & UX control. I was finally able to switch
the lamp on and off:

    $ uvcdynctrl -S 4:3 8001f0
    [39252.854261] uvcvideo: Fixing USB a168:0870 UX control 4/3 len: 1 -> 3
    [...]
    query control size of : 3
    [...]
    set value of          : (LE)0x8001f0  (BE)0xf00180
    [lamp goes off]

You can find the patch below. I abstracted it in the spirit of
uvc_ctrl_fixup_xu_info[5] so we can add more entries to the table in the
future. What do you think, would it be relevant to merge? AFAICT there is no
API in uvcvideo or v4l for controlling this kind of illuminator/lamp features,
so giving userland the ability to control the devices via XU by lying seems to
be the only solution.

Best,

Alexandre

[1] "Dino-Lite uvc support", 2008, https://sourceforge.net/p/linux-uvc/mailman/message/29831153/
[2] "switching light on device Dino-Lite Premier", 2013, https://sourceforge.net/p/linux-uvc/mailman/message/31219122/
[3] https://www.dinolite.us/products/digital-microscopes/usb/basic/am4111t
[4] http://elixir.free-electrons.com/linux/v4.11/source/drivers/media/usb/uvc/uvc_video.c#L72
[5] http://elixir.free-electrons.com/linux/v4.11/source/drivers/media/usb/uvc/uvc_ctrl.c#L1593

Signed-off-by: Alexandre Macabies <web+oss@zopieux.com>