x86: vsmp: avoid link error with gcc -Og
When the compiler skips optimizations for ease of debugging,
teh vsmp_cap_cpus() function is not eliminated from the build
with CONFIG_PCI=n:

arch/x86/kernel/vsmp_64.o: In function `vsmp_cap_cpus':
vsmp_64.c:(.init.text+0x23): undefined reference to `read_pci_config'

Change the caller in a way that will always optimize this
as required.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>