ovl: fix ovl_rename error handling
We try to clean up two objects before they got initialized:

fs/overlayfs/dir.c: In function 'ovl_rename':
fs/overlayfs/dir.c:1060:2: error: 'newdentry' may be used uninitialized in this function [-Werror=maybe-uninitialized]
fs/overlayfs/dir.c:891:17: note: 'newdentry' was declared here
fs/overlayfs/dir.c:1062:2: error: 'olddentry' may be used uninitialized in this function [-Werror=maybe-uninitialized]
fs/overlayfs/dir.c:890:17: note: 'olddentry' was declared here

Assuming that no special cleanup is required for the new code, the correct
branch target should be "out_revert_creds" to clean up everything that
got initialized up to then.

Fixes: 02cac3227a28 ("ovl: mark upper dir with type origin entries "impure"")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>