watchdog: orion: don't build for ARCH_EBSA110
The randconfig builder caught another corner case with this driver that
fails to build for EBSA110 since that has its own MMIO handlers and
lacks atomic_io_modify:

drivers/watchdog/orion_wdt.o: In function `orion_stop':
orion_wdt.c:(.text.orion_stop+0x28): undefined reference to `atomic_io_modify'
orion_wdt.c:(.text.orion_stop+0x3c): undefined reference to `atomic_io_modify'
drivers/watchdog/orion_wdt.o: In function `armada370_wdt_clock_init':
orion_wdt.c:(.text.armada370_wdt_clock_init+0x2c): undefined reference to `atomic_io_modify'
drivers/watchdog/orion_wdt.o: In function `armada375_stop':
orion_wdt.c:(.text.armada375_stop+0x28): undefined reference to `atomic_io_modify'
orion_wdt.c:(.text.armada375_stop+0x58): undefined reference to `atomic_io_modify'

The best workaround I can think of is to add another Kconfig dependency.
We could add atomic_io_modify() for ebsa110 in theory, but it seemed
wrong because that platform would never actually use it.

Fixes: da2a68b3eb47 ("watchdog: Enable COMPILE_TEST where possible")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>