sched/clock: add dummy clear_sched_clock_stable stub function
In commit acb04058de49458010c44bb35b849d45113fd668 ("sched/clock:
Fix hotplug crash") the parisc code gained a call to this function.

However the prototype for it is within HAVE_UNSTABLE_SCHED_CLOCK
ifdef/endif.  That, combined with this:

  arch/parisc/Kconfig:    select HAVE_UNSTABLE_SCHED_CLOCK if SMP

means that parisc can have it either enabled or disabled, resulting
in the following build fail:

arch/parisc/kernel/setup.c:180:2: error: implicit declaration of
function 'clear_sched_clock_stable' [-Werror=implicit-function-declaration]

Add a no-op stub for the non-SMP case to prevent this.

Fixes: acb04058de49 ("sched/clock: Fix hotplug crash")
Cc: Peter Zijlstra (Intel) <peterz@infradead.org>
Cc: Ingo Molnar <mingo@kernel.org>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>