perf tools: Remove BUG_ON char[] to bool implicit conversions
When compiling with LLVM, errors like this are shown:

  builtin-lock.c:46:10: error: implicit conversion turns string literal into bool: 'const char [39]' to 'bool'

due to error message implicit conversion into bool. Fix it printing
the error message and returning an error when possible.

Signed-off-by: David Carrillo-Cisneros <davidcc@google.com>