PCI: altera: add OF_PCI dependency
The newly added altera PCI driver fails to build when CONFIG_OF
is disabled:

drivers/pci/host/pcie-altera.c: In function 'altera_pcie_parse_request_of_pci_ranges':
drivers/pci/host/pcie-altera.c:420:8: error: implicit declaration of function 'of_pci_get_host_bridge_resources' [-Werror=implicit-function-declaration]

This adds a dependency on OF_PCI for clarity, this is the symbol
that guards the implementation of of_pci_get_host_bridge_resources.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 6bb4dd154ae8 ("PCI: altera: Add Altera PCIe host controller driver")