crypto: morus - Hide Kconfig option for glue code
Enabling the glue drivers for morus640 and/or morus1280 leads to a build failure
on all non-x86 architectures:

crypto/morus1280_glue.c:24:10: fatal error: asm/fpu/api.h: No such file or directory
scripts/Makefile.build:311: recipe for target 'crypto/morus1280_glue.o' failed
crypto/morus640_glue.c:24:10: fatal error: asm/fpu/api.h: No such file or directory
scripts/Makefile.build:311: recipe for target 'crypto/morus640_glue.o' failed

There really is no reason to enable these unless we also have a real
driver using the glue, so the Kconfig option can be hidden and remain
selected by the x86 specific SIMD drivers or any others getting added
in the future.

Fixes: 56e8e57fc3a7 ("crypto: morus - Add common SIMD glue code for MORUS")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>