drivers/clk/uniphier/clk-uniphier-mio.c: fix build for older gcc
gcc-4.4.4 (at least) has issues with anon union initializers.

drivers/clk/uniphier/clk-uniphier-mio.c:81: error: unknown field 'mux' specified in initializer
drivers/clk/uniphier/clk-uniphier-mio.c:81: error: unknown field 'parent_names' specified in initializer
drivers/clk/uniphier/clk-uniphier-mio.c:81: warning: missing braces around initializer
drivers/clk/uniphier/clk-uniphier-mio.c:81: warning: (near initialization for 'uniphier_sld3_mio_clk_data[8].<anonymous>.cpugear.parent_names')
drivers/clk/uniphier/clk-uniphier-mio.c:81: error: unknown field 'num_parents' specified in initializer
drivers/clk/uniphier/clk-uniphier-mio.c:81: warning: excess elements in union initializer
drivers/clk/uniphier/clk-uniphier-mio.c:81: warning: (near initialization for 'uniphier_sld3_mio_clk_data[8].<anonymous>')
drivers/clk/uniphier/clk-uniphier-mio.c:81: error: unknown field 'reg' specified in initializer
...


Fixes: 7f4d3b52b6b69f ("clk: uniphier: add clock data for UniPhier SoCs")
Cc: Masahiro Yamada <yamada.masahiro@socionext.com>
Cc: Rob Herring <robh@kernel.org>
Cc: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>