dwc3: make PM functions as __maybe_unused
A change to the suspend/resume handling in dwc3-pci introduced a
harmless warning:

drivers/usb/dwc3/dwc3-pci.c:169:12: error: ‘dwc3_pci_dsm’ defined but not used [-Werror=unused-function]

Replacing the #ifdef around the PM functions with __maybe_unused
annotations is the easiest way to make sure this doesn't happen
again. A similar problem happened two months earlier and we
ended up updating the #ifdef, but as it has come back now,
I'd suggest going back to my earlier approach.

Fixes: 9cecca75b5a0 ("usb: dwc3: pci: call _DSM for suspend/resume")
Link: https://patchwork.kernel.org/patch/9318887/
Signed-off-by: Arnd Bergmann <arnd@arndb.de>