regulator: bd718x7: include linux/of.h
Without this header, we get a lengthy build error:

drivers/regulator/bd718x7-regulator.c:364:16: error: implicit declaration of function 'of_match_ptr'; did you mean 'hash_ptr'? [-Werror=implicit-function-declaration]
    .of_match = of_match_ptr("BUCK1"),
                ^~~~~~~~~~~~
                hash_ptr
drivers/regulator/bd718x7-regulator.c:364:16: error: initialization of 'const char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
drivers/regulator/bd718x7-regulator.c:364:16: note: (near initialization for 'bd71847_regulators[0].desc.of_match')
drivers/regulator/bd718x7-regulator.c:364:16: error: initializer element is not constant
drivers/regulator/bd718x7-regulator.c:364:16: note: (near initialization for 'bd71847_regulators[0].desc.of_match')
drivers/regulator/bd718x7-regulator.c:365:23: error: initialization of 'const char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
...

Fixes: 2ece646c90c5 ("regulator: bd718xx: rename bd71837 to 718xx")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>