x86/mpx/selftests: Fix wrong bounds with old _sigfault
I fixed this on my machine and forgot to tell anyone until a
recent bug report. The patch almost get lost. Archiving it here.

For distributions with old userspace header files, the _sigfault
structure is different. mpx-mini-test fails with the following
error:

[root@Purley]# mpx-mini-test_64 tabletest
XSAVE is supported by HW & OS
XSAVE processor supported state mask: 0x2ff
XSAVE OS supported state mask: 0x2ff
 BNDREGS: size: 64 user: 1 supervisor: 0 aligned: 0
  BNDCSR: size: 64 user: 1 supervisor: 0 aligned: 0
starting mpx bounds table test
ERROR: siginfo bounds do not match shadow bounds for register 0

Fix it by using the correct offset of _lower/_upper in _sigfault.
RHEL needs this patch to work.

Fixes: e754aedc26ef ("x86/mpx, selftests: Add MPX self test")
Signed-off-by: Rui Wang <rui.y.wang@intel.com>