md/raid1: Delete three unwanted spaces before increment operators
The script "checkpatch.pl" pointed information out like the following.

ERROR: space prohibited before that '++' (ctx:WxO)

Thus fix the affected source code places.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>