kernel/locking/lockdep.c: mark chainhashentry as __maybe_unused
The newly added chainhashentry() function is only use when
CONFIG_PROVE_LOCKING is enabled, otherwise we get a warning about it.

kernel/locking/lockdep.c:318:26: error: 'chainhashentry' defined but not used [-Werror=unused-function]

We could add another #ifdef or add __maybe_unused to avoid the warning,
this patch picks the second option.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: a33a23c7def8 ("kernel/locking/lockdep.c: make lockdep initialize itself on demand")