perf stat: Potential NULL dereference in print_aggr()
Smatch complains that:

    ./tools/perf/util/stat-display.c:616 print_aggr()
    error: we previously assumed 'config->aggr_map' could be null (see line 607)

Not only that, but it looks like aggr_update_shadow() can Oops if
"config->aggr_get_id" is NULL.  The intent seems to have been to return
if either of these pointers is NULL.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>