intel_punit_ipc: include linux/io.h
After we stop including linux/irq.h implicitly, we don't see linux/io.h
in intel_punit_ipc.c, leading to a build failure:

drivers/platform/x86/intel_punit_ipc.c: In function 'ipc_read_status':
drivers/platform/x86/intel_punit_ipc.c:55:9: error: implicit declaration of function 'readl' [-Werror=implicit-function-declaration]

Add back the include that is clearly needed.

Fixes: 447ae3166702 ("x86: Don't include linux/irq.h from asm/hardirq.h")
Cc: Nicolai Stange <nstange@suse.de>
Cc: Thomas Gleixner <tglx@linutronix.de>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>