staging: pi433: fix Kconfig entry
I ran into a build error with the new pi433 driver and
CONFIG_SPI disabled:

drivers/staging/pi433/pi433_if.o: In function `pi433_probe.part.6':
pi433_if.c:(.text+0x1657): undefined reference to `spi_write_then_read'
drivers/staging/pi433/pi433_if.o: In function `pi433_probe':
pi433_if.c:(.text+0x1d28): undefined reference to `spi_setup'
drivers/staging/pi433/pi433_if.o: In function `pi433_init':

I'm adding a Kconfig dependency on CONFIG_SPI here to avoid that,
and since I spot two cosmetic mistakes in the entry, I'm also
fixing the whitespace and remove the redundant 'default n'.

Fixes: 874bcba65f9a ("staging: pi433: New driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>