mm: hugetlb: replace some macros with inline functions
All users of dissolve_free_huge_page() that ignore the result cause a warning
when CONFIG_HUGETLB_PAGE is disabled:

mm/memory-failure.c: In function 'me_huge_page':
include/linux/hugetlb.h:556:36: error: statement with no effect [-Werror=unused-value]
 #define dissolve_free_huge_page(p) 0

We can avoid this by using an inline function instead of the macro, and I
decided to do the same change for the related helpers as well.

Fixes: mmotm ("mm: hugetlb: soft-offline: dissolve source hugepage after successful migration")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>