device-dax: fix BLOCK dependency
commit ef51042472f5 ("block, dax: move "select DAX" from BLOCK to FS_DAX")
uses get_start_sect() which requires CONFIG_BLOCK

make allnoconfig + dax gives the following:

drivers/dax/super.c: In function 'bdev_dax_pgoff':
drivers/dax/super.c:50:26: error: implicit declaration of function
'get_start_sect' [-Werror=implicit-function-declaration]

Signed-off-by: Fabian Frederick <fabf@skynet.be>