lib-extablec-use-bsearch-library-function-in-search_extable-checkpatch-fixes
WARNING: line over 80 characters
#42: FILE: kernel/extable.c:58:
+	e = search_extable(__start___ex_table, __stop___ex_table - __start___ex_table, addr);

ERROR: "foo * bar" should be "foo *bar"
#94: FILE: lib/extable.c:100:
+	const struct exception_table_entry * _elt = elt;

ERROR: "(foo*)" should be "(foo *)"
#95: FILE: lib/extable.c:101:
+	unsigned long k = *(unsigned long*) key;

WARNING: line over 80 characters
#132: FILE: lib/extable.c:123:
+	return bsearch(&value, first, num, sizeof(struct exception_table_entry), cmp_ex_search);

total: 2 errors, 2 warnings, 100 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/lib-extablec-use-bsearch-library-function-in-search_extable.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Thomas Meyer <thomas@m3y3r.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>