linux-next: Tree for Oct 31 (vboxguest)
On 10/31/18, Randy Dunlap <rdunlap@infradead.org> wrote:
> On 10/30/18 8:59 PM, Stephen Rothwell wrote:
>> Hi all,
>>
>> Please do not add any v4.21/v5.1 code to your linux-next included trees
>> until after the merge window closes.
>>
>> Changes since 20181030:
>>
>
>
> on i386:
>
> ld: drivers/virt/vboxguest/vboxguest_core.o: in function
> `vbg_ioctl_hgcm_call':
> vboxguest_core.c:(.text+0x212b): undefined reference to `vbg_hgcm_call32'
>
>
> Full randconfig file is attached.
>
> Reported-by: Randy Dunlap <rdunlap@infradead.org>

I ran into the same thing, and lots of others like it; they all go back to
the -Og compiler option introduced in commit 94c7dfd01652 ("kernel
hacking: support building kernel with -Og optimization level").

I have patches for most of these, but I'd prefer if we could leave
that patch out of 4.20 for now, and have it in linux-next for merging
into the next merge window, to give us more time to fix up all the
regressions. This particular instance is fixed by the patch below.

Other symptoms caused by the change are tons of 'section mismatch'
warnings for functions that are no longer automatically inlined, and
sprintf format string overflow warnings when gcc fails to propagate
an upper bound on an integer argument that is printed into a fixed
length string.

     Arnd