dmaengine: rcar-dmac: avoid array overflow
Building with CONFIG_UBSAN_SANITIZE_ALL shows this warning:

drivers/dma/sh/rcar-dmac.c: In function 'rcar_dmac_chan_prep_sg':
drivers/dma/sh/rcar-dmac.c:839:29: error: array subscript is above array bounds [-Werror=array-bounds]
  desc->chcr = chcr | chcr_ts[desc->xfer_shift];

As the compiler doesn't know what the xfer_size is, it is impossible
to rule out the array overflow here. As we know that xfer_size
can only be within enum dma_slave_buswidth, this will not overflow
for correct users, and adding a range check will handle the
obscure case and shut up the warning.

Fixes: 87244fe5abdf ("dmaengine: rcar-dmac: Add Renesas R-Car Gen2 DMA Controller (DMAC) driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>