x86, kasan: Fix build failure on KASAN=y && KMEMCHECK=y kernels
Declaration of memcpy is hidden under #ifndef CONFIG_KMEMCHECK.
In asm/efi.h we under #ifdef CONFIG_KASAN we #undef memcpy
thus following happens:

In file included from arch/x86/kernel/setup.c:96:0:
./arch/x86/include/asm/desc.h: In function ‘native_write_idt_entry’:
./arch/x86/include/asm/desc.h:122:2: error: implicit declaration of function ‘memcpy’ [-Werror=implicit-function-declaration]
  memcpy(&idt[entry], gate, sizeof(*gate));
  ^
  cc1: some warnings being treated as errors
  make[2]: *** [arch/x86/kernel/setup.o] Error 1

We will get rid of that #undef in asm/efi.h eventually.
But in the meanwhile move memcpy() declaration out ifdefs
to fix build.

Reported-by: Borislav Petkov <bp@alien8.de>
Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>