x86, relocs: add printf attribute to die()
Adding such an attribute helps to detect errors in the format string at
build time. After doing this, the compiler complains about such issues:

    arch/x86/tools/relocs.c:460:5: error: format specifies type 'int'
    but the argument has type 'Elf64_Xword' (aka 'unsigned long')
    [-Werror,-Wformat]
                                    sec->shdr.sh_size);
                                    ^~~~~~~~~~~~~~~~~
    arch/x86/tools/relocs.c:464:5: error: format specifies type 'int'
    but the argument has type 'Elf64_Off' (aka 'unsigned long')
    [-Werror,-Wformat]
                                    sec->shdr.sh_offset, strerror(errno));
                                    ^~~~~~~~~~~~~~~~~~~

When relocs.c is included by relocs_32.c, sec->shdr.sh_size and
sec->shdr.sh_offset are 32-bit unsigned integers. When the file is
included by relocs_64.c, these expressions are 64-bit unsigned integers.

Introduce a PRIuELF macro to define the right format to use when
printing sh_size and sh_offset values.

While at it, constify the format attribute of die().

Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>