CIFS: use correct format string for size_t
This warning is harmless as size_t is always as wide as 'unsigned long':

fs/cifs/smb2ops.c:2008:245: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'size_t {aka unsigned int}' [-Werror=format=]

Using %zu however is the correct format string that we don't get a warning for.

Fixes: c9d651a5a2fe ("CIFS: Decrypt and process small encrypted packets")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>