power: qcom-smbb: add extcon dependency
Building the smbb driver without extcon results in a link failure:

drivers/power/built-in.o: In function `smbb_usb_valid_handler':
:(.text+0x3190): undefined reference to `extcon_set_cable_state_'
drivers/power/built-in.o: In function `smbb_charger_probe':
:(.text+0x3880): undefined reference to `devm_extcon_dev_allocate'
:(.text+0x3898): undefined reference to `devm_extcon_dev_register'

This adds a Kconfig dependency.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 56d7df8716b2 ("power: Add Qualcomm SMBB driver")