PCI: always build pci-host-common on ARM64
The Thunder PCI host driver is always built, but it relies on pci_host_common_probe,
so we get a link error here:

drivers/pci/host/pci-thunder-pem.c: In function 'thunder_pem_probe':
drivers/pci/host/pci-thunder-pem.c:412:9: error: implicit declaration of function 'pci_host_common_probe';did you mean 'pci_host_bridge_priv'? [-Werror=implicit-function-declaration]

This adds the common file to the existing hack.

Fixes: ca5ab37b19df ("PCI: Explain ARM64 ACPI/MCFG quirk Kconfig and build strategy")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>