iw_cxgb4: fix uninitialized variable plen
Fixes the following smatch warning and few more possible cases:
The patch 94245f4ad9e1: "iw_cxgb4: Support FW write completion WR"
from Aug 2, 2018, leads to the following static checker warning:

	drivers/infiniband/hw/cxgb4/qp.c:651 build_rdma_write_cmpl()
	error: uninitialized symbol 'plen'.

Fixes: 94245f4ad9e ("iw_cxgb4: Support FW write completion WR")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Potnuri Bharat Teja <bharat@chelsio.com>