md/dm-table: Delete an unwanted space in high()
The script "checkpatch.pl" pointed information out like the following.

ERROR: space prohibited after that '-' (ctx:WxW)

Thus fix the affected source code place.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>