kernel: futex: fixed to else and initcall
The include/linux/init.h file have to content; to not used __initcall functions.
I think, needs to be replaced to device_initcall.

device_initcall() or more appropriate function instead of __initcall.

else doesn't need to be used, if should be enclosed in parentheses.
Also, I used checkpatch scripts and fixed to errors.

ERROR: "(foo*)" should be "(foo *)"
ERROR: "foo * bar" should be "foo *bar"
ERROR: "foo * bar" should be "foo *bar"

Signed-off-by: Ozgur Karatas <okaratas@member.fsf.org>