oom_reaper: don't call mmput_async() on uninitialized mm
The change to the oom_reaper to hold a mutex inside __oom_reap_task()
accidentally started calling mmput_async() on the local
mm before that variable got initialized, as reported by gcc
in linux-next:

mm/oom_kill.c: In function '__oom_reap_task':
mm/oom_kill.c:537:2: error: 'mm' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This rearranges the code slightly back to the state before patch
but leaves the lock in place. The error handling in the function
still looks a bit confusing and could probably be improved
but I could not come up with a solution that made me happy
for now.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: mmotm ("oom_reaper: close race with exiting task")