usb: Kconfig: make USB_ULPI_BUS select USB_COMMON
Moving the CONFIG_USB_ULPI_BUS option to the top-level Kconfig file
means that we can enable it without any of the other USB support,
leading to a build error because Kbuild never enters the
drivers/usb/common/ directory without CONFIG_USB_COMMON:

ERROR: "ulpi_unregister_driver" [drivers/phy/phy-tusb1210.ko] undefined!
ERROR: "__ulpi_register_driver" [drivers/phy/phy-tusb1210.ko] undefined!
ERROR: "ulpi_write" [drivers/phy/phy-tusb1210.ko] undefined!

This adds a 'select USB_COMMON' for the symbol, similar to what
we have for related options.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: ad764c49f65a ("usb: Kconfig: move ulpi bus support out of host")