Input: synaptics-rmi4 - make F03 a tristate symbol
If CONFIG_INPUT=m, we get a build error for the rmi4-f03 driver,
added in linux-4.10:

drivers/input/built-in.o: In function `rmi_f03_attention':
rmi_f03.c:(.text+0xcfe0): undefined reference to `serio_interrupt'
rmi_f03.c:(.text+0xd055): undefined reference to `serio_interrupt'
drivers/input/built-in.o: In function `rmi_f03_remove':
rmi_f03.c:(.text+0xd115): undefined reference to `serio_unregister_port'
drivers/input/built-in.o: In function `rmi_f03_probe':
rmi_f03.c:(.text+0xd209): undefined reference to `__serio_register_port'

If we make the driver itself a 'tristate' instead of 'bool' symbol,
Kconfig ensures that it can only be a loadable module in this case,
which avoids the problem.

Fixes: c5e8848fc98e ("Input: synaptics-rmi4 - add support for F03")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>