firmware: bcm47xx_nvram: fix typo / build error
The change to the new __ioread32_copy() helper used the
DIV_ROUND_UP macro incorrectly:

drivers/firmware/broadcom/bcm47xx_nvram.c: In function 'nvram_find_and_copy':
drivers/firmware/broadcom/bcm47xx_nvram.c:110:30: error: macro "DIV_ROUND_UP" requires 2 arguments, but only 1 given

The same commit also changed the behavior of the code in big-endian
builds to no longer perform byte swaps, which looks intentional
but was not part of the patch description.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 31e2fab1c36b ("FIRMWARE: bcm47xx_nvram: Use __ioread32_copy() instead of open-coding")