MIPS: remove duplicate definition
mips defconfig and allmodconfig are failing with the error:

In file included from ../arch/mips/kernel/asm-offsets.c:13:0:
include/linux/sched.h:2656:20: error: conflicting types for 'exit_thread'

exit_thread() was already defined in include/linux/sched.h.

Fixes: 8664c52c094e ("MIPS: Make flush_thread and exit_thread inline.")
Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>