ASoC: qcom: Fix some static checker warnings
This patch fixes below static checker warning plus suggestions from Dan.

sound/soc/qcom/lpass-platform.c:555 lpass_platform_pcm_new()
error: uninitialized symbol 'ret'.

sound/soc/qcom/lpass-platform.c
515          csubstream = pcm->streams[SNDRV_PCM_STREAM_CAPTURE].substream;
516          if (csubstream) {
517                  if (v->alloc_dma_channel)
518                          data->wrdma_ch = v->alloc_dma_channel(drvdata,
519                                              SNDRV_PCM_STREAM_CAPTURE);
520
521                  if (IS_ERR_VALUE(data->wrdma_ch))
522                          goto capture_alloc_err;

 wrdma_ch is an int so this should just be:

			if (data->wrdma_ch < 0) {
				ret = data->wrdma_ch;
				goto capture_alloc_err;
			}

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>