drivers/clk/uniphier/clk-uniphier.h: fix build with old gcc
gcc-4.4.4 (at least) has issues with anon uniion initializers.  Work
around this.

drivers/clk/uniphier/clk-uniphier-sys.c:45: error: unknown field 'factor' specified in initializer
drivers/clk/uniphier/clk-uniphier-sys.c:45: error: unknown field 'parent_name' specified in initializer
drivers/clk/uniphier/clk-uniphier-sys.c:45: warning: missing braces around initializer
drivers/clk/uniphier/clk-uniphier-sys.c:45: warning: (near initialization for 'uniphier_sld3_sys_clk_data[0].<anonymous>.cpugear')
drivers/clk/uniphier/clk-uniphier-sys.c:45: error: unknown field 'mult' specified in initializer
drivers/clk/uniphier/clk-uniphier-sys.c:45: warning: excess elements in union initializer
drivers/clk/uniphier/clk-uniphier-sys.c:45: warning: (near initialization for 'uniphier_sld3_sys_clk_data[0].<anonymous>')
drivers/clk/uniphier/clk-uniphier-sys.c:45: error: unknown field 'div' specified in initializer
drivers/clk/uniphier/clk-uniphier-sys.c:45: warning: excess elements in union initializer
...

Fixes: 734d82f4a678e897 ("clk: uniphier: add core support code for UniPhier clock driver")
Cc: Masahiro Yamada <yamada.masahiro@socionext.com>
Cc: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>