drm/amd: Compile fix for amdgpu_dm.c
Fix compilation issue with CONFIG_DRM_AMDGPU on:
drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c: In function ‘amdgpu_dm_mode_config_init’:
drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:1666:30: error: passing argument 1 of ‘drm_atomic_private_obj_init’ from incompatible pointer type

Fixes: b962a12050a3 ("drm/atomic: integrate modeset lock with private objects")
Cc: Rob Clark <robdclark@gmail.com>
Cc: Boris Brezillon <boris.brezillon@bootlin.com>
Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
Cc: Tomi Sarvela <tomi.p.sarvela@intel.com>
Signed-off-by: Mika Kuoppala <mika.kuoppala@linux.intel.com>