powerpc/powernv/idle: Put pnv_cpu_offline behind HOTPLUG_CPU
In commit 900612315788 ("powerpc/powernv/smp: Add busy-wait loop as fall back
for CPU-Hotplug") the idle code uses generic_check_cpu_restart(), but that
function is not available when CONFIG_HOTPLUG_CPU is disabled.

arch/powerpc/platforms/powernv/idle.c: In function ‘pnv_cpu_offline’:
arch/powerpc/platforms/powernv/idle.c:286:11: error: implicit declaration of
function ‘generic_check_cpu_restart’ [-Werror=implicit-function-declaration]
   while (!generic_check_cpu_restart(cpu)) {
           ^~~~~~~~~~~~~~~~~~~~~~~~~

The callers of pnv_cpu_offline are behind CONFIG_HOTPLUG_CPU, so fix the build
error by putting this code behind the same gard.

Fixes: 900612315788 ("powerpc/powernv/smp: Add busy-wait loop as fall back for CPU-Hotplug").
Cc: <stable@vger.kernel.org> # 4.12
Signed-off-by: Joel Stanley <joel@jms.id.au>