linux-next: Tree for Nov 1 (lightnvm)
On 11/02/2015 04:37 PM, Jens Axboe wrote:
> On 11/02/2015 05:43 AM, Matias Bjorling wrote:
>> On 11/02/2015 02:16 AM, Randy Dunlap wrote:
>>> On 11/01/15 08:53, Stephen Rothwell wrote:
>>>> Hi all,
>>>>
>>>> I start again a day early, and this is how you all repay me? ;-)
>>>>
>>>> Changes since 20151022:
>>>>
>>>
>>> on i386:
>>>
>>> ../include/linux/lightnvm.h:143:4: error: width of 'resved' exceeds
>>> its type
>>>
>>> # CONFIG_LBDAF is not set
>>>
>>>
>>
>> Thanks Randy.
>>
>> Jens, how would you like to receive the patch? (I've currently attached
>> it in this mail)
>
> If it really needs to be 64-bit regardless of LBDAF, just make it a u64
> instead of typedef'ing some new ppa_t that everybody would have to look up.
>

Sure, patch attached.

From a40f984025a73cf4bf3552513504ba60a7cb58a0 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Matias=20Bj=C3=B8rling?= <m@bjorling.me>
Date: Mon, 2 Nov 2015 17:12:27 +0100
Subject: [PATCH] lightnvm: refactor phys addrs type to u64
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

For cases where CONFIG_LBDAF is not set. The struct ppa_addr exceeds its
type on 32 bit architectures. ppa_addr requires a 64bit integer to hold
the generic ppa format. We therefore refactor it to u64 and
replaces the sector_t usages with u64 for physical addresses.

Signed-off-by: Matias Bjørling <m@bjorling.me>