staging: rtl8192u: ieee80211: Fix space required after }.
This was reported by checkpatch.pl:
ERROR: space required after that close brace '}'

Signed-off-by: Valerio Genovese <valerio.click@gmail.com>