pci: stub out some MSI functions
A bug fix to the MSIx handling in vfio added references
to functions that may not be defined if MSI is disabled in the kernel,
resulting in this link error:

drivers/built-in.o: In function `vfio_msi_set_vector_signal':
:(.text+0x450808): undefined reference to `get_cached_msi_msg'
:(.text+0x45080c): undefined reference to `write_msi_msg'

When MSI is disabled, we should never get into this code path,
so by adding stub implementations we can avoid the link error
without causing any other changes.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: b8f02af096b1 ("vfio/pci: Restore MSIx message prior to enabling")
Link: http://lists.infradead.org/pipermail/linux-arm-kernel/2014-October/294293.html