aio: always provide ki_destruct_fn callback pointer
The newly added synchronous openat support in AIO adds a ki_destruct_fn
function pointer to struct aio_kiocb inside of a CONFIG_AIO_THREAD check
but calls it unconditionally, leading to a build error:

fs/aio.c: In function 'kiocb_free':
fs/aio.c:1101:9: error: 'struct aio_kiocb' has no member named 'ki_destruct_fn'
  if (req->ki_destruct_fn)
         ^~
fs/aio.c:1102:6: error: 'struct aio_kiocb' has no member named 'ki_destruct_fn'

This moves the declaration outside of the #ifdef, assuming that we want
to call this regardless.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 5d3d80fcf992 ("aio: add support for in-submit openat")