misc: pci_endpoint_test: select CONFIG_CRC32
Without CRC32, we get this link error:

pci_endpoint_test.c:(.text+0x2509e): undefined reference to `crc32_le'

Fixes: 58c89c8aa0e8 ("misc: Add host side PCI driver for PCI test function device")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>