zmalloc: hide unused lock_zspage
Making lock_zspage() static revealed that it is unused in some confiurations:

mm/zsmalloc.c:931:13: error: 'lock_zspage' defined but not used [-Werror=unused-function]

I considered moving it into the same #ifdef that hides its user, but
it seems better to keep it close to trylock_zspage() etc, so this
marks it __maybe_unused() to let the compiler drop it without warning
about it.

Fixes: 0de664ada6b6 ("mm/zsmalloc.c: make several functions and a struct static")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>