phy: add HAS_IOMEM/OF_MDIO dependencies to MDIO_OCTEON
Ran into this on UML:

drivers/built-in.o: In function `octeon_mdiobus_probe':
drivers/net/phy/mdio-octeon.c:295: undefined reference to `devm_ioremap'
drivers/net/phy/mdio-octeon.c:320: undefined reference to `of_mdiobus_register'
collect2: error: ld returned 1 exit status

devm_ioremap() is defined only when HAS_IOMEM is selected.

of_mdiobus_register() is defined only when OF_MDIO is selected.

Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
Cc: Florian Fainelli <f.fainelli@gmail.com>
Cc: netdev@vger.kernel.org