mm/debug-pagealloc: add missing debug_pagealloc_enabled
The change to move the pagealloc logic broke the slab allocator
check when it's disabled at compile time:

mm/slab.c: In function 'is_debug_pagealloc_cache':
mm/slab.c:1608:29: error: implicit declaration of function 'debug_pagealloc_enabled' [-Werror=implicit-function-declaration]

This adds an inline helper to get it to work again.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 0a244aea1a61 ("mm/slab: clean up DEBUG_PAGEALLOC processing code")