EDAC, pnd2_edac: fix build error without CONFIG_EDAC_DEBUG
Calling into functions inside of the #ifdef causes an obvious compile error:

drivers/edac/pnd2_edac.c: In function 'pnd2_init':
drivers/edac/pnd2_edac.c:1521:2: error: implicit declaration of function 'setup_pnd2_debug'; did you mean 'setup_log_buf'? [-Werror=implicit-function-declaration]
drivers/edac/pnd2_edac.c: In function 'pnd2_exit':
drivers/edac/pnd2_edac.c:1529:2: error: implicit declaration of function 'teardown_pnd2_debug' [-Werror=implicit-function-declaration]

This removes the #ifdef and instead uses an equivalent IS_ENABLED() check
so the compiler can silently drop the functions but still build-test them
and not need an #ifdef.

Fixes: 5c71ad17f97e ("EDAC, pnd2_edac: Add new EDAC driver for Intel SoC platforms")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>