sunxi-irq: Fix Kconfig dependency on GENERIC_IRQ_CHIP
The Allwinner NMI irqchip driver requires GENERIC_IRQ_CHIP, but
we can't select it directly, because there is no specific Kconfig entry
for the driver. Compiling this NMI driver with certain arm64
configurations thus fails due to the missing dependency:

drivers/built-in.o: In function `sunxi_sc_nmi_set_type':
drivers/irqchip/irq-sunxi-nmi.c:114: undefined reference to `irq_setup_alt_chip'
drivers/built-in.o: In function `irq_domain_add_linear':
include/linux/irqdomain.h:253: undefined reference to `irq_generic_chip_ops'
include/linux/irqdomain.h:253: undefined reference to `irq_generic_chip_ops'
drivers/built-in.o: In function `sunxi_sc_nmi_irq_init':
drivers/irqchip/irq-sunxi-nmi.c:146: undefined reference to `irq_alloc_domain_generic_chips'
drivers/irqchip/irq-sunxi-nmi.c:161: undefined reference to `irq_get_domain_generic_chip'
drivers/irqchip/irq-sunxi-nmi.c:170: undefined reference to `irq_gc_mask_clr_bit'
drivers/irqchip/irq-sunxi-nmi.c:171: undefined reference to `irq_gc_mask_set_bit'
drivers/irqchip/irq-sunxi-nmi.c:172: undefined reference to `irq_gc_ack_set_bit'
drivers/irqchip/irq-sunxi-nmi.c:170: undefined reference to `irq_gc_mask_clr_bit'

Add separate Kconfig options for both Allwinner specific irqchip
drivers and select GENERIC_IRQ_CHIP for the NMI driver.
The older sun4i IRQ driver only gets selected when support for these
specific SoCs is compiled, while the NMI driver is selected for all
Allwinner SoCs (copying the current behaviour and covering future SoCs
automatically).

Reported-by: Suzuki K Poulose <Suzuki.Poulose@arm.com>
Signed-off-by: Andre Przywara <andre.przywara@arm.com>