MIPS: fix build failure
While building for mips defconfig the build failed with the error:
In function 'create_elf_tables':
arch/mips/include/asm/elf.h:425:14: error:
'AT_SYSINFO_EHDR' undeclared (first use in this function)

AT_SYSINFO_EHDR is defined in uapi/asm/auxvec.h which was not included
here.

Fixes: c1fb442ade67 ("MIPS: Initial implementation of a VDSO")
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>