linux-next: Tree for Nov 1 (lightnvm)
On 11/02/2015 02:16 AM, Randy Dunlap wrote:
> On 11/01/15 08:53, Stephen Rothwell wrote:
>> Hi all,
>>
>> I start again a day early, and this is how you all repay me? ;-)
>>
>> Changes since 20151022:
>>
>
> on i386:
>
> ../include/linux/lightnvm.h:143:4: error: width of 'resved' exceeds its type
>
> # CONFIG_LBDAF is not set
>
>

Thanks Randy.

Jens, how would you like to receive the patch? (I've currently attached
it in this mail)

From bc2462b86467be52711f74ab1cb6c5f75819e58d Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Matias=20Bj=C3=B8rling?= <m@bjorling.me>
Date: Mon, 2 Nov 2015 05:42:38 +0100
Subject: [PATCH] lightnvm: refactor phys addrs type to ppa_t
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

For cases where CONFIG_LBDAF is not set. The ppa_addr exceeds its type
on 32 bit architectures. ppa_addr requires a 64bit integer to hold the
generic ppa format. We therefore typedef ppa_t to u64 and replaces
the sector_t usages with ppa_t for physical addresses.

Signed-off-by: Matias Bjørling <m@bjorling.me>