staging: pi433: codestyle space required
This patch fixes the following checkpatch.pl error:

ERROR: spaces required around that '+=' (ctx:WxV) +
                           position +=temp;
       ^

Signed-off-by: Oliver Graute <oliver.graute@gmail.com>