ALSA: snd-usb-line6 depends on CONFIG_SND_HWDEP
ALSA - snd-usb-line6 depends on CONFIG_SND_HWDEP

ERROR: "snd_hwdep_new" [sound/usb/line6/snd-usb-line6.ko] undefined!
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1

Signed-off-by: Valdis Kletnieks <valdis.kletnieks@vt.edu>