s390: fix build failure
s390 defconfig fails with the error:
ERROR: "phys_to_pfn_t" [drivers/s390/block/dcssblk.ko] undefined!

We need CONFIG_HAS_IOMEM for phys_to_pfn_t() and for that we need to
have CONFIG_PCI.

Fixes: bfac97e7b361 ("mm, dax, pmem: introduce pfn_t")
Cc: Dan Williams <dan.j.williams@intel.com>
Cc: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>