ARM: OMAP2+: Prepare to pass auxdata for smartreflex
* kbuild test robot <lkp@intel.com> [180226 08:39]:
> >> arch/arm/mach-omap2/pdata-quirks.c:517:36: error: array type has incomplete element type 'struct omap_sr_data'
>     struct omap_sr_data __maybe_unused omap_sr_pdata[OMAP_SR_NR];
>                                        ^~~~~~~~~~~~~
>
> vim +517 arch/arm/mach-omap2/pdata-quirks.c
>
>    516
>  > 517	struct omap_sr_data __maybe_unused omap_sr_pdata[OMAP_SR_NR];
>    518

Thanks kbt. Looks like it needs to be out of the ifdef
CONFIG_POWER_AVS_OMAP in include/linux/power/smartreflex.h.

Updated patch below.

Regards,

Tony

8< ---------------------
From tony Mon Sep 17 00:00:00 2001
From: Tony Lindgren <tony@atomide.com>
Date: Thu, 22 Feb 2018 13:57:30 -0800
Subject: [PATCH] ARM: OMAP2+: Prepare to pass auxdata for smartreflex

We are still initializing smartreflex with platform data using
omap_device_build(). We can instead pass the platform data in
with auxdata in pdata-quirks.c and make the driver use that
in later patches.

Note that we cannot enable the auxdata use yet, this is done
in the last patch of the series.

Signed-off-by: Tony Lindgren <tony@atomide.com>