staging: vt6656: rf.c: alignment should match open parentheses
Resolving 5 instances of checkpatch error/warning statements generated
due to:
ERROR: code indent should use tabs where possible
CHECK: Alignment should match open parenthesis

Signed-off-by: Matthew Giassa <matthew@giassa.net>