PCI: rcar: select PCI_MSI_IRQ_DOMAIN
The R-CAR PCIe driver requires the use of irq domains for its
MSI code:

drivers/pci/host/pcie-rcar.c: In function 'rcar_pcie_msi_irq':
drivers/pci/host/pcie-rcar.c:635:9: error: implicit declaration of function 'irq_find_mapping' [-Werror=implicit-function-declaration]
drivers/pci/host/pcie-rcar.c: In function 'rcar_msi_setup_irq':
drivers/pci/host/pcie-rcar.c:666:8: error: implicit declaration of function 'irq_create_mapping' [-Werror=implicit-function-declaration]
drivers/pci/host/pcie-rcar.c: In function 'rcar_pcie_enable_msi':
drivers/pci/host/pcie-rcar.c:725:16: error: implicit declaration of function 'irq_domain_add_linear' [-Werror=implicit-function-declaration]
drivers/pci/host/pcie-rcar.c:725:14: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
  msi->domain = irq_domain_add_linear(pcie->dev->of_node, INT_PCI_MSI_NR,
              ^
drivers/pci/host/pcie-rcar.c:762:2: error: implicit declaration of function 'irq_domain_remove' [-Werror=implicit-function-declaration]

This ensures that the feature is always enabled by adding a
Kconfig select statement. This is not consistent with what the
other drivers do at the moment, but I have another patch that
changes them to do it like this one, which is more logical.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>