make of_usb_get_dr_mode_by_phy helper inline
The recently added of_usb_get_dr_mode_by_phy function causes a link error
when CONFIG_OF is disabled:

drivers/usb/common/built-in.o: In function `of_usb_get_dr_mode_by_phy':
include/linux/usb/of.h:23: multiple definition of `of_usb_get_dr_mode_by_phy'
drivers/usb/dwc3/built-in.o:/git/arm-soc/obj-tmp/../include/linux/usb/of.h:23: first defined here

This patch marks the dummy stub implementation of the function as
'static inline' so we don't get duplicate definitions when the
header gets included multiple times.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 98bfb3946695 ("usb: of: add an api to get dr_mode by the phy node")