nvdimm: avoid bogus -Wmaybe-uninitialized warning
Removing the btt_rw_page/pmem_rw_page functions had a surprising
side-effect of introducing a false-positive warning in another
function, due to changed inlining decisions in gcc:

In file included from drivers/nvdimm/pmem.c:36:0:
drivers/nvdimm/pmem.c: In function 'pmem_make_request':
drivers/nvdimm/nd.h:407:2: error: 'start' may be used uninitialized in this function [-Werror=maybe-uninitialized]
drivers/nvdimm/pmem.c:174:16: note: 'start' was declared here
In file included from drivers/nvdimm/btt.c:27:0:
drivers/nvdimm/btt.c: In function 'btt_make_request':
drivers/nvdimm/nd.h:407:2: error: 'start' may be used uninitialized in this function [-Werror=maybe-uninitialized]
drivers/nvdimm/btt.c:1202:16: note: 'start' was declared here

The problem is that gcc fails to track the value of the 'do_acct'
variable here and has to read it back from stack, but it does
remember that 'start' may be uninitialized sometimes.

This shuts up the warning by making nd_iostat_start() always
initialize the 'start' variable. In those cases that gcc successfully
tracks the state of the variable, this will have no effect.

Fixes: 503a5e89b1de ("drivers/nvdimm/btt.c: remove btt_rw_page()")
Fixes: 58100d6e735e ("drivers/nvdimm/pmem.c: remove pmem_rw_page()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>