ceph: quota: fix null pointer dereference in quota check
This patch fixes a possible null pointer dereference in
check_quota_exceeded, detected by the static checker smatch, with the
following warning:

    fs/ceph/quota.c:240 check_quota_exceeded()
     error: we previously assumed 'realm' could be null (see line 188)

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Link: https://lkml.kernel.org/n/20181101065318.2cylxol6d444nzeu@kili.mountain
Fixes: b7a2921765cf ("ceph: quota: support for ceph.quota.max_files")
Signed-off-by: Luis Henriques <lhenriques@suse.com>