clk: ti: divider: try to fix ti_clk_register_divider
The newly introduced function is entirely bogus as I found when looking
at this warning:

drivers/clk/ti/divider.c: In function 'ti_clk_register_divider':
drivers/clk/ti/divider.c:460:8: error: 'reg' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Treating a 'u32' variable as a structure leads to a stack overflow here,
and the register address we pass down is never initialized.

As the code in its original form makes no sense, I can only guess what
the intention was, and change it to take the address from div->reg.ptr
instead.

Fixes: d96f774b2538 ("clk: ti: divider: add support for legacy divider init")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>