procfs: use inline functions instead of macros for proc_create_single_data stub
The procfs interface changes caused one warning in afs for
a now unused function:

fs/afs/proc.c:818:12: error: 'afs_proc_stats_show' defined but not used [-Werror=unused-function]
 static int afs_proc_stats_show(struct seq_file *m, void *v)

This can be avoided by using an inline function instead of a macro
to reference it, so now the compiler can silently drop the function
after seeing that there is a reference but that it is never called.

Unfortunately, this change triggers another warning where a function
is hidden and now unexpectedly referenced:

drivers/mtd/mtdcore.c: In function 'init_mtd':
drivers/mtd/mtdcore.c:1878:48: error: 'mtd_proc_show' undeclared (first use in this function); did you mean 'mtd_name_show'?

It seems nicer to keep using the inline function and removing the #ifdef
here than to add an #ifdef around every single function we pass into
proc_create_single_data(), so I'm removing the #ifdef here.

After a few hundred randconfig builds, this was the only instance
I found that caused a problem.

Fixes: 353861cf0594 ("afs: simplify procfs code")
Fixes: 3f3942aca6da ("proc: introduce proc_create_single{,_data}")
Cc: Christoph Hellwig <hch@lst.de>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>