nwflash: use no_seek_end_llseek_size
The recently introduced no_seek_end_llseek was wrong, it should
be no_seek_end_llseek_size:

drivers/char/nwflash.c: In function 'flash_llseek':
drivers/char/nwflash.c:280:8: error: too many arguments to function 'no_seek_end_llseek'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 00c1b53c0e61 ("new helpers: no_seek_end_llseek{,_size}()")