pci: mvebu: add MVEBU_MBUS dependency
Enabling the PCI_MVEBU driver for compile testing caused a build failure
on ARM randconfig builds:

drivers/pci/host/pci-mvebu.c: In function 'mvebu_pcie_del_windows':
drivers/pci/host/pci-mvebu.c:341:3: error: implicit declaration of function 'mvebu_mbus_del_window'; did you mean 'mvebu_pcie_del_windows'? [-Werror=implicit-function-declaration]
   mvebu_mbus_del_window(base, sz);
   ^~~~~~~~~~~~~~~~~~~~~
   mvebu_pcie_del_windows
drivers/pci/host/pci-mvebu.c: In function 'mvebu_pcie_add_windows':
drivers/pci/host/pci-mvebu.c:364:9: error: implicit declaration of function 'mvebu_mbus_add_window_remap_by_id'; did you mean 'mvebu_pcie_add_windows'? [-Werror=implicit-function-declaration]
   ret = mvebu_mbus_add_window_remap_by_id(target, attribute, base,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         mvebu_pcie_add_windows
drivers/pci/host/pci-mvebu.c: In function 'mvebu_pcie_probe':
drivers/pci/host/pci-mvebu.c:1209:2: error: implicit declaration of function 'mvebu_mbus_get_pcie_mem_aperture'; did you mean 'mvebu_mbus_get_io_win_info'? [-Werror=implicit-function-declaration]
drivers/pci/host/pci-mvebu.c:1215:2: error: implicit declaration of function 'mvebu_mbus_get_pcie_io_aperture'; did you mean 'mvebu_mbus_get_io_win_info'? [-Werror=implicit-function-declaration]

The problem is that the mbus helper functions are not declared in the
header. There are two ways of solving this: we can change the header
to provide empty stub functions for CONFIG_MVEBU_MBUS=n, or we can
add back the dependency here.

I picked the second option since that is simpler, but it somewhat
defeats the purpose of the original patch because we still cannot
compile test on other platforms this way.

Fixes: 51bc085d6454 ("PCI: Improve host drivers compile test coverage")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>