rcuperf: fix duplicate struct initializer
Building with "make W=1" shows a set of new warnings in the rcuperf code:

kernel/rcu/rcuperf.c:282:11: error: initialized field overwritten [-Werror=override-init]
  .async  = srcu_call_rcu,
kernel/rcu/rcuperf.c:282:11: note: (near initialization for 'sched_ops.async')
kernel/rcu/rcuperf.c:283:16: error: initialized field overwritten [-Werror=override-init]
  .gp_barrier = srcu_rcu_barrier,
kernel/rcu/rcuperf.c:283:16: note: (near initialization for 'sched_ops.gp_barrier')
kernel/rcu/rcuperf.c:313:11: error: initialized field overwritten [-Werror=override-init]
  .async  = call_rcu_tasks,
kernel/rcu/rcuperf.c:313:11: note: (near initialization for 'tasks_ops.async')
kernel/rcu/rcuperf.c:314:16: error: initialized field overwritten [-Werror=override-init]
  .gp_barrier = rcu_barrier_tasks,
kernel/rcu/rcuperf.c:314:16: note: (near initialization for 'tasks_ops.gp_barrier')

This appears to be a copy-paste bug, so we can remove the extranous copy.

Fixes: f743d20f2cc6 ("rcuperf: Add ability to performance-test call_rcu() and friends")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>