uapi: fix linux/sched/types.h userspace compilation errors
Consistently use types provided by <linux/types.h> to fix the following
linux/sched/types.h userspace compilation errors:

/usr/include/linux/sched/types.h:57:2: error: unknown type name 'u32'
  u32 size;
/usr/include/linux/sched/types.h:59:2: error: unknown type name 'u32'
  u32 sched_policy;
/usr/include/linux/sched/types.h:60:2: error: unknown type name 'u64'
  u64 sched_flags;
/usr/include/linux/sched/types.h:63:2: error: unknown type name 's32'
  s32 sched_nice;
/usr/include/linux/sched/types.h:66:2: error: unknown type name 'u32'
  u32 sched_priority;
/usr/include/linux/sched/types.h:69:2: error: unknown type name 'u64'
  u64 sched_runtime;
/usr/include/linux/sched/types.h:70:2: error: unknown type name 'u64'
  u64 sched_deadline;
/usr/include/linux/sched/types.h:71:2: error: unknown type name 'u64'
  u64 sched_period;

Fixes: e2d1e2aec572 ("sched/headers: Move various ABI definitions to <uapi/linux/sched/types.h>")
Cc: stable@vger.kernel.org # v4.12
Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>