powerpc: allow compiling with GENERIC_MSI_IRQ
This allows building powerpc with the GENERIC_MSI_IRQ Kconfig
by enabling the asm-generic msi.h in Kbuild. Without this,
there's a compilation error [1] because powerpc, as most arches,
doesn't provide an asm/msi.h.

[1] In file included from ./include/linux/kvm_host.h:20:0,
                 from ./arch/powerpc/include/asm/kvm_ppc.h:30,
                 from arch/powerpc/kernel/dbell.c:20:
./include/linux/msi.h:195:21: fatal error: asm/msi.h: No such file or directory

Signed-off-by: Laurentiu Tudor <laurentiu.tudor@nxp.com>