rtc: isl12057: remove unused variables
A cleanup patch introduced a harmless warning about now unused local variables:

drivers/rtc/rtc-isl12057.c: In function 'isl12057_rtc_read_alarm':
drivers/rtc/rtc-isl12057.c:249:26: error: unused variable 'alarm_secs' [-Werror=unused-variable]
  unsigned long rtc_secs, alarm_secs;
                          ^~~~~~~~~~
drivers/rtc/rtc-isl12057.c:249:16: error: unused variable 'rtc_secs' [-Werror=unused-variable]
  unsigned long rtc_secs, alarm_secs;
                ^~~~~~~~
drivers/rtc/rtc-isl12057.c:248:18: error: unused variable 'rtc_tm' [-Werror=unused-variable]
  struct rtc_time rtc_tm, *alarm_tm = &alarm->time;
                  ^~~~~~

This removes the variables to shut up those warnings.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 4e30a585a343 ("rtc: isl12057: let the rtc core interpret the partial alarm")