overlayfs: include linux/pagemap.h for PAGE_CACHE_SIZE
The overlayfs has started enforcing a maximum file size, but is missing
the header file that defines the PAGE_CACHE_SIZE constant in some
configurations.

fs/overlayfs/super.c: In function 'ovl_fill_super':
fs/overlayfs/super.c:939:29: error: 'PAGE_CACHE_SIZE' undeclared (first use in this function)

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 7b1746cac878 ("ovl: setattr: check permissions before copy-up")
Cc: <stable@vger.kernel.org>