regulator: qcom-saw: avoid uninitialized variable warning
gcc cannot know that a for_each_possible_cpu() loop always executes
at least once, so it warns about the use of the "found" variable
in qcom_saw_regulator_probe:

drivers/regulator/qcom_saw-regulator.c: In function 'qcom_saw_regulator_probe':
drivers/regulator/qcom_saw-regulator.c:154:5: error: 'found' is used uninitialized in this function [-Werror=uninitialized]

This adds an explicit initialization to avoid the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 18bba3b50355 ("regulator: qcom-saw: Add support for SAW regulators")