block: partitions: mac: Mark mac_fix_string() as __maybe_unused
The function is only used when CONFIG_PPC_PMAC=y. Adding the attribute
fixes the following warning when building with clang:

block/partitions/mac.c:22:20: error: unused function 'mac_fix_string'
    [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>