ALSA: unhide snd_soc_new_compress() declaration
My randconfig build setup came across a new build failure today:

sound/soc/soc-topology.c: In function 'soc_tplg_dai_create':
sound/soc/soc-topology.c:1758:27: error: 'snd_soc_new_compress' undeclared (first use in this function); did you mean 'snd_soc_compr_ops'?
   dai_drv->compress_new = snd_soc_new_compress;

Simply making that prototype visible again fixes the build failure
for me, though I'm not exactly sure why we don't get a link
error now.

The reference to snd_soc_new_compress() was added a few weeks
ago and seems to have caused the problem.

Fixes: 5db6aab6f36f ("ASoC: topology: Add support for compressed PCMs")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>