MIPS: ath79: fix build failure
The ath79_defconfig build of mips was faling with the errors:

arch/mips/ath79/setup.c: In function 'plat_mem_setup':
arch/mips/ath79/setup.c:226:20: error: invalid storage class for function 'ath79_of_plat_time_init'
 static void __init ath79_of_plat_time_init(void)
                    ^
arch/mips/ath79/setup.c:226:1: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 static void __init ath79_of_plat_time_init(void)
 ^
arch/mips/ath79/setup.c:284:20: error: invalid storage class for function 'ath79_setup'
 static  __init int ath79_setup(void)
                    ^
arch/mips/ath79/setup.c:299:1: error: initializer element is not constant
 arch_initcall(ath79_setup);

It turns out to be a simple error of a missed closing brace.

Fixes: f63ba725caa7 ("MIPS: ath79: Disable platform code for OF boards.")
Cc: Antony Pavlov <antonynpavlov@gmail.com>
Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>