dmaengine: imx-sdma: fix merge conflict
The sdma_handle_channel_loop() function was modified in one patch
and removed in another, and the merge between those patches left
an unused function in place:

drivers/dma/imx-sdma.c:673:13: error: 'sdma_handle_channel_loop' defined but not used [-Werror=unused-function]

This removes it again.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 48dc77e2d4fc ("dmaengine: imx-sdma: convert callback to helper function")
Fixes: 15f30f513111 ("dmaengine: imx-sdma - reduce transfer latency for DMA cyclic clients")