KVM: s390: fix build failure
etr_ptff definitions are moved and renamed but we missed updating them
here and as a result s390 defconfig and allmodconfig was failing with
the error:
arch/s390/kvm/kvm-s390.c:230:45: error: 'ETR_PTFF_QAF' undeclared

Fixes: cc8f94656487 ("s390/time: move PTFF definitions")
Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>