kernel/stop_machine: remove HOTPLUG_CPU dependency
A number of things rely on stop_machine, not just HOTPLUG_CPU,
as got apparent, when we stopped building the functions for all
SMP configurations:

arch/arm/kernel/built-in.o: In function `patch_text':
arch/arm/kernel/patch.c:127: undefined reference to `stop_machine'
arch/arm/probes/built-in.o: In function `kprobes_remove_breakpoint':
arch/arm/probes/kprobes/core.c:184: undefined reference to `stop_machine'
arch/arm/probes/kprobes/core.c:184: undefined reference to `stop_machine'
kernel/built-in.o: In function `timekeeping_notify':
kernel/time/timekeeping.c:1096: undefined reference to `stop_machine'
mm/built-in.o: In function `build_all_zonelists':

This restores the original behavior by always compiling the stop_machine
function.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 64dab25b058c ("kernel/stop_machine.c: remove CONFIG_SMP dependencies")