vsprintf: fix build warning
The have_filled_random_ptr_key variable was recently removed,
but then reappeared with another patch, presumably after an
incorrect rebase:

lib/vsprintf.c:1668:13: error: 'have_filled_random_ptr_key' defined but not used [-Werror=unused-variable]

This removes it again.

Fixes: 85f4f12d5139 ("vsprintf: Replace memory barrier with static_key for random_ptr_key update")
Fixes: bfe80ed3d7c7 ("vsprintf: add command line option debug_boot_weak_hash")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>