KVM: arm/arm64: arch_timer: remove unused error handling
A cleanup removed the call to create_singlethread_workqueue(), but did not
remove the code that was used in case it failed:

virt/kvm/arm/arch_timer.c: In function 'kvm_timer_hyp_init':
virt/kvm/arm/arch_timer.c:457:1: error: label 'out_free' defined but not used [-Werror=unused-label]

This removes the now dead code too.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 3706feacd007 ("KVM: Remove deprecated create_singlethread_workqueue")