blk-rq-qos: always make debugfs_attr available
We fail building if !CONFIG_BLK_DEBUG_FS:

   In file included from block/bio.c:35:
   block/blk-rq-qos.h: In function 'rq_qos_add':
>> block/blk-rq-qos.h:101:15: error: 'struct rq_qos_ops' has no member named 'debugfs_attrs'
     if (rqos->ops->debugfs_attrs)
                  ^~

since we only make that member available with BLK_DEBUG_FS. Just make
it always available, since it doesn't take up any space if BLK_DEBUG_FS
is turned off anyway.

Fixes: 8e4ceb9ed1de ("blk-mq-debugfs: support rq_qos")
Signed-off-by: Jens Axboe <axboe@kernel.dk>