mmc: dw_mmc should depend on COMMON_CLK
This patch fix the following build failure on m68k:
ERROR: "clk_set_rate" [drivers/mmc/host/dw_mmc.ko] undefined!

Signed-off-by: Corentin Labbe <clabbe@baylibre.com>