KVM: Eliminate unused variable warning on uniprocessor configs
Commit 7a97cec26b94 ("KVM: mark requests that need synchronization",
2017-04-27) added a variable 'wait' to kvm_make_all_cpus_request(),
which is only consumed in calls to smp_call_function_many.  When the
kernel is compiled with CONFIG_SMP=n, smp_call_function_many() turns
into a macro which doesn't use the 'wait' argument, leading to a
warning about the variable 'wait' being unused:

/home/paulus/kernel/kvm/arch/powerpc/kvm/../../../virt/kvm/kvm_main.c: In function ‘kvm_make_all_cpus_request’:
/home/paulus/kernel/kvm/arch/powerpc/kvm/../../../virt/kvm/kvm_main.c:195:7: error: unused variable ‘wait’ [-Werror=unused-variable]
  bool wait = req & KVM_REQUEST_WAIT;
       ^

Since PPC compiles everything that gets built under arch/powerpc
with -Werror by default, this causes the build to fail.

This fixes it by adding a __maybe_unused annotation to the
declaration of 'wait'.

Signed-off-by: Paul Mackerras <paulus@ozlabs.org>