binfmt_em86: load_em86: Remove unused i_arg variable and constify i_name
i_arg is not used at all therefore remove it. This also prevents
an error in case -Werror=i-Werror=incompatible-pointer-types
is enabled:

fs/binfmt_em86.c:73:35: error: passing argument 2 of ‘copy_strings_kernel’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   retval = copy_strings_kernel(1, &i_arg, bprm);

The second error would come from i_name which is defined as char pointer
without the const attribute.

fs/binfmt_em86.c:71:34: error: passing argument 2 of ‘copy_strings_kernel’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  retval = copy_strings_kernel(1, &i_name, bprm);

While at it, check the remove_arg_zero return value too.

fs/binfmt_em86.c:68:2: warning: ignoring return value of ‘remove_arg_zero’, declared with attribute warn_unused_result [-Wunused-result]
  remove_arg_zero(bprm);
  ^

Signed-off-by: Daniel Wagner <daniel.wagner@bmw-carit.de>