iio: adc: STM32_DFSDM_ADC should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "bad_dma_ops" [drivers/iio/adc/stm32-dfsdm-adc.ko] undefined!

Add a dependency on HAS_DMA to fix this.

Fixes: e2e6771c64625165 ("IIO: ADC: add STM32 DFSDM sigma delta ADC support")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>