FRV-setup: Move "else" closer to a brace
The script "checkpatch.pl" pointed information out like the following.

ERROR: else should follow close brace '}'

Thus fix the affected source code places.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>