lib: lcm.c: make __attribute_const__ consistent
The lcm and lcm_not_zero() are producing sparse warnings due to
the use of __attribute_const__ in the header but not in the lcm.c
file. Add the __attribute_const__ to lcm.c and make the header
consistent with using the attribute before the function to fix
the following sparse warnings:

lib/lcm.c:7:15: error: symbol 'lcm' redeclared with different type (originally declared at include/linux/lcm.h:6) - different modifiers
lib/lcm.c:16:15: error: symbol 'lcm_not_zero' redeclared with different type (originally declared at include/linux/lcm.h:7) - different modifiers

Signed-off-by: Ben Dooks <ben.dooks@codethink.co.uk>