pinctrl: stm32: fix debugfs format string
The newly added stm32_pconf_dbg_show function has an incorrect format
string that does not match the arguments, as reported by the gcc warning:

drivers/pinctrl/stm32/pinctrl-stm32.c: In function 'stm32_pconf_dbg_show':
drivers/pinctrl/stm32/pinctrl-stm32.c:797:17: error: too many arguments for format [-Werror=format-extra-args]

This changes the format string in a way that gets rid of the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 3beed93c1617 ("pinctrl: stm32: Implement .pin_config_dbg_show()")