uapi: fix linux/mqueue.h userspace compilation errors
Include <linux/types.h> to fix the following linux/mqueue.h userspace
compilation errors:

/usr/include/linux/mqueue.h:26:2: error: unknown type name '__kernel_long_t'
  __kernel_long_t mq_flags; /* message queue flags   */
/usr/include/linux/mqueue.h:27:2: error: unknown type name '__kernel_long_t'
  __kernel_long_t mq_maxmsg; /* maximum number of messages  */
/usr/include/linux/mqueue.h:28:2: error: unknown type name '__kernel_long_t'
  __kernel_long_t mq_msgsize; /* maximum message size   */
/usr/include/linux/mqueue.h:29:2: error: unknown type name '__kernel_long_t'
  __kernel_long_t mq_curmsgs; /* number of messages currently queued */
/usr/include/linux/mqueue.h:30:2: error: unknown type name '__kernel_long_t'
  __kernel_long_t __reserved[4]; /* ignored for input, zeroed for output */

This reverts commit 139a7bdc2b93 ("mqueue.h: don't include linux/types.h").

Fixes: 63159f5dcccb ("uapi: Use __kernel_long_t in struct mq_attr")
Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>