nios2: time: Fix build error and warning
nios2 builds fail with

arch/nios2/kernel/time.c: In function 'time_init':
arch/nios2/kernel/time.c:354:2: warning:
	'return' with a value, in function returning void

include/linux/of.h:999:2: warning:
	ISO C90 forbids mixed declarations and code

include/linux/of.h:999:22: error:
	expected declaration or statement at end of input

Fixes: 2ef9162920dc ("clocksource/drivers/nios2: Convert init function to return error")
Cc: Daniel Lezcano <daniel.lezcano@linaro.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>