serial: atmel: remove module device table
A recent patch removed most of the module-specific code from the atmel
serial driver, but left the MODULE_DEVICE_TABLE in place, so we can't
build it any more:

drivers/tty/serial/atmel_serial.c:192:1: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE' [-Werror=implicit-int]
drivers/tty/serial/atmel_serial.c:192:1: warning: parameter names (without types) in function declaration

This removes the table as well to avoid the error.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: c39dfebc7798 ("drivers/tty/serial: make serial/atmel_serial.c explicitly non-modular")