bnxt_en: hide unused bnxt_get_max_func_{vnics,rss_ctxs} functions
There are lots of #ifdefs in this file, and a recent patch got one
of them wrong, leading to a harmless warning in some randconfig
builds:

ethernet/broadcom/bnxt/bnxt.c:4956:21: error: 'bnxt_get_max_func_vnics' defined but not used [-Werror=unused-function]
ethernet/broadcom/bnxt/bnxt.c:4947:21: error: 'bnxt_get_max_func_rss_ctxs' defined but not used [-Werror=unused-function]

Ideally we'd just remove all of them and use 'if (IS_ENABLED())'
checks instead, which don't have this problem, but for now, I'm
adding one more #ifdef to shut up the new warning.

Fixes: 8079e8f107bf ("bnxt_en: Refactor code that determines RFS capability.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>