asm-generic/io.h: remove unnecessary #include of <linux/vmalloc.h>
After commit 1f5307b1e094 ("mm, vmalloc: properly track vmalloc users")
the build for ARCH=nios2 fails with:

In file included from ./include/asm-generic/io.h:767:0,
  		 from ./arch/nios2/include/asm/io.h:61,
		 from ./include/linux/io.h:25,
		 from ./arch/nios2/include/asm/pgtable.h:18,
		 from ./include/linux/mm.h:70,
		 from ./include/linux/pid_namespace.h:6,
		 from ./include/linux/ptrace.h:9,
		 from ./arch/nios2/include/uapi/asm/elf.h:23,
		 from ./arch/nios2/include/asm/elf.h:22,
		 from ./include/linux/elf.h:4,
		 from ./include/linux/module.h:15,
		 from init/main.c:16:
./include/linux/vmalloc.h: In function '__vmalloc_node_flags':
./include/linux/vmalloc.h:99:40: error: 'PAGE_KERNEL' undeclared (first use in this function); did you mean 'GFP_KERNEL'?

which is due to the newly added #include <asm/pgtable.h>, which on nios2
includes <linux/io.h> and thus <asm/io.h> and <asm-generic/io.h> which
again includes <linux/vmalloc.h>.

It turns out the #include <linux/vmalloc.h> in <asm-generic/io.h> isn't
necessary at all since none of it definitions are used there, so remove
it alltogether.

Build tested on
 - nios2: 10m50_defconfig
 - x86: allyesconfig, various randconfigs
 - arm: tegra_defconfig, various randconfigs

Cc: Michal Hocko <mhocko@suse.com>
Cc: Ley Foon Tan <lftan@altera.com>
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>