MIPS: MSP71xx: fix build failure
The build of msp71xx_defconfig was failing with the error:
arch/mips/pmcs-msp71xx/msp_smp.c: In function 'msp_vsmp_int_init':
arch/mips/pmcs-msp71xx/msp_smp.c:72:2: error:
	implicit declaration of function 'set_vi_handler';
	did you mean 'irq_set_handler'? [-Werror=implicit-function-declaration]

The file 'msp_smp.c' was only missing a header file.

Signed-off-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>