ext4: fix up huge_fault rename
It looks like a search+replace accidentally change one function pointer that
should have remained as before, as shown by this new warning:

fs/ext4/file.c:279:1: error: 'ext4_dax_huge_fault' defined but not used [-Werror=unused-function]

This reverts the one line of the changeset.

Fixes: 80a841811260 ("mm,fs,dax: change ->pmd_fault to ->huge_fault")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>