x86: setup_percpu: remove unnecessary include of module.h, add asm/desc.h
This was originally a part of commit 186f43608a5c:

    ("x86/kernel: Audit and remove any unnecessary uses of module.h")

...but without the asm/desc.h addition.  As such, Ingo reported a
build failure on i386 allnoconfig with SMP=y during his pre-merge
testing.   For expediency the chunk was just dropped at that time.

The failure was as follows:

arch/x86/kernel/setup_percpu.c: In function ‘setup_percpu_segment’:
arch/x86/kernel/setup_percpu.c:159:2: error: implicit declaration of function
‘pack_descriptor’ [-Werror=implicit-function-declaration]

arch/x86/kernel/setup_percpu.c:162:2: error: implicit declaration of function
‘write_gdt_entry’ [-Werror=implicit-function-declaration]

arch/x86/kernel/setup_percpu.c:162:18: error: implicit declaration of function
‘get_cpu_gdt_table’ [-Werror=implicit-function-declaration]

As pack_descriptor, write_gdt_entry and get_cpu_gdt_table all live in the
file arch/x86/include/asm/desc.h -- calling that header out explicitly
should fix things.

Reported-by: Ingo Molnar <mingo@redhat.com>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Ingo Molnar <mingo@redhat.com>
Cc: "H. Peter Anvin" <hpa@zytor.com>
Cc: x86@kernel.org
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>