phy: leave out DT based interfaces without CONFIG_OF
After a recent change in the PHY core, we get a build error when
CONFIG_OF is disabled:

drivers/phy/phy-core.c: In function '__of_phy_provider_register':
drivers/phy/phy-core.c:848:13: error: implicit declaration of function 'of_get_next_parent' [-Werror=implicit-function-declaration]

It would not be hard to avoid this error by adding a declaration
for of_get_next_parent, but I'm taking a different approach here
and remove all the unused DT handling from the PHY core in
configurations with CONFIG_OF, which avoids the build error and
reduces the object code size.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 2f7600bc981c ("phy: core: Allow children node to be overridden")