rtc: vr41xx: remove unused function:
The vr41xx_rtc_alarm_irq_enable function is never called
has no effect other than producing a warning:

drivers/rtc/rtc-vr41xx.c:228:12: error: 'vr41xx_rtc_alarm_irq_enable' defined but not used [-Werror=unused-function]

This removes it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>