PCI: faraday: use %pap format string for printing resources
resource_size_t may be either 32-bit or 64-bit wide, so we have to use
the special %pap format string to avoid warnings like:

drivers/pci/host/pci-ftpci100.c: In function 'faraday_res_to_memcfg':
drivers/pci/host/pci-ftpci100.c:174:586: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'resource_size_t {aka long long unsigned int}' [-Werror=format=]
drivers/pci/host/pci-ftpci100.c:174:586: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'resource_size_t {aka long long unsigned int}' [-Werror=format=]

This relies on resource_size_t and phys_addr_t being the same width,
as other code already does.

Fixes: 5c18f2b240bd ("PCI: faraday: Add Faraday Technology FTPCI100 PCI Host Bridge driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>