perf-probe: Match linkage name with mangled name
Match linkage name with mangled name if exists. The linkage_name
is used for storing mangled name of the object.
Thus, this allows perf-probe to find appropriate probe point
from mangled symbol as below.

E.g. without this fix:
  ----
  $ ./perf probe -x /usr/lib64/libstdc++.so.6 \
    -D _ZNKSt15basic_fstreamXXIwSt11char_traitsIwEE7is_openEv
  Probe point '_ZNKSt15basic_fstreamXXIwSt11char_traitsIwEE7is_openEv'
  not found.
    Error: Failed to add events.
  ----

With this fix, perf probe can find the correct one.
  ----
  $ ./perf probe -x /usr/lib64/libstdc++.so.6 \
    -D _ZNKSt15basic_fstreamXXIwSt11char_traitsIwEE7is_openEv
  p:probe_libstdc/_ZNKSt15basic_fstreamXXIwSt11char_traitsIwEE7is_openEv
  /usr/lib64/libstdc++.so.6.0.22:0x8ca60
  ----

Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>