phy: xgene: rename "enum phy_mode" to "enum xgene_phy_mode"
commit 96284c53246f ("phy: Add set_mode callback") introduced
enum phy_mode in phy_core. This introduced the following build
error.

drivers/phy/phy-xgene.c:521:6: error: nested redefinition of 'enum phy_mode'
 enum phy_mode {
      ^
drivers/phy/phy-xgene.c:521:6: error: redeclaration of 'enum phy_mode'
In file included from drivers/phy/phy-xgene.c:57:0:
include/linux/phy/phy.h:25:6: note: originally defined here
 enum phy_mode {
      ^
Fix it here.

Signed-off-by: Kishon Vijay Abraham I <kishon@ti.com>
Reviewed-by: Loc Ho <lho@apm.com>