staging/rdma/hfi1: Fix error in hfi1 driver build]
Greg,

It looks like you missed this patch for 4.4-rc5

Could we get it included for rc6?

Thanks,
Ira

----- Forwarded message from Jubin John <jubin.john@intel.com> -----

From: Jubin John <jubin.john@intel.com>
To: <gregkh@linuxfoundation.org>, <devel@driverdev.osuosl.org>
CC: <linux-rdma@vger.kernel.org>, <dledford@redhat.com>,
	<mike.marciniszyn@intel.com>, <ira.weiny@intel.com>, <jubin.john@intel.com>
Subject: [PATCH] staging/rdma/hfi1: Fix error in hfi1 driver build
Date: Fri, 20 Nov 2015 18:13:08 -0500

hfi1 driver build fails with the following error:
In function ‘handle_receive_interrupt’:
error: implicit declaration of function ‘skip_rcv_packet’ [-Werror=implicit-function-declaration]
    last = skip_rcv_packet(&packet, thread);
    ^
This is due to the inclusion of the skip_rcv_packet() in the
CONFIG_PRESCAN_RXQ ifdef block. This function is independent of
CONFIG_PRESCAN_RXQ and should be outside this block.

Fixes: 82c2611daaf0 ("staging/rdma/hfi1: Handle packets with invalid RHF on context 0")
Reviewed-by: Mike Marciniszyn <mike.marciniszyn@intel.com>
Signed-off-by: Jubin John <jubin.john@intel.com>