staging: rtl8192u: Fixing coding style issues
fixed errors and warnings:
ERROR: spaces required around that '='
ERROR: spaces required around that '<'
ERROR: space required before the open parenthesis '('
CHECK: spaces preferred around that '&'
CHECK: spaces preferred around that '<<'
ERROR: space required after that ','
ERROR: spaces required around that '+='
WARNING: Missing a blank line after declarations
CHECK: spaces required around that '?'
CHECK: spaces required around that ':'

Signed-off-by: simran singhal <singhalsimran0@gmail.com>