staging: rtl8188eu: Macro should be enclosed
Fix style error pointed out by checkpatch.pl:
ERROR: Macros with complex values should be enclosed in
parentheses

I have compiled the module just to be sure. I haven't run it
because I haven't changed any funcionality.

Signed-off-by: Alfonso Lima Astor <alfonsolimaastor@gmail.com>