drm/i915/dsi: silence a warning about uninitialized return value
When building the kernel with clang and some warning flags, the compiler
reports that the return value of dcs_get_backlight() may be
uninitialized:

    drivers/gpu/drm/i915/intel_dsi_dcs_backlight.c:53:2: error: variable
    'data' is used uninitialized whenever 'for' loop exits because its
    condition is false [-Werror,-Wsometimes-uninitialized]
            for_each_dsi_port(port, intel_dsi->dcs_backlight_ports) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/i915/intel_dsi.h:126:49: note: expanded from macro
    'for_each_dsi_port'
    #define for_each_dsi_port(__port, __ports_mask)
                                for_each_port_masked(__port, __ports_mask)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/i915/i915_drv.h:322:26: note: expanded from macro
    'for_each_port_masked'
        for ((__port) = PORT_A; (__port) < I915_MAX_PORTS; (__port)++)  \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/i915/intel_dsi_dcs_backlight.c:60:9: note:
    uninitialized use occurs here
            return data;
                   ^~~~

As intel_dsi->dcs_backlight_ports seems to be always initialized to a
non-null value, the content of the for loop is always executed and there
is no bug in the current code. Nevertheless the compiler has no way of
knowing that assumption, so initialize variable 'data' to silence the
warning here.

Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>