misc: mic: remove unused label
A cleanup left an unused label behind:

drivers/misc/mic/vop/vop_vringh.c: In function 'vop_ioctl':
drivers/misc/mic/vop/vop_vringh.c:1001:1: error: label 'done' defined but not used [-Werror=unused-label]

This cleans it up as well.

Fixes: 30b7a2c19e29 ("misc: mic: Use memdup_user() as a cleanup")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>