cpufreq: ti: move to new dev_pm_opp_set_supported_hw() API
We have a conflict between the interface change in one patch, and the
newly added driver using the old interface:

drivers/cpufreq/ti-cpufreq.c: In function 'ti_cpufreq_init':
drivers/cpufreq/ti-cpufreq.c:250:6: error: assignment makes integer from pointer without a cast [-Werror=int-conversion]

This adapts the driver accordingly.

Fixes: fa30184d192e ("PM / OPP: Return opp_table from dev_pm_opp_set_*() routines")
Fixes: 36cae4bca3bc ("cpufreq: ti: Add cpufreq driver to determine available OPPs at runtime")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>