torture: use ktime_t consistently
A recent change accidentally introduced a 64-bit division in torture_shutdown,
which fails to build on 32-bit architectures:

kernel/built-in.o: In function `torture_shutdown':
:(.text+0x4b29a): undefined reference to `__aeabi_uldivmod'

This converts the function to use ktime_t instead, which also simplifies
it a little.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: b4aa201e0c7c ("torture: Convert torture_shutdown() to hrtimer")