mm: migrate: add isolate_movable_page() stub implementation
Without CONFIG_MIGRATION, we get a build failure when trying to
call isolate_movable_page():

mm/memory-failure.c: In function '__soft_offline_page':
mm/memory-failure.c:1656:10: error: implicit declaration of function 'isolate_movable_page';did you mean 'isolate_huge_page'? [-Werror=implicit-function-declaration]

This adds one more static inline helper function in the header
declaring it. This returns false to indicate that the
page was not isolated.

Fixes: mmotm ("HWPOISON: soft offlining for non-lru movable pages")
Fixes: bda807d44454 ("mm: migrate: support non-lru movable page migration")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>