ACPICA: arm64: fix compile apci tools fail for arm64
when try to cross compile acpi tool in dir kernel/tools
for arm64 use command:
    make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- acpi
it failed with the following log:
In file included
    from ../../../../../include/acpi/acpi.h:58:0,
    from ../../../../../drivers/acpi/acpica/utstring.c:44:
    ../../../../../include/acpi/actypes.h:130:34: error: conflicting types for 's64'
 typedef signed long long s64;
                           ^
In file included
    from /opt/aarch64-linux-gnu/libc/usr/include/asm-generic/types.h:6:0
    from /opt/aarch64-linux-gnu/libc/usr/include/asm/types.h:1,
    from ../../../../../include/uapi/linux/types.h:4,
    from ../../../../../include/linux/types.h:5,
    from /opt/aarch64-linux-gnu/libc/usr/include/asm/sigcontext.h:19,
    from /opt/aarch64-linux-gnu/libc/usr/include/bits/sigcontext.h:27,
    from /opt/aarch64-linux-gnu/libc/usr/include/signal.h:308,
    from ../../../../../include/acpi/platform/acenv.h:365,
    from ../../../../../include/acpi/acpi.h:56,
    from ./acpidump.h:55,
    from ../../os_specific/service_layers/oslinuxtbl.c:44:
../../../../../include/asm-generic/int-ll64.h:24:26: note: previous declaration of 's64' was here
 typedef signed long long s64;
                           ^
Fix this compile problem.

Fixes: e323c02dee59 ("ACPICA: MSVC9: Fix <sys/stat.h> inclusion order issue")
Signed-off-by: Yisheng Xie <xieyisheng1@huawei.com>