metag build error in -next due to 'fs, elf: drop MAP_FIXED usage from elf_map'
On Sat 06-01-18 17:07:33, Guenter Roeck wrote:
> The following build error is seen when building metag:meta2_defconfig
> or metag:tz1090_defconfig.
>
> arch/metag/kernel/process.c: In function '__metag_elf_map':
> arch/metag/kernel/process.c:421: error: 'tsk' undeclared

Sorry about that and thanks for your report. The following should fix
the issue. Andrew, could you fold it to the original patch please?