ufs: Fix build errors on 32 bit machines
Various 32 builds fail with error messages such as

ERROR: "__udivdi3" [fs/ufs/ufs.ko] undefined!

due to a variable type change from 32 bit to 64 bit.

Fixes: c596961d1b4c ("ufs: fix s_size/s_dsize users")
Reported-by: Arnd Bergmann <arnd@arndb.de>
Cc: Arnd Bergmann <arnd@arndb.de>
Cc: Al Viro <viro@zeniv.linux.org.uk>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>