x86/vdso: Fix build when CONFIG_KVM_GUEST is not set
Doing randbuilds fails like this here at link time:

  arch/x86/built-in.o: In function `arch_setup_additional_pages':
  /home/boris/kernel/linux/arch/x86/entry/vdso/vma.c:174: undefined reference to `pvclock_pvti_cpu0_va'
  make: *** [vmlinux] Error 1

This is because pvclock_pvti_cpu0_va() is defined in
arch/x86/kernel/kvmclock.c as an accessor to the private hv_clock thing
but if CONFIG_KVM_GUEST is not set, we don't have that function to link
to.

So add CONFIG_KVM_GUEST to the ifdeffery.

Signed-off-by: Borislav Petkov <bp@suse.de>