fpga: FPGA_MGR_ZYNQ_FPGA should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "dma_free_coherent" [drivers/fpga/zynq-fpga.ko] undefined!
    ERROR: "dma_alloc_coherent" [drivers/fpga/zynq-fpga.ko] undefined!

Add a dependency on HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>