mlx5: work around unused function warning
The previous patch addressed a sparse warning but replaced it with a
compiler warning when CONFIG_MODULES is disabled:

drivers/net/ethernet/mellanox/mlx5/core/ipoib.c:485:13: error: 'mlx5_rdma_netdev_free' defined but not used [-Werror=unused-function]
drivers/net/ethernet/mellanox/mlx5/core/ipoib.c:423:27: error: 'mlx5_rdma_netdev_alloc' defined but not used [-Werror=unused-function]

We should never export 'static' functions, so this makes them global
again but hides them in another #ifdef like the change before.

Fixes: a7082ef066f0 ("mlx5: hide unused functions")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>