powerpc: export cpu_to_core_id()
Export cpu_to_core_id().  This will be used by the lpfc driver.

This enables topology_core_id() from  <linux/topology.h> (defined
to cpu_to_core_id() in arch/powerpc/include/asm/topology.h) to be
used by (non-builtin) modules.

That is arch-neutral, already used by eg, drivers/base/topology.c,
but it is builtin (obj-y in Makefile) thus didn't need the export.

Since the module uses topology_core_id() and this is defined to
cpu_to_core_id(), it needs the export, otherwise:

    ERROR: "cpu_to_core_id" [drivers/scsi/lpfc/lpfc.ko] undefined!
    make[1]: *** [__modpost] Error 1
    make: *** [modules] Error 2

Tested on next-20160601.

Changelog:
 - v2: include details about the need for this patch with regards
       to the architecture-neutral topology API.

Signed-off-by: Mauricio Faria de Oliveira <mauricfo@linux.vnet.ibm.com>