sched/core: include asm/paravirt.h
One of the headers that got removed was needed after all, depending
on the configuration:

kernel/sched/core.c: In function 'update_rq_clock_task':
kernel/sched/core.c:198:50: error: 'paravirt_steal_rq_enabled' undeclared (first use in this function); did you mean 'arch_local_irq_enable'?

This restores the include.

Fixes: 004172bdad64 ("sched/core: Remove unnecessary #include headers")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>