drm/msm/rd: fix msm_rd_dump_submit() prototype
A build regression has appeared in linux-4.15-rc from an API change,
in configurations without CONFIG_DEBUG_FS:

In file included from drivers/gpu/drm/msm/msm_gpu.h:24:0,
                 from drivers/gpu/drm/msm/msm_gpu.c:18:
drivers/gpu/drm/msm/msm_drv.h:306:20: note: expected 'struct msm_gem_submit *' but argument is of type 'struct msm_rd_state *'
 static inline void msm_rd_dump_submit(struct msm_gem_submit *submit) {}
                    ^~~~~~~~~~~~~~~~~~
drivers/gpu/drm/msm/msm_gpu.c:295:4: error: too many arguments to function 'msm_rd_dump_submit'

This changes the prototype of the stub function the same way as the
regualar prototype.

Fixes: 998b9a588314 ("drm/msm/rd: allow adding addition msg to top of dump")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>