mtd: fsl-quadspi: Never build on SPARC
Attempts to build fsl-quadspi on SPARC fail with

drivers/mtd/spi-nor/fsl-quadspi.c: In function 'fsl_qspi_init_lut':
drivers/mtd/spi-nor/fsl-quadspi.c:369:1: error:
	'LUT_0' undeclared (first use in this function)
drivers/mtd/spi-nor/fsl-quadspi.c:418:1: error:
	pasting "LUT_" and "(" does not give a valid preprocessing token
drivers/mtd/spi-nor/fsl-quadspi.c:418:2: error:
	implicit declaration of function 'LUT_'

Never build it on SPARC, even if COMPILE_TEST is enabled.

Fixes: d26a22d06708 ("mtd: fsl-quadspi: allow building for other ARCHes
	with COMPILE_TEST")
Cc: Brian Norris <computersforpeace@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>