serial: 8250: fix building mediatek with SERIAL_8250=m
The Mediatek 8250 driver has a 'bool' Kconfig symbol, but that
breaks when SERIAL_8250 is a loadable module:

drivers/tty/built-in.o: In function `mtk8250_set_termios':
8250_ingenic.c:(.text+0x1bee8): undefined reference to `serial8250_do_set_termios'
8250_ingenic.c:(.text+0x1bf10): undefined reference to `uart_get_baud_rate'
8250_ingenic.c:(.text+0x1c09c): undefined reference to `uart_get_divisor'
drivers/tty/built-in.o: In function `mtk8250_do_pm':
8250_ingenic.c:(.text+0x1c0d0): undefined reference to `serial8250_do_pm'
drivers/tty/built-in.o: In function `mtk8250_probe':
8250_ingenic.c:(.text+0x1c2e4): undefined reference to `serial8250_register_8250_port'
serial/8250/8250_mtk.c:287:242: error: data definition has no type or storage class [-Werror]
serial/8250/8250_mtk.c:287:122: error: 'mtk8250_platform_driver_init' defined but not used [-Werror=unused-function]

This changes the symbol to a 'tristate', so the dependency on
SERIAL_8250 also works when that is set to 'm'.
To actually build the driver, we also need to include <linux/module.h>.

Note that the driver uses builtin_platform_driver() and implements
no .remove() callback, so unloading the module is not possible.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>