checkpatch: avoid error report caused by syzbot
syzbot request to add his reported-by when fix the bug find by syzbot.
However, it will trigger a error when use checkpatch:

  ERROR: Unrecognized email address: 'syzbot+d7a918a7a8e1c952bc36@syzkaller.appspotmail.com'

For it include '+' in email and make regular expression works abnomal. Fix
it by adding check for syzbot.

Signed-off-by: Yisheng Xie <xieyisheng1@huawei.com>