ahci: don't use MSI when PCI is disabled
The AHCI driver is used for some on-chip devices that do not
use PCI for probing, and it can be built even when CONFIG_PCI
is disabled, but that now results in a build failure:

ata/libahci.c: In function 'ahci_host_activate_multi_irqs':
ata/libahci.c:2475:4: error: invalid use of undefined type 'struct msix_entry'
ata/libahci.c:2475:21: error: dereferencing pointer to incomplete type 'struct msix_entry'

This adds an #ifdef so we use that code only if actual PCI MSI
is available.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: d684a90d38e2 ("ahci: per-port msix support")