net: dsa: fix build failure
We were getting build failure with allmodconfig of tile, tilegx, m32r and m68k
with the error:
implicit declaration of function 'gpio_to_desc'
implicit declaration of function 'gpiod_direction_output'

Fixes: cc30c16344fc ("net: dsa: Add support for a switch reset gpio")
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>