objtool: Fix Makefile to properly see if libelf is supported
When doing a make allmodconfig, I hit the following compile error:

In file included from builtin-check.c:32:0:
elf.h:22:18: fatal error: gelf.h: No such file or directory
compilation terminated.
In file included from special.h:22:0,
                 from special.c:26:
elf.h:22:18: fatal error: gelf.h: No such file or directory
compilation terminated.
In file included from elf.c:30:0:
elf.h:22:18: fatal error: gelf.h: No such file or directory
compilation terminated.
mv: cannot stat 'tools/objtool/.elf.o.tmp': No such file or directory
tools/build/Makefile.build:77: recipe for target 'tools/objtool/elf.o' failed
make[4]: *** [tools/objtool/elf.o] Error 1
make[4]: *** Waiting for unfinished jobs....

Digging into it, it appears that the $(shell ..) command in the Makefile does
not give the proper result when it fails to find -lelf, and continues to
compile objtool.

Instead, use the "try-run" makefile macro to perform the test. This gives a
proper result for both cases.

Fixes: 442f04c34a1a4 ("objtool: Add tool to perform compile-time stack metadata validation")
Signed-off-by: Steven Rostedt <rostedt@goodmis.org>