ARM: imx: Enable REGMAP_MMIO per default
If unset, the gpc drivers fails to link with this error:
drivers/built-in.o: In function `imx_gpc_probe':
core.c:(.text+0x1e16c): undefined reference to
 `__devm_regmap_init_mmio_clk'

As the gpc driver is built when ARCH_MXC is set, enable REGMAP_MMIO in
this case too.

Signed-off-by: Alexander Stein <alexander.stein@systec-electronic.com>
Fixes: 721cabf6c660 ("soc: imx: move PGC handling to a new GPC driver")