perf tools: Fix wrong indentation and build failure with gcc 6
One line in perf_pmu__parse_unit() is indented wrongly, leading
to a warning (=> error) from gcc 6:

util/pmu.c:156:3: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]
   sret = read(fd, alias->unit, UNIT_MAX_LEN);
   ^~~~

util/pmu.c:153:2: note: ...this 'if' clause, but it is not
  if (fd == -1)
  ^~

Fixes: 410136f5dd96 ("tools/perf/stat: Add event unit and scale support")
Signed-off-by: Ben Hutchings <ben@decadent.org.uk>