mn10300: Add missing include file to proc-init.c
mn10300:asb2303_defconfig fails to build as follows.

arch/mn10300/proc-mn103e010/proc-init.c: In function 'processor_init':
arch/mn10300/proc-mn103e010/proc-init.c:59:24: error: 'NR_IRQS' undeclared

Fixes: 4511118b5b44 ("char/genrtc: remove mn10300 support")
Cc: Arnd Bergmann <arnd@arndb.de>
Cc: Alexandre Belloni <alexandre.belloni@free-electrons.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>