Troubles with smatch and jiffies
Hi Dan,

I'm having some things that look like false positives when testing the media
drivers against smatch. This is bothering me for some time, but, as this was
harder to debug (as I needed to do a build with -j1), I postponed trying to
fix it for a while.

Basically, smatch is complaining for things like:

	time_before(jiffies, jiffies + msecs_to_jiffies(var));

I noticed the very same behavior on two places:
	drivers/media/pci/ivtv/ivtv-mailbox.c
	drivers/media/rc/ati_remote.c

The enclosed patch makes smatch to shut up for ivtv build, but, IMHO,
we should make it stop making it complain about it globalwide, as the
same warning may also be appearing on other places.

FYI, I'm using here gcc (GCC) 5.3.1 20151207 (Red Hat 5.3.1-2) and the
very latest version of smatch from git://repo.or.cz/smatch.git.

Regards,
Mauro

--
Thanks,
Mauro
commit 6a4d1872a94ba8450c9aff6599d1e86b515fd2a9
Author: Mauro Carvalho Chehab <mchehab@osg.samsung.com>
Date:   Mon Feb 22 14:55:14 2016 -0300

    ivtv-mailbox: avoid confusing smatch

    The current logic causes smatch to be confused:
    	include/linux/jiffies.h:359:41: error: strange non-value function or array
    	include/linux/jiffies.h:361:42: error: strange non-value function or array
    	include/linux/jiffies.h:359:41: error: strange non-value function or array
    	include/linux/jiffies.h:361:42: error: strange non-value function or array

    Use a different logic.

    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>