remoteproc: qcom: use %pap format string for phys_addr_t
We cannot cast a phys_addr_t variable to a pointer on 32-bit architectures
with CONFIG_PHYS_ADDR_T_64BIT set:

In file included from include/linux/kernel.h:14:0,
                 from include/linux/clk.h:16,
                 from drivers/remoteproc/qcom_q6v5_pil.c:18:
drivers/remoteproc/qcom_q6v5_pil.c: In function 'q6v5_xfer_mem_ownership':
drivers/remoteproc/qcom_q6v5_pil.c:337:10: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
          (void *)addr, (void *)(addr + size),
          ^

The correct way to print the contents is to use the %pap format
string, passing the phys address by reference.

Fixes: 6c5a9dc2481b ("remoteproc: qcom: Make secure world call for mem ownership switch")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>