selftests/bpf: don't use bpf helpers in non-bpf environment
We're using bpf_htons in test_progs.c to initialize some static
global data and I think I hit some weird case on an older compiler
which doesn't have __builtin_bswap16 (and __builtin_constant_p
expands to false).

In this case I see:
error: implicit declaration of function '__builtin_bswap16'

Let's explicitly use __constant_htons which should be exposed by the
linux/byteorder.h uapi header.

Signed-off-by: Stanislav Fomichev <sdf@google.com>