scsi: advansys needs ISA dma api for ISA support
On Monday 12 October 2015 08:28:01 James Bottomley wrote:
> >
> > diff --git a/drivers/scsi/Kconfig b/drivers/scsi/Kconfig
> > index d2f480b04a52..d4aa6a1a806c 100644
> > --- a/drivers/scsi/Kconfig
> > +++ b/drivers/scsi/Kconfig
> > @@ -499,6 +499,7 @@ config SCSI_ADVANSYS
> >       tristate "AdvanSys SCSI support"
> >       depends on SCSI
> >       depends on ISA || EISA || PCI
> > +     depends on ISA_DMA_API || !ISA
> >       help
> >         This is a driver for all SCSI host adapters manufactured by
> >         AdvanSys. It is documented in the kernel source in
>
> This fix looks wrong.  the request_dma code is confined within an #ifdef
> CONFIG_ISA section but the advansys doesn't actually require an ISA DMA
> channel to function, so you're saying there are systems with ISA but
> without request_dma()?

Yes. Specifically, the ARM EBSA110 and SA1100 platforms can have some
PIO based ISA devices, but they have nothing close enough to an i8237
to support the request_dma interface.

> If so I think we leave the depends alone and try to bring the board up
> in NO_ISA_DMA mode.

Ok

>  That means the narrowboard check should be gated by
> CONFIG_ISA_DMA_API ... do we also have to gate free_dma as well?

Yes. A few more as well, as we also don't want to do inb/outb
instructions to a DMA controller that is not there.

I've compile-tested the patch below.

	Arnd

8<-------
From 67fed3da5dd65abf5e4d01d8731c5217eb823fdb Mon Sep 17 00:00:00 2001
From: Arnd Bergmann <arnd@arndb.de>
Date: Sat, 10 Oct 2015 21:13:29 +0200
Subject: [PATCH] scsi: advansys: fix build without ISA DMA API

The advansys drvier uses the request_dma function that is used on ISA
machines for the internal DMA controller, which causes build errors
on platforms that have ISA slots but do not provide the ISA DMA API:

drivers/scsi/advansys.c: In function 'advansys_board_found':
drivers/scsi/advansys.c:11300:10: error: implicit declaration of function 'request_dma' [-Werror=implicit-function-declaration]

The problem now showed up in ARM randconfig builds after commit
6571fb3f8b7f ("advansys: Update to version 3.5 and remove compilation
warning") made it possible to build on platforms that have neither
VIRT_TO_BUS nor ISA_DMA_API but that do have ISA.

This changes the existing #ifdefs in the driver to check for both
CONFIG_ISA and CONFIG_ISA_DMA_API where appropriate. It should
still be possible to use the driver in PIO mode with ISA when
DMA is not available.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>