sched/fair: move capacity_margin definition into #ifdef
Marking the variable static showed that it's only used for
SMP builds, as seen from this warning:

kernel/sched/fair.c:119:21: error: 'capacity_margin' defined but not used [-Werror=unused-variable]
 static unsigned int capacity_margin   = 1280;

This has apparently been true since the variable has first been
introduced, but only now started causing a compile time warning.

Fixes: ed8885a14433 ("sched/fair: Make some variables static")
Fixes: 3273163c6775 ("sched/fair: Let asymmetric CPU configurations balance at wake-up")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>