of: Move of_io_request_and_map prototype to correct context
of_io_request_and_map() is defined in of/address.c, which is compiled
if CONFIG_OF_ADDRESS is configured. However, it is defined in the context
of CONFIG_OF. This results in the following build errors for
sparc:allmodconfig (which defines CONFIG_OF but not CONFIG_OF_ADDRESS).

drivers/built-in.o: In function `meson6_timer_init':
	meson6_timer.c:(.init.text+0x62a8):
		undefined reference to `of_io_request_and_map'
drivers/built-in.o: In function `mtk_timer_init':
	mtk_timer.c:(.init.text+0x6e70):
		undefined reference to `of_io_request_and_map'
drivers/built-in.o: In function `asm9260_timer_init':
	asm9260_timer.c:(.init.text+0x6fcc):
		undefined reference to `of_io_request_and_map'

Move function prototype and dummy function into the CONFIG_OF_ADDRESS
conditional to fix the problem.

Exposed by commit bec8c4617611 ("clocksource/drivers/mediatek: Add the
COMPILE_TEST option").

Cc: Daniel Lezcano <daniel.lezcano@linaro.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>