undefined reference to `snd_timer_interrupt'
On Tue, 26 Jan 2016 23:16:55 +0100,
kbuild test robot wrote:
>
> tree:   https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git master
> head:   92e963f50fc74041b5e9e744c330dca48e04f08d
> commit: 90bbaf66ee7b946952f1e82a0069639dea5fd893 ALSA: timer: add config item to export PCM timer disabling for expert
> date:   3 months ago
> config: x86_64-randconfig-s0-01270516 (attached as .config)
> reproduce:
>         git checkout 90bbaf66ee7b946952f1e82a0069639dea5fd893
>         # save the attached .config to linux build tree
>         make ARCH=x86_64
>
> All errors (new ones prefixed by >>):
>
>    sound/built-in.o: In function `snd_emu10k1_interrupt':
> >> (.text+0x604c7): undefined reference to `snd_timer_interrupt'
>    sound/built-in.o: In function `snd_emu10k1_timer':
> >> (.text+0x70d5d): undefined reference to `snd_timer_new'

Fixed by the patch below.

thanks,

Takashi

-- 8< --
From: Takashi Iwai <tiwai@suse.de>
Subject: [PATCH] ALSA: Add missing dependency on CONFIG_SND_TIMER

Since the build of PCM timer may be disabled via Kconfig now, each
driver that provides a timer interface needs to set CONFIG_SND_TIMER
explicitly.  Otherwise it may get a build error due to missing
symbol.

Fixes: 90bbaf66ee7b ('ALSA: timer: add config item to export PCM timer disabling for expert')
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Cc: <stable@vger.kernel.org> # v4.4+
Signed-off-by: Takashi Iwai <tiwai@suse.de>