Btrfs: incremental send, add gen for is_waiting_for_rm when some corner case
There a one case for old_gen waiting_for_rm,
but new_gen use get_cur_path with the same inode.

Example:
    Parent snapshot:
    |---- dir258/ (ino 258, dir)
        |--- dir257/ (ino 257, dir)
    |---- dir259/ (ino 259, dir)

    Send snapshot:
    |---- file258 (ino 258, file)
    |---- new_dir259/ (ino 259, dir)
        |--- dir257/ (ino 257, dir)

utimes
mkdir o259-21-0
rename dir258 -> o258-15-0
utimes
mkfile o258-21-0
rename o258-21-0 -> file258
utimes
truncate o258-21-0 size=0
ERROR: truncate o258-21-0 failed: No such file or directory

dir258 will be delete, but dir257 is waiting for move,
so dir258 is waiting for rm, and then file258 be create,
and rename it, and then need to truncate it, so use get_cur_path
to get path, but is_waiting_for_rm olny check ino, dosen't check gen,
match dir258 is waiting for rm, so get error path o258-21-0.

therefore, add gen check in is_waiting_for_rm.

Signed-off-by: Robbie Ko <robbieko@synology.com>