PCI: iproc: fix msi driver selection
The newly added MSI support for iproc causes a link error when its
Kconfig option is disabled:

ERROR: "iproc_msi_exit" [drivers/pci/host/pcie-iproc.ko] undefined!
ERROR: "iproc_msi_init" [drivers/pci/host/pcie-iproc.ko] undefined!

This changes the header file so we use stub functions whenever
the driver is not built, even when CONFIG_MSI is enabled.

As the Kconfig logic for the driver is a bit off, I'm rectifying
that as well, by making it depend on the specific drivers that
call into the driver, and moving the option behind those instead
of before them.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 610894347cbf ("PCI: iproc: Add iProc PCIe MSI support")