serial: samsung: Bring back removed variable to fix compilation
By mistake commit 500fcc08a32b ("serial: samsung: Add missing checks for
dma_map_single failure") removes a local variable which is still used by
code.  After backporting the commit to stable, compilation fails:

	drivers/tty/serial/samsung.c: In function ‘s3c24xx_serial_request_dma’:
	drivers/tty/serial/samsung.c:909:45: error: ‘flags’ undeclared (first use in this function)

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>