PM / Domains: provide pm_genpd_poweroff_noirq stub
When CONFIG_PM_SLEEP is disabled, we don't have a pm_genpd_poweroff_noirq
function definition:

drivers/base/power/domain.c: In function 'pm_genpd_init':
drivers/base/power/domain.c:1549:37: error: 'pm_genpd_poweroff_noirq' undeclared (first use in this function); did you mean 'genpd_power_off_unused'?

This adds another NULL definition for it, just like we already have
for the other _noirq handlers.

Fixes: 10da65423fdb ("PM / Domains: Call driver's noirq callbacks")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>