kernel/padata: hide unused functions
A recent cleanup removed some exported functions that were not
used anywhere, which in turn exposed the fact that some other
functions in the same file are only used in some configurations.

We now get a warning about them when CONFIG_HOTPLUG_CPU is
disabled:

kernel/padata.c:670:12: error: '__padata_remove_cpu' defined but not used [-Werror=unused-function]
 static int __padata_remove_cpu(struct padata_instance *pinst, int cpu)
            ^~~~~~~~~~~~~~~~~~~
kernel/padata.c:650:12: error: '__padata_add_cpu' defined but not used [-Werror=unused-function]
 static int __padata_add_cpu(struct padata_instance *pinst, int cpu)

This rearranges the code so the __padata_remove_cpu/__padata_add_cpu
functions are within the #ifdef that protects the code that calls
them.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 4ba6d78c671e ("kernel/padata.c: removed unused code")