Bluetooth: hci_nokia: select CONFIG_BT_HCIUART_H4
Like the other H4 variants, this only builds when the base
H4 support is enabled, otherwise we get a build error:

drivers/bluetooth/hci_nokia.c:624:33: error: array type has incomplete element type 'struct h4_recv_pkt'

Fixes: 7bb318680e86 ("Bluetooth: add nokia driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>