i2c: i801: mark PM functions as __maybe_unused
Changing from UNIVERSAL_DEV_PM_OPS to SIMPLE_DEV_PM_OPS caused a harmless
warning in configurations without CONFIG_PM_SLEEP:

drivers/i2c/busses/i2c-i801.c:1723:12: error: 'i801_resume' defined but not used [-Werror=unused-function]
 static int i801_resume(struct device *dev)
            ^~~~~~~~~~~
drivers/i2c/busses/i2c-i801.c:1714:12: error: 'i801_suspend' defined but not used [-Werror=unused-function]
 static int i801_suspend(struct device *dev)

This removes the incorrect #ifdef and instead marks both functions as
__maybe_unused, which is a more robust way to express the same thing.

Fixes: a9c8088c7988 ("i2c: i801: Don't restore config registers on runtime PM")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>