rtl8723bs: fix build when DEBUG_RTL871X is defined
Defining DEBUG_RTL871X in rtw_debug.h causes the following compile error:
  CC [M]  drivers/staging/rtl8723bs/core/rtw_mlme.o
In file included from drivers/staging/rtl8723bs/core/rtw_mlme.c:18:0:
drivers/staging/rtl8723bs/core/rtw_mlme.c: In function ‘rtw_restruct_sec_ie’:
drivers/staging/rtl8723bs/core/rtw_mlme.c:2502:19: error: ‘ndissecuritytype’ undeclared (first use in thisfunction)

Remove the no longer existing parameter.

Signed-off-by: Stefan Assmann <sassmann@kpanic.de>