pinctrl: axp209: add CONFIG_OF dependency
The pinconf_generic_dt_free_map and pinconf_generic_dt_node_to_map_group
functions are only defined when CONFIG_OF is set:

drivers/pinctrl/pinctrl-axp209.c:312:21: error: 'pinconf_generic_dt_node_to_map_group' undeclared here (not in a function); did you mean 'pinconf_generic_params'?
drivers/pinctrl/pinctrl-axp209.c:313:18: error: 'pinconf_generic_dt_free_map' undeclared here (not in a function); did you mean 'pinconf_generic_params'?

This adds a Kconfig depdency for the driver to prevent randconfig
build failures.

Fixes: 23f75d7dfa92 ("pinctrl: axp209: add pinctrl features")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>