media: i2c: mt9v111: Add VIDEO_V4L2_SUBDEV_API dependency
Fix build error caused by the VIDEO_V4L2_SUBDEV_API symbol not being enabled
in Kconfig option by making the driver depend on it.

Builds configured without the VIDEO_V4L2_SUBDEV_API symbol fail with:
drivers/media/i2c/mt9v111.c:801:10: error: implicit declaration of function
'v4l2_subdev_get_try_format';

Fixes: aab7ed1c ("media: i2c: Add driver for Aptina MT9V111")
Signed-off-by: Jacopo Mondi <jacopo+renesas@jmondi.org>