tools:perf:scripting-engines: Fix compile error with some perl5 versions
Fix below compile error:
CC       util/scripting-engines/trace-event-perl.o
In file included from /usr/lib/perl5/5.22.2/i686-linux/CORE/perl.h:5673:0,
                 from util/scripting-engines/trace-event-perl.c:31:
/usr/lib/perl5/5.22.2/i686-linux/CORE/inline.h: In function 'S__is_utf8_char_slow':
/usr/lib/perl5/5.22.2/i686-linux/CORE/inline.h:270:5: error: nested extern declaration of 'Perl___notused' [-Werror=nested-externs]
        dTHX;   /* The function called below requires thread context */
			     ^
cc1: all warnings being treated as errors

After digging perl5 repository, I find out that we will meet this compile error
with perl from v5.21.1 to v5.25.4

Signed-off-by: Wang YanQing <udknight@gmail.com>