staging: wilc1000: fix for undefined reference to `__this_module' error
wilc_debugfs.o object file is included for both SDIO and SPI module.
When anyone(either SDIO or SPI) module is compiled as loaded module and
another as builtin module then below compilation error occurs.

"drivers/staging/wilc1000/wilc_debugfs.o:(.data+0x10): undefined
reference to `__this_module'"

Deleted wilc_debugfs.c file as it's not used, fixed the compilation error.

Fixes: 9abc44ba4e2f ("staging: wilc1000: fix TODO to compile spi and sdio components in single module")
Reported-by: kbuild test robot <lkp@intel.com>
Suggested-by: Greg KH <gregkh@linuxfoundation.org>
Signed-off-by: Ajay Singh <ajay.kathat@microchip.com>