tty/serial: make early console depend on SERIAL_CORE=y
On an powerpc allmodconfig build, the following is seen:

paul@builder:~/git/linux-head$ make O=../ppc-build -j30 > /dev/null
drivers/built-in.o: In function `.setup_earlycon':
(.init.text+0x5b00): undefined reference to `.uart_parse_earlycon'
make[1]: *** [vmlinux] Error 1

Since uart_parse_earlycon lives in serial_core.c we need to ensure
it is built in if early console is to be used.

Cc: Arnd Bergmann <arnd@arndb.de>
Cc: Peter Hurley <peter@hurleysoftware.com>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Cc: Jiri Slaby <jslaby@suse.com>
Cc: linux-serial@vger.kernel.org
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>