usb: Fix microtek driver compilation errors
This fixes compilation errors due to missing scsi_cmnd.h include.

usb/image/microtek.c: In function ‘mts_slave_alloc’:
usb/image/microtek.c:326:3: error: dereferencing pointer to incomplete type
  s->inquiry_len = 0x24;
   ^
usb/image/microtek.c: In function ‘mts_slave_configure’:
usb/image/microtek.c:332:27: error: dereferencing pointer to incomplete type
  blk_queue_dma_alignment(s->request_queue, (512 - 1));
                           ^
usb/image/microtek.c: In function ‘mts_scsi_abort’:
usb/image/microtek.c:338:48: error: dereferencing pointer to incomplete type
  struct mts_desc* desc = (struct mts_desc*)(srb->device->host->hostdata[0]);
                                                ^
etc.

Signed-off-by: Mariusz Skamra <mariuszx.skamra@intel.com>