linux-next: build failure after merge of the akpm-current tree
Hi Andrew,

After merging the akpm-current tree, today's linux-next build (powerpc
ppc64_defconfig) failed like this:

drivers/block/nbd.c: In function 'nbd_thread_send':
drivers/block/nbd.c:592:3: error: implicit declaration of function 'dequeue_signal_lock' [-Werror=implicit-function-declaration]
   dequeue_signal_lock(current, &current->blocked, &info);
   ^

Caused by commit

  ffcb8dc55a97 ("signal: turn dequeue_signal_lock() into kernel_dequeue_signal()")

interacting with commit

  dcc909d90ccd ("nbd: Add locking for tasks")

from Linus' tree.

I added this merge fix patch:

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Mon, 2 Nov 2015 03:04:27 +1100
Subject: [PATCH] ndb: fix up for dequeue_signal_lock API change

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>