x86, relocs: add function attributes to die()
When building the kernel with clang and some warning flags, the compiler
reports the following warning:

    arch/x86/tools/relocs.c:979:6: warning: variable 'do_reloc' is used
    uninitialized whenever 'if' condition is false
    [-Wsometimes-uninitialized]
            if (!use_real_mode)
                ^~~~~~~~~~~~~~
    arch/x86/tools/relocs.c:991:14: note: uninitialized use occurs here
            walk_relocs(do_reloc);
                        ^~~~~~~~
    arch/x86/tools/relocs.c:979:2: note: remove the 'if' if its
    condition is always true
            if (!use_real_mode)
            ^~~~~~~~~~~~~~~~~~~
    arch/x86/tools/relocs.c:976:24: note: initialize the variable
    'do_reloc' to silence this warning
                            const char *symname);
                                                ^
                                                 = NULL

This is obviously a false positive: whenever the 'if' condition is
false, the program calls die(). Nevertheless the compiler did not know
this call makes the program quit because this function did not have a
noreturn attribute. Add it.

While at it, add a printf attribute too to die() and constify the format
parameter. This leads to some errors when compiling on x86_64:

    arch/x86/tools/relocs.c:460:5: error: format specifies type 'int'
    but the argument has type 'Elf64_Xword' (aka 'unsigned long')
    [-Werror,-Wformat]
                                    sec->shdr.sh_size);
                                    ^~~~~~~~~~~~~~~~~
    arch/x86/tools/relocs.c:464:5: error: format specifies type 'int'
    but the argument has type 'Elf64_Off' (aka 'unsigned long')
    [-Werror,-Wformat]
                                    sec->shdr.sh_offset, strerror(errno));
                                    ^~~~~~~~~~~~~~~~~~~

To support both 32-bit and 64-bit modes, add casts to long types and use
%lu and %ld to format the numbers.

Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>