scsi: qla2xxx: fix printk format string warning on 32-bit
On 32-bit architectures, we using %lx to print a size_t causes a harmless
warning:

qla2xxx/qla_init.c: In function 'qla24xx_load_risc_flash':
qla2xxx/qla_init.c:6407:7: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'unsigned int' [-Werror=format=]
qla2xxx/qla_init.c: In function 'qla24xx_load_risc_blob':
qla2xxx/qla_init.c:6709:7: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'unsigned int' [-Werror=format=]

The correct format string is %zx.

Fixes: 0f110b54d157 ("scsi: qla2xxx: Retain loop test for fwdump length exceeding buffer length")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>