tty/serial: atmel: Include module.h to fix build failure
If serial/atmel_serial.c is compiled with devicetree enabled, the
following build error is observed.

drivers/tty/serial/atmel_serial.c:192:1: warning:
	data definition has no type or storage class
drivers/tty/serial/atmel_serial.c:192:1: error:
	type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE'
drivers/tty/serial/atmel_serial.c:192:1: warning:
	parameter names (without types) in function declaration

MODULE_DEVICE_TABLE is used to specify devicetree compatibilities.

Fixes: c39dfebc7798 ("drivers/tty/serial: make serial/atmel_serial.c explicitly non-modular")
Cc: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>