relay: select CONFIG_IRQ_WORK
The relay code was changed to use irq_work, and it now fails to build
if that is disabled:

kernel/relay.o: In function `__relay_reset':
relay.c:(.text.__relay_reset+0xb0): undefined reference to `irq_work_sync'
kernel/relay.o: In function `relay_close_buf':
relay.c:(.text.relay_close_buf+0x14): undefined reference to `irq_work_sync'
kernel/relay.o: In function `relay_switch_subbuf':

This adds the necessary Kconfig select statement.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: c37d49250a7b ("relay: Use irq_work instead of plain timer for deferred wakeup")