of: fix build failure
We are having build failure with next-20151202 for sparc allmodconfig
with the error messages:
undefined reference to 'of_io_request_and_map'

CONFIG_OF is defined for sparc so it is expected that we have a
definition of of_io_request_and_map() but of/address.c is only compiled
if it is !SPARC.

Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>