Raise the minimum required gcc version to 4.6
Various architectures fail to build properly with older versions
of the gcc compiler.

An example from Guenter Roeck via this thread:
https://lore.kernel.org/lkml/20180814170904.GA12768@roeck-us.net/

----------------------
In file included from ./include/linux/mm.h:17:0,
                 from ./include/linux/pid_namespace.h:7,
                 from ./include/linux/ptrace.h:10,
                 from arch/openrisc/kernel/asm-offsets.c:32:
./include/linux/mm_types.h:497:16: error: flexible array member in otherwise empty struct

This is just an example with gcc 4.5.1 for or32. I have seen the problem
with gcc 4.4 (for unicore32) as well.
----------------------

So update the minimum required version of gcc to 4.6.

Miscellanea:

o Update Documentation/process/changes.rst
o Remove and consolidate version test blocks in compiler-gcc.h
  for versions lower than 4.6

Signed-off-by: Joe Perches <joe@perches.com>
Reviewed-by: Kees Cook <keescook@chromium.org>
Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>