PCI: amlogic: fix build failure due to missing linux/gpio/consumer.h header
When building on x86, I got the following build failure:
drivers/pci/controller/dwc/pci-meson.c: In function ‘meson_pcie_assert_reset’:
drivers/pci/controller/dwc/pci-meson.c:290:2: error: implicit declaration of function ‘gpiod_set_value_cansleep’; did you mean ‘gpio_set_value_cansleep’? [-Werror=implicit-function-declaration]
  gpiod_set_value_cansleep(mp->reset_gpio, 0);
  ^~~~~~~~~~~~~~~~~~~~~~~~
  gpio_set_value_cansleep
drivers/pci/controller/dwc/pci-meson.c: In function ‘meson_pcie_probe’:
drivers/pci/controller/dwc/pci-meson.c:540:19: error: implicit declaration of function ‘devm_gpiod_get’; did you mean ‘devm_gpio_free’? [-Werror=implicit-function-declaration]
  mp->reset_gpio = devm_gpiod_get(dev, "reset", GPIOD_OUT_LOW);
                   ^~~~~~~~~~~~~~
                   devm_gpio_free
drivers/pci/controller/dwc/pci-meson.c:540:48: error: ‘GPIOD_OUT_LOW’ undeclared (first use in this function); did you mean ‘GPIOF_INIT_LOW’?
  mp->reset_gpio = devm_gpiod_get(dev, "reset", GPIOD_OUT_LOW);
                                                ^~~~~~~~~~~~~
                                                GPIOF_INIT_LOW

This is due to the missing linux/gpio/consumer.h header

Signed-off-by: Corentin Labbe <clabbe@baylibre.com>