ovl: avoid setting uninitialized creds
If the call to ovl_copy_up() fails, we now call revert_creds on
an uninitialized structure after a recent patch, as found
by "gcc -Wmayby-uninitialized":

fs/overlayfs/inode.c: In function 'ovl_open_maybe_copy_up':
fs/overlayfs/inode.c:39:2: error: 'old_cred' may be used uninitialized in this function [-Werror=maybe-uninitialized]
fs/overlayfs/inode.c:22:21: note: 'old_cred' was declared here

This changes the code back to not call revert_creds unless
we have already called ovl_override_creds().

Fixes: 54249cd03956 ("ovl: during copy up, switch to mounter's creds early")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>