vcodec: mediatek: add missing linux/slab.h include
With the newly added driver, I have run into randconfig failures like:

drivers/media/platform/mtk-jpeg/mtk_jpeg_core.c: In function 'mtk_jpeg_open':
drivers/media/platform/mtk-jpeg/mtk_jpeg_core.c:1017:8: error: implicit declaration of function 'kzalloc';did you mean 'kvzalloc'? [-Werror=implicit-function-declaration]

Including the header with the declaration solves the problem.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>