Btrfs: incremental send, fix don't skip root inode in overwrite_ref
When root dir item change, don't skip will_overwrite_ref,
because root inode always exist.

Example:
Parent snapshot:
|---- a1/ (ino 257, dir)
|---- a2/ (ino 258, dir)

Send snapshot:
|---- a2 (ino 257, file)

ERROR: rename o257-29-0 -> a2 failed: Is a directory

when process 257, first rmdir (ino 257,dir), and then mkfile o257-29-0,
and rename o257-29-0 -> a2, but now parent snapshot had a2(ino 258,dir),
we don't ignore it.

therefore is_inode_existent always return 1,
and will_overwrite_ref don't check gen for root inode.

Signed-off-by: Robbie Ko <robbieko@synology.com>