staging: wilc1000: restore wilc_spi_dev variable
A recent change to wilc1000 accidentally deleted an important
variable, so we now get a build error when the SPI mode is
selected:

ERROR: "wilc_spi_dev" [drivers/staging/wilc1000/wilc1000.ko] undefined!

This partially reverts the broken commit to put the variable back.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 56293ff232b9 ("staging: wilc1000: linux_wlan_spi: include header")