linux-next: build failure after merge of the mfd tree
Hi Lee,

After merging the mfd tree, today's linux-next build (x86_64 allmodconfig)
failed like this:

drivers/mfd/intel-lpss.c:29:47: fatal error: asm-generic/io-64-nonatomic-lo-hi.h: No such file or directory
 #include <asm-generic/io-64-nonatomic-lo-hi.h>
                                               ^

Caused by commit

  6a1d82fbc8e8 ("mfd: intel-lpss: Use writeq() helper")

interacting with commit

  f626fe17485b ("move io-64-nonatomic*.h out of asm-generic")

from the asm-generic tree.

I have added the following merge fix patch and can carry it as necessary.

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Thu, 15 Oct 2015 13:23:20 +1100
Subject: [PATCH] mfd: fix for "move io-64-nonatomic*.h out of asm-generic"

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>