lpc_eth: remove unused variable
A cleanup patch removed the only user of a local variable, as
indicated by a gcc warning.

drivers/net/ethernet/nxp/lpc_eth.c: In function 'lpc_eth_ioctl':
drivers/net/ethernet/nxp/lpc_eth.c:1183:24: error: unused variable 'pldat' [-Werror=unused-variable]

This removes the variable as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: f786f3564c4f ("net: ethernet: lpc_eth: use phydev from struct net_device")