serial-uartlite: un-constify uartlite_be/uartlite_le
The patch to make uartlite_be/uartlite_le const was well-intended but
caused a new build warning:

tty/serial/uartlite.c: In function 'ulite_request_port':
tty/serial/uartlite.c:348:21: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
tty/serial/uartlite.c:354:22: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]

It would be nice to allow passing const pointers through
port->private_data, but that would be way more work, so this
reverts part of the original commit for now.

A possible alternative might be to pass a structure in the private_data
that contains a const pointer to the operations, which introduces a little
extra overhead, or we could just add a cast to a non-const pointer, I'll
leave that to the maintainer.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 2905697a82ea ("serial-uartlite: Constify uartlite_be/uartlite_le")