dmaengine: pl330: Mark unused functions as __maybe_unused
Several functions are not used and probably kept around for completeness
or debugging. Adding the attribute fixes a bunch of warnings like this
when building with clang:

drivers/dma/pl330.c:568:19: error: unused function '_emit_ADDH'
    [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>