gpio: Remove superfluous include of io-mapping.h
The io-mapping.h include arose from the need to workaround an arch/um
compile failure:

   drivers/gpio/gpio-mpc8xxx.c: In function 'mpc8xxx_probe':
>> drivers/gpio/gpio-mpc8xxx.c:373:2: error: implicit declaration of
>> function 'iounmap' [-Werror=implicit-function-declaration]
     iounmap(mpc8xxx_gc->regs);
     ^~~~~~~

from commit 296ad4acb8ef ("gpio: remove deps on
ARCH_[WANT_OPTIONAL|REQUIRE]_GPIOLIB") but io-mapping.h doesn't provide
iounmap so the problem persisted and eventually (will be) silenced by
making OF_GPIO depend on !NO_IOMEM (i.e. disabling building under
arch/um). My desire to remove the unneed include to io-mapping is to
simplify verification of changes to io-mapping.h

Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>
Cc: Linus Walleij <linus.walleij@linaro.org>
Cc: Alexandre Courbot <gnurou@gmail.com>
Cc: linux-gpio@vger.kernel.org