sh/intc: Add a space character for better code readability in register_intc_controller()
The script "checkpatch.pl" pointed information out like the following.

ERROR: spaces required around that '+=' (ctx:VxW)

Thus fix the affected source code place.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>