tools: build: fix libiberty feature detection
Any CFLAGS or LDFLAGS set by the user need to be passed to the feature build
command.  This many include for example -I or -L to point to libraries and
include files in custom paths.

In most of the test-*.bin rules in build/feature/Makefile, we use the BUILD
macro which always sends in CFLAGS and LDFLAGS.  The libiberty build line
however doesn't use the BUILD macro and thus needs to send in CFLAGS and
LDFLAGS explicitly.  Without this, when using custom CFLAGS/LDFLAGS, libiberty
fails to be detected and the perf link fails with something like:

  LINK     perf
 libbfd.a(bfd.o): In function `bfd_errmsg':
 bfd.c:(.text+0x168): undefined reference to `xstrerror'
 bbfd.a(opncls.o): In function `_bfd_new_bfd':
 opncls.c:(.text+0xe8): undefined reference to `objalloc_create'
 ...

Signed-off-by: Rabin Vincent <rabin.vincent@axis.com>