xfs: only modify ACLs if CONFIG_XFS_POSIX_ACL enabled
A recent bug fix added a call to forget_cached_acl(), but that
function is not always available, so we can get a build error
here:

fs/xfs/xfs_xattr.c: In function 'xfs_xattr_set':
fs/xfs/xfs_xattr.c:84:4: error: implicit declaration of function 'forget_cached_acl' [-Werror=implicit-function-declaration]

This changes the code to use the same #ifdef that we already
use to encapsule the existing ACL handling.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 6caa105651cb ("xfs: invalidate cached acl if set directly via xattr")