linux-next: build failure after merge of the asm-generic tree
Hi Arnd,

After merging the asm-generic tree, today's linux-next build (x86_64
allmodconfig) failed like this:

drivers/acpi/osl.c:46:47: fatal error: asm-generic/io-64-nonatomic-lo-hi.h: No such file or directory
 #include <asm-generic/io-64-nonatomic-lo-hi.h>
                                               ^

Caused by commit

  f626fe17485b ("move io-64-nonatomic*.h out of asm-generic")

interacting with commit

  3277b4ea216e ("ACPI / osl: replace custom implementation of readq / writeq")

from Linus' tree (added before v4.3-rc1).

I added the following build fix:

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Thu, 15 Oct 2015 09:50:08 +1100
Subject: [PATCH] fix for "move io-64-nonatomic*.h out of asm-generic"

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>