staging: ccree: remove unused function argument
"gcc -Wunused" warns about one argument being assigned but not used:

drivers/staging/ccree/ssi_cipher.c: In function 'ssi_blkcipher_complete':
drivers/staging/ccree/ssi_cipher.c:747:41: error: parameter 'info' set but not used [-Werror=unused-but-set-parameter]

We can simply drop that argument here and in its callers.

Fixes: 302ef8ebb4b2 ("staging: ccree: add skcipher support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>