+ printk-add-kernel-parameter-to-control-writes-to-dev-kmsg-checkpatch-fixes.patch added to -mm tree
Hi Andrew,

On Mon, Jul 18, 2016 at 02:27:48PM -0700, akpm@linux-foundation.org wrote:
>
> The patch titled
>      Subject: printk-add-kernel-parameter-to-control-writes-to-dev-kmsg-checkpatch-fixes
> has been added to the -mm tree.  Its filename is
>      printk-add-kernel-parameter-to-control-writes-to-dev-kmsg-checkpatch-fixes.patch
>
> This patch should soon appear at
>     http://ozlabs.org/~akpm/mmots/broken-out/printk-add-kernel-parameter-to-control-writes-to-dev-kmsg-checkpatch-fixes.patch
> and later at
>     http://ozlabs.org/~akpm/mmotm/broken-out/printk-add-kernel-parameter-to-control-writes-to-dev-kmsg-checkpatch-fixes.patch
>
> Before you just go and hit "reply", please:
>    a) Consider who else should be cc'ed
>    b) Prefer to cc a suitable mailing list as well
>    c) Ideally: find the original patch on the mailing list and do a
>       reply-to-all to that, adding suitable additional cc's
>
> *** Remember to use Documentation/SubmitChecklist when testing your code ***
>
> The -mm tree is included into linux-next and is updated
> there every 3-4 working days
>
> ------------------------------------------------------
> From: Andrew Morton <akpm@linux-foundation.org>
> Subject: printk-add-kernel-parameter-to-control-writes-to-dev-kmsg-checkpatch-fixes
>
> ERROR: else should follow close brace '}'
> #160: FILE: kernel/printk/printk.c:120:
> +	}
> +	else

Thanks for catching this, here's an updated 2/2 patch with the above
integrated and the SYSTEM_BOOTING check removed because we set
system_state to SYSTEM_RUNNING before we start init.