libata: add parentheses to avoid a gcc warning
gcc-6.1 warns about possibly ambiguous code that was newly added
to libata:

drivers/ata/libata-scsi.c: In function 'ata_mselect_caching':
drivers/ata/libata-scsi.c:3637:28: error: suggest parentheses around comparison in operand of '&' [-Werror=parentheses]
drivers/ata/libata-scsi.c: In function 'ata_mselect_control':
drivers/ata/libata-scsi.c:3702:28: error: suggest parentheses around comparison in operand of '&' [-Werror=parentheses]

The code is fine, and it's not really ambigous to human readers,
but let's shut up the warning anyway by adding the parentheses
that gcc suggests.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 9b7844a8c34a ("libata-scsi: fix read-only bits checking in ata_mselect_*()")