phy: tegra-xusb: add pinctrl dependency
The newly added tegra xusb phy driver fails to link when CONFIG_PINCTRL
is disabled, since that also leaves out the legacy probe function:

ERROR: "tegra_xusb_padctl_legacy_probe" [drivers/phy/tegra/phy-tegra-xusb.ko] undefined!

This adds a Kconfig dependency for it, depending on both
PINCTRL_TEGRA_XUSB (for the driver) and PINCTRL_TEGRA (for the
directory it's in), adding a dependency on just one of the
two does not solve the problem unfortunately.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 53d2a715c240 ("phy: Add Tegra XUSB pad controller support")