serial: atmel: header file for MODULE_DEVICE_TABLE
mips allmodconfig fails with the error:

drivers/tty/serial/atmel_serial.c:192:1: warning: data definition has no type or storage class
 MODULE_DEVICE_TABLE(of, atmel_serial_dt_ids);
 ^
drivers/tty/serial/atmel_serial.c:192:1: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE' [-Werror=implicit-int]
drivers/tty/serial/atmel_serial.c:192:1: warning: parameter names (without types) in function declaration

commit c39dfebc7798 has made the driver non-modular and removed the
header file and it is now compiled as a builtin driver. But since
CONFIG_OF is defined for mips so we need the definition of
MODULE_DEVICE_TABLE to compile successfully.

Fixes: c39dfebc7798 ("drivers/tty/serial: make serial/atmel_serial.c explicitly non-modular")
Cc: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>