Input: mousedev - fix implicit conversion warning
On Tue, Jul 11, 2017 at 11:57:10PM -0700, Nick Desaulniers wrote:
> Hi Dmitry, did you get a chance to merge the sugguested revision, yet?

Sorry, no, as it was broken (we lost the assignment to the bytes 2 and
3 of the PS/2 data stream). Here is the version that seems to work, but
at this time I guess I'll push it out to 4.14.

--
Dmitry

Input: mousedev - fix implicit conversion warning

From: Nick Desaulniers <nick.desaulniers@gmail.com>

Clang warns:

drivers/input/mousedev.c:653:63: error: implicit conversion from 'int'
to 'signed char' changes value from 200 to -56
[-Wconstant-conversion]
  client->ps2[1] = 0x60; client->ps2[2] = 3; client->ps2[3] = 200;
                                                            ~ ^~~
As the PS2 data is really a stream of bytes, let's switch to using u8 type
for it, which silences this warning.

Signed-off-by: Nick Desaulniers <nick.desaulniers@gmail.com>
Patchwork-Id: 9753771
Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>