mm/hugetlb.c: mark alloc_gigantic_page stub inline
A cleanup patch introduced a new stub helper function but
accidentally did not mark that 'inline' as all the other
stubs are here, and this causes a warning when it is
not used:

mm/hugetlb.c:1166:21: error: 'alloc_gigantic_page' defined but not used [-Werror=unused-function]

Fixes: akpm-current ("mm/hugetlb.c: rename some allocation functions")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>