PCI: provide of_pci_get_host_bridge_resources helper
The pcie-rcar driver can be built for any ARM platform (for COMPILE_TEST)
including those without CONFIG_OF enabled, and that results in a compile-time
error:

drivers/pci/host/pcie-rcar.c: In function 'rcar_pcie_parse_request_of_pci_ranges':
drivers/pci/host/pcie-rcar.c:939:8: error: implicit declaration of function 'of_pci_get_host_bridge_resources' [-Werror=implicit-function-declaration]
  err = of_pci_get_host_bridge_resources(np, 0, 0xff, &pci->resources, &iobase);

In order to allow compile-testing on all platforms, this adds a
of_pci_get_host_bridge_resources() helper stub function that gets
used when CONFIG_OF_ADDRESS is disabled. This mirrors what we do for
other OF-specific functions.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 5d2917d469fa ("PCI: rcar: Convert to DT resource parsing API")