cgroup: define empty cftype structure for !CONFIG_CGROUPS
There is a new forward declaration for two global cftype arrays, but
that fails to build when CONFIG_CGROUPS is disabled:

In file included from /git/arm-soc/block/bfq-iosched.c:105:0:
block/bfq-iosched.h:820:22: error: array type has incomplete element type 'struct cftype'
 extern struct cftype bfq_blkcg_legacy_files[];
 extern struct cftype bfq_blkg_files[];

This adds an empty definition for the type to make it build again.

Fixes: ea25da48086d ("block, bfq: split bfq-iosched.c into multiple source files")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>