block: partitions: mac: Put mac_fix_string() inside #ifdef section
The function is only used when CONFIG_PPC_PMAC=y, put it inside the
existing #ifdef section. This fixes the following warning when building
with clang:

block/partitions/mac.c:22:20: error: unused function 'mac_fix_string'
    [-Werror,-Wunused-function]

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>