crypto: tcrypt: Fix linkage error on ARM on division of s64
gcc 4.7.3 for ARM on Ubuntu couldn't link tcrypt module because of
division of s64:
	ERROR: "__aeabi_ldivmod" [crypto/tcrypt.ko] undefined!

Fixes: 087bcd225c56 ("crypto: tcrypt - Add speed tests for SHA multibuffer algorithms")
Signed-off-by: Krzysztof Kozlowski <k.kozlowski@samsung.com>