linux-next: build failure after merge of the pci tree
Hi Bjorn,

After merging the pci tree, today's linux-next build (powerpc
allyesconfig) failed like this:

In file included from include/linux/kvm_host.h:20:0,
                 from arch/powerpc/kernel/asm-offsets.c:54:
include/linux/msi.h:174:21: fatal error: asm/msi.h: No such file or directory

Caused by commit

  f19eafec930f ("PCI: altera: Add Altera PCIe MSI driver")

I have disabled that driver for today:

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Mon, 2 Nov 2015 02:12:54 +1100
Subject: [PATCH] PCI: altera: disable MSI driver for now

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>