linux-next: build failure after merge of the mfd tree
Hi Stephen, Lee

> After merging the mfd tree, today's linux-next build (x86_64 allmodconfig)
> failed like this:
>
> drivers/regulator/tps65086-regulator.c:194:9: error: implicit declaration of function 'regmap_write_bits' [-Werror=implicit-function-declaration]
>    ret = regmap_write_bits(config->regmap,
>          ^
>
> Caused by commit
>
>   23b92e4cf5fd ("regmap: remove regmap_write_bits()")
>
> from the sound-asoc & regmap trees.
>
> I am not sure why this is suddenly exposed by the mfd tree, but grep
> would have been useful when the regmap tree patch was applied.
>
> I have reverted that regmap commit for today.

Oops, it is my fault. Can you check/test this patch ?

----------------
From: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Date: Tue, 1 Mar 2016 10:12:20 +0900
Subject: [PATCH] regmap: add regmap_force_update_bits()

commit 23b92e4c ("regmap: remove regmap_write_bits()")
removed regmap_write_bits(), we can use regmap_force_update_bits()
instead of it.

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>